// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package core

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
)

// IMicrosoftAccountMultiFactorAuthenticationManager is the WinRT interface Windows.Security.Authentication.Identity.Core.IMicrosoftAccountMultiFactorAuthenticationManager.
// IID: 0fd340a5-f574-4320-a08e-0a19a82322aa
// Exclusive to the Windows.Security.Authentication.Identity.Core.MicrosoftAccountMultiFactorAuthenticationManager runtime class.
type IMicrosoftAccountMultiFactorAuthenticationManager struct {
	syswinrt.IInspectable
}

// IID_IMicrosoftAccountMultiFactorAuthenticationManager is the interface identifier for IMicrosoftAccountMultiFactorAuthenticationManager.
var IID_IMicrosoftAccountMultiFactorAuthenticationManager = win32.GUID{Data1: 0x0fd340a5, Data2: 0xf574, Data3: 0x4320, Data4: [8]byte{0xa0, 0x8e, 0x0a, 0x19, 0xa8, 0x23, 0x22, 0xaa}}

// GetOneTimePassCodeAsync dispatches through IMicrosoftAccountMultiFactorAuthenticationManager's vtable slot 6.
func (self *IMicrosoftAccountMultiFactorAuthenticationManager) GetOneTimePassCodeAsync(userAccountId string, codeLength uint32) (*IAsyncOperationOfMicrosoftAccountMultiFactorOneTimeCodedInfo, error) {
	hUserAccountId, err := winrt.NewHString(userAccountId)
	if err != nil {
		return nil, err
	}
	defer hUserAccountId.Close()
	result := new(*IAsyncOperationOfMicrosoftAccountMultiFactorOneTimeCodedInfo)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hUserAccountId.Raw()), uintptr(codeLength), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// AddDeviceAsync dispatches through IMicrosoftAccountMultiFactorAuthenticationManager's vtable slot 7.
func (self *IMicrosoftAccountMultiFactorAuthenticationManager) AddDeviceAsync(userAccountId string, authenticationToken string, wnsChannelId string) (*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse, error) {
	hUserAccountId, err := winrt.NewHString(userAccountId)
	if err != nil {
		return nil, err
	}
	defer hUserAccountId.Close()
	hAuthenticationToken, err := winrt.NewHString(authenticationToken)
	if err != nil {
		return nil, err
	}
	defer hAuthenticationToken.Close()
	hWnsChannelId, err := winrt.NewHString(wnsChannelId)
	if err != nil {
		return nil, err
	}
	defer hWnsChannelId.Close()
	result := new(*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(hUserAccountId.Raw()), uintptr(hAuthenticationToken.Raw()), uintptr(hWnsChannelId.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemoveDeviceAsync dispatches through IMicrosoftAccountMultiFactorAuthenticationManager's vtable slot 8.
func (self *IMicrosoftAccountMultiFactorAuthenticationManager) RemoveDeviceAsync(userAccountId string) (*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse, error) {
	hUserAccountId, err := winrt.NewHString(userAccountId)
	if err != nil {
		return nil, err
	}
	defer hUserAccountId.Close()
	result := new(*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hUserAccountId.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// UpdateWnsChannelAsync dispatches through IMicrosoftAccountMultiFactorAuthenticationManager's vtable slot 9.
func (self *IMicrosoftAccountMultiFactorAuthenticationManager) UpdateWnsChannelAsync(userAccountId string, channelUri string) (*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse, error) {
	hUserAccountId, err := winrt.NewHString(userAccountId)
	if err != nil {
		return nil, err
	}
	defer hUserAccountId.Close()
	hChannelUri, err := winrt.NewHString(channelUri)
	if err != nil {
		return nil, err
	}
	defer hChannelUri.Close()
	result := new(*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(hUserAccountId.Raw()), uintptr(hChannelUri.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetSessionsAsync dispatches through IMicrosoftAccountMultiFactorAuthenticationManager's vtable slot 10.
func (self *IMicrosoftAccountMultiFactorAuthenticationManager) GetSessionsAsync(userAccountIdList *IIterableOfString) (*IAsyncOperationOfMicrosoftAccountMultiFactorGetSessionsResult, error) {
	result := new(*IAsyncOperationOfMicrosoftAccountMultiFactorGetSessionsResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(userAccountIdList)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetSessionsAndUnregisteredAccountsAsync dispatches through IMicrosoftAccountMultiFactorAuthenticationManager's vtable slot 11.
func (self *IMicrosoftAccountMultiFactorAuthenticationManager) GetSessionsAndUnregisteredAccountsAsync(userAccountIdList *IIterableOfString) (*IAsyncOperationOfMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo, error) {
	result := new(*IAsyncOperationOfMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(userAccountIdList)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ApproveSessionUsingAuthSessionInfoAsync dispatches through IMicrosoftAccountMultiFactorAuthenticationManager's vtable slot 12.
func (self *IMicrosoftAccountMultiFactorAuthenticationManager) ApproveSessionUsingAuthSessionInfoAsync(sessionAuthentictionStatus MicrosoftAccountMultiFactorSessionAuthenticationStatus, authenticationSessionInfo *IMicrosoftAccountMultiFactorSessionInfo) (*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse, error) {
	result := new(*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(sessionAuthentictionStatus), uintptr(unsafe.Pointer(authenticationSessionInfo)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ApproveSessionAsync dispatches through IMicrosoftAccountMultiFactorAuthenticationManager's vtable slot 13.
func (self *IMicrosoftAccountMultiFactorAuthenticationManager) ApproveSessionAsync(sessionAuthentictionStatus MicrosoftAccountMultiFactorSessionAuthenticationStatus, userAccountId string, sessionId string, sessionAuthenticationType MicrosoftAccountMultiFactorAuthenticationType) (*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse, error) {
	hUserAccountId, err := winrt.NewHString(userAccountId)
	if err != nil {
		return nil, err
	}
	defer hUserAccountId.Close()
	hSessionId, err := winrt.NewHString(sessionId)
	if err != nil {
		return nil, err
	}
	defer hSessionId.Close()
	result := new(*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(sessionAuthentictionStatus), uintptr(hUserAccountId.Raw()), uintptr(hSessionId.Raw()), uintptr(sessionAuthenticationType), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DenySessionUsingAuthSessionInfoAsync dispatches through IMicrosoftAccountMultiFactorAuthenticationManager's vtable slot 14.
func (self *IMicrosoftAccountMultiFactorAuthenticationManager) DenySessionUsingAuthSessionInfoAsync(authenticationSessionInfo *IMicrosoftAccountMultiFactorSessionInfo) (*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse, error) {
	result := new(*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(authenticationSessionInfo)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DenySessionAsync dispatches through IMicrosoftAccountMultiFactorAuthenticationManager's vtable slot 15.
func (self *IMicrosoftAccountMultiFactorAuthenticationManager) DenySessionAsync(userAccountId string, sessionId string, sessionAuthenticationType MicrosoftAccountMultiFactorAuthenticationType) (*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse, error) {
	hUserAccountId, err := winrt.NewHString(userAccountId)
	if err != nil {
		return nil, err
	}
	defer hUserAccountId.Close()
	hSessionId, err := winrt.NewHString(sessionId)
	if err != nil {
		return nil, err
	}
	defer hSessionId.Close()
	result := new(*IAsyncOperationOfMicrosoftAccountMultiFactorServiceResponse)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)), uintptr(hUserAccountId.Raw()), uintptr(hSessionId.Raw()), uintptr(sessionAuthenticationType), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMicrosoftAccountMultiFactorAuthenticatorStatics is the WinRT interface Windows.Security.Authentication.Identity.Core.IMicrosoftAccountMultiFactorAuthenticatorStatics.
// IID: d964c2e6-f446-4c71-8b79-6ea4024aa9b8
// Exclusive to the Windows.Security.Authentication.Identity.Core.MicrosoftAccountMultiFactorAuthenticationManager runtime class.
type IMicrosoftAccountMultiFactorAuthenticatorStatics struct {
	syswinrt.IInspectable
}

// IID_IMicrosoftAccountMultiFactorAuthenticatorStatics is the interface identifier for IMicrosoftAccountMultiFactorAuthenticatorStatics.
var IID_IMicrosoftAccountMultiFactorAuthenticatorStatics = win32.GUID{Data1: 0xd964c2e6, Data2: 0xf446, Data3: 0x4c71, Data4: [8]byte{0x8b, 0x79, 0x6e, 0xa4, 0x02, 0x4a, 0xa9, 0xb8}}

// Current (propget get_Current) dispatches through IMicrosoftAccountMultiFactorAuthenticatorStatics's vtable slot 6.
func (self *IMicrosoftAccountMultiFactorAuthenticatorStatics) Current() (*IMicrosoftAccountMultiFactorAuthenticationManager, error) {
	result := new(*IMicrosoftAccountMultiFactorAuthenticationManager)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMicrosoftAccountMultiFactorGetSessionsResult is the WinRT interface Windows.Security.Authentication.Identity.Core.IMicrosoftAccountMultiFactorGetSessionsResult.
// IID: 4e23a9a0-e9fa-497a-95de-6d5747bf974c
// Exclusive to the Windows.Security.Authentication.Identity.Core.MicrosoftAccountMultiFactorGetSessionsResult runtime class.
type IMicrosoftAccountMultiFactorGetSessionsResult struct {
	syswinrt.IInspectable
}

// IID_IMicrosoftAccountMultiFactorGetSessionsResult is the interface identifier for IMicrosoftAccountMultiFactorGetSessionsResult.
var IID_IMicrosoftAccountMultiFactorGetSessionsResult = win32.GUID{Data1: 0x4e23a9a0, Data2: 0xe9fa, Data3: 0x497a, Data4: [8]byte{0x95, 0xde, 0x6d, 0x57, 0x47, 0xbf, 0x97, 0x4c}}

// Sessions (propget get_Sessions) dispatches through IMicrosoftAccountMultiFactorGetSessionsResult's vtable slot 6.
func (self *IMicrosoftAccountMultiFactorGetSessionsResult) Sessions() (*IVectorViewOfMicrosoftAccountMultiFactorSessionInfo, error) {
	result := new(*IVectorViewOfMicrosoftAccountMultiFactorSessionInfo)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ServiceResponse (propget get_ServiceResponse) dispatches through IMicrosoftAccountMultiFactorGetSessionsResult's vtable slot 7.
func (self *IMicrosoftAccountMultiFactorGetSessionsResult) ServiceResponse() (MicrosoftAccountMultiFactorServiceResponse, error) {
	result := new(MicrosoftAccountMultiFactorServiceResponse)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMicrosoftAccountMultiFactorOneTimeCodedInfo is the WinRT interface Windows.Security.Authentication.Identity.Core.IMicrosoftAccountMultiFactorOneTimeCodedInfo.
// IID: 82ba264b-d87c-4668-a976-40cfae547d08
// Exclusive to the Windows.Security.Authentication.Identity.Core.MicrosoftAccountMultiFactorOneTimeCodedInfo runtime class.
type IMicrosoftAccountMultiFactorOneTimeCodedInfo struct {
	syswinrt.IInspectable
}

// IID_IMicrosoftAccountMultiFactorOneTimeCodedInfo is the interface identifier for IMicrosoftAccountMultiFactorOneTimeCodedInfo.
var IID_IMicrosoftAccountMultiFactorOneTimeCodedInfo = win32.GUID{Data1: 0x82ba264b, Data2: 0xd87c, Data3: 0x4668, Data4: [8]byte{0xa9, 0x76, 0x40, 0xcf, 0xae, 0x54, 0x7d, 0x08}}

// Code (propget get_Code) dispatches through IMicrosoftAccountMultiFactorOneTimeCodedInfo's vtable slot 6.
func (self *IMicrosoftAccountMultiFactorOneTimeCodedInfo) Code() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// TimeInterval (propget get_TimeInterval) dispatches through IMicrosoftAccountMultiFactorOneTimeCodedInfo's vtable slot 7.
func (self *IMicrosoftAccountMultiFactorOneTimeCodedInfo) TimeInterval() (foundation.TimeSpan, error) {
	result := new(foundation.TimeSpan)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// TimeToLive (propget get_TimeToLive) dispatches through IMicrosoftAccountMultiFactorOneTimeCodedInfo's vtable slot 8.
func (self *IMicrosoftAccountMultiFactorOneTimeCodedInfo) TimeToLive() (foundation.TimeSpan, error) {
	result := new(foundation.TimeSpan)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ServiceResponse (propget get_ServiceResponse) dispatches through IMicrosoftAccountMultiFactorOneTimeCodedInfo's vtable slot 9.
func (self *IMicrosoftAccountMultiFactorOneTimeCodedInfo) ServiceResponse() (MicrosoftAccountMultiFactorServiceResponse, error) {
	result := new(MicrosoftAccountMultiFactorServiceResponse)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMicrosoftAccountMultiFactorSessionInfo is the WinRT interface Windows.Security.Authentication.Identity.Core.IMicrosoftAccountMultiFactorSessionInfo.
// IID: 5f7eabb4-a278-4635-b765-b494eb260af4
// Exclusive to the Windows.Security.Authentication.Identity.Core.MicrosoftAccountMultiFactorSessionInfo runtime class.
type IMicrosoftAccountMultiFactorSessionInfo struct {
	syswinrt.IInspectable
}

// IID_IMicrosoftAccountMultiFactorSessionInfo is the interface identifier for IMicrosoftAccountMultiFactorSessionInfo.
var IID_IMicrosoftAccountMultiFactorSessionInfo = win32.GUID{Data1: 0x5f7eabb4, Data2: 0xa278, Data3: 0x4635, Data4: [8]byte{0xb7, 0x65, 0xb4, 0x94, 0xeb, 0x26, 0x0a, 0xf4}}

// UserAccountId (propget get_UserAccountId) dispatches through IMicrosoftAccountMultiFactorSessionInfo's vtable slot 6.
func (self *IMicrosoftAccountMultiFactorSessionInfo) UserAccountId() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// SessionId (propget get_SessionId) dispatches through IMicrosoftAccountMultiFactorSessionInfo's vtable slot 7.
func (self *IMicrosoftAccountMultiFactorSessionInfo) SessionId() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// DisplaySessionId (propget get_DisplaySessionId) dispatches through IMicrosoftAccountMultiFactorSessionInfo's vtable slot 8.
func (self *IMicrosoftAccountMultiFactorSessionInfo) DisplaySessionId() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// ApprovalStatus (propget get_ApprovalStatus) dispatches through IMicrosoftAccountMultiFactorSessionInfo's vtable slot 9.
func (self *IMicrosoftAccountMultiFactorSessionInfo) ApprovalStatus() (MicrosoftAccountMultiFactorSessionApprovalStatus, error) {
	result := new(MicrosoftAccountMultiFactorSessionApprovalStatus)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// AuthenticationType (propget get_AuthenticationType) dispatches through IMicrosoftAccountMultiFactorSessionInfo's vtable slot 10.
func (self *IMicrosoftAccountMultiFactorSessionInfo) AuthenticationType() (MicrosoftAccountMultiFactorAuthenticationType, error) {
	result := new(MicrosoftAccountMultiFactorAuthenticationType)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RequestTime (propget get_RequestTime) dispatches through IMicrosoftAccountMultiFactorSessionInfo's vtable slot 11.
func (self *IMicrosoftAccountMultiFactorSessionInfo) RequestTime() (foundation.DateTime, error) {
	result := new(foundation.DateTime)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ExpirationTime (propget get_ExpirationTime) dispatches through IMicrosoftAccountMultiFactorSessionInfo's vtable slot 12.
func (self *IMicrosoftAccountMultiFactorSessionInfo) ExpirationTime() (foundation.DateTime, error) {
	result := new(foundation.DateTime)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo is the WinRT interface Windows.Security.Authentication.Identity.Core.IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo.
// IID: aa7ec5fb-da3f-4088-a20d-5618afadb2e5
// Exclusive to the Windows.Security.Authentication.Identity.Core.MicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo runtime class.
type IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo struct {
	syswinrt.IInspectable
}

// IID_IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo is the interface identifier for IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo.
var IID_IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo = win32.GUID{Data1: 0xaa7ec5fb, Data2: 0xda3f, Data3: 0x4088, Data4: [8]byte{0xa2, 0x0d, 0x56, 0x18, 0xaf, 0xad, 0xb2, 0xe5}}

// Sessions (propget get_Sessions) dispatches through IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo's vtable slot 6.
func (self *IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo) Sessions() (*IVectorViewOfMicrosoftAccountMultiFactorSessionInfo, error) {
	result := new(*IVectorViewOfMicrosoftAccountMultiFactorSessionInfo)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// UnregisteredAccounts (propget get_UnregisteredAccounts) dispatches through IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo's vtable slot 7.
func (self *IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo) UnregisteredAccounts() (*IVectorViewOfString, error) {
	result := new(*IVectorViewOfString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ServiceResponse (propget get_ServiceResponse) dispatches through IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo's vtable slot 8.
func (self *IMicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo) ServiceResponse() (MicrosoftAccountMultiFactorServiceResponse, error) {
	result := new(MicrosoftAccountMultiFactorServiceResponse)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
