// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package policies

import (
	"fmt"
)

// NamedPolicyKind is Windows.Management.Policies.NamedPolicyKind.
type NamedPolicyKind int32

const (
	NamedPolicyKindInvalid NamedPolicyKind = 0
	NamedPolicyKindBinary  NamedPolicyKind = 1
	NamedPolicyKindBoolean NamedPolicyKind = 2
	NamedPolicyKindInt32   NamedPolicyKind = 3
	NamedPolicyKindInt64   NamedPolicyKind = 4
	NamedPolicyKindString  NamedPolicyKind = 5
)

// String returns the NamedPolicyKind constant's name, or its numeric form when
// the value is not a known constant.
func (e NamedPolicyKind) String() string {
	switch e {
	case NamedPolicyKindInvalid:
		return "NamedPolicyKindInvalid"
	case NamedPolicyKindBinary:
		return "NamedPolicyKindBinary"
	case NamedPolicyKindBoolean:
		return "NamedPolicyKindBoolean"
	case NamedPolicyKindInt32:
		return "NamedPolicyKindInt32"
	case NamedPolicyKindInt64:
		return "NamedPolicyKindInt64"
	case NamedPolicyKindString:
		return "NamedPolicyKindString"
	default:
		return fmt.Sprintf("NamedPolicyKind(%d)", int32(e))
	}
}
