// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package usb

import (
	"fmt"
)

// UsbControlRecipient is Windows.Devices.Usb.UsbControlRecipient.
type UsbControlRecipient int32

const (
	UsbControlRecipientDevice             UsbControlRecipient = 0
	UsbControlRecipientSpecifiedInterface UsbControlRecipient = 1
	UsbControlRecipientEndpoint           UsbControlRecipient = 2
	UsbControlRecipientOther              UsbControlRecipient = 3
	UsbControlRecipientDefaultInterface   UsbControlRecipient = 4
)

// String returns the UsbControlRecipient constant's name, or its numeric form when
// the value is not a known constant.
func (e UsbControlRecipient) String() string {
	switch e {
	case UsbControlRecipientDevice:
		return "UsbControlRecipientDevice"
	case UsbControlRecipientSpecifiedInterface:
		return "UsbControlRecipientSpecifiedInterface"
	case UsbControlRecipientEndpoint:
		return "UsbControlRecipientEndpoint"
	case UsbControlRecipientOther:
		return "UsbControlRecipientOther"
	case UsbControlRecipientDefaultInterface:
		return "UsbControlRecipientDefaultInterface"
	default:
		return fmt.Sprintf("UsbControlRecipient(%d)", int32(e))
	}
}

// UsbControlTransferType is Windows.Devices.Usb.UsbControlTransferType.
type UsbControlTransferType int32

const (
	UsbControlTransferTypeStandard UsbControlTransferType = 0
	UsbControlTransferTypeClass    UsbControlTransferType = 1
	UsbControlTransferTypeVendor   UsbControlTransferType = 2
)

// String returns the UsbControlTransferType constant's name, or its numeric form when
// the value is not a known constant.
func (e UsbControlTransferType) String() string {
	switch e {
	case UsbControlTransferTypeStandard:
		return "UsbControlTransferTypeStandard"
	case UsbControlTransferTypeClass:
		return "UsbControlTransferTypeClass"
	case UsbControlTransferTypeVendor:
		return "UsbControlTransferTypeVendor"
	default:
		return fmt.Sprintf("UsbControlTransferType(%d)", int32(e))
	}
}

// UsbEndpointType is Windows.Devices.Usb.UsbEndpointType.
type UsbEndpointType int32

const (
	UsbEndpointTypeControl     UsbEndpointType = 0
	UsbEndpointTypeIsochronous UsbEndpointType = 1
	UsbEndpointTypeBulk        UsbEndpointType = 2
	UsbEndpointTypeInterrupt   UsbEndpointType = 3
)

// String returns the UsbEndpointType constant's name, or its numeric form when
// the value is not a known constant.
func (e UsbEndpointType) String() string {
	switch e {
	case UsbEndpointTypeControl:
		return "UsbEndpointTypeControl"
	case UsbEndpointTypeIsochronous:
		return "UsbEndpointTypeIsochronous"
	case UsbEndpointTypeBulk:
		return "UsbEndpointTypeBulk"
	case UsbEndpointTypeInterrupt:
		return "UsbEndpointTypeInterrupt"
	default:
		return fmt.Sprintf("UsbEndpointType(%d)", int32(e))
	}
}

// UsbReadOptions is Windows.Devices.Usb.UsbReadOptions.
// Bitmask — values may be combined with |.
type UsbReadOptions uint32

const (
	UsbReadOptionsNone                              UsbReadOptions = 0
	UsbReadOptionsAutoClearStall                    UsbReadOptions = 1
	UsbReadOptionsOverrideAutomaticBufferManagement UsbReadOptions = 2
	UsbReadOptionsIgnoreShortPacket                 UsbReadOptions = 4
	UsbReadOptionsAllowPartialReads                 UsbReadOptions = 8
)

// String returns the UsbReadOptions constant's name, or its numeric form when
// the value is not a known constant.
func (e UsbReadOptions) String() string {
	switch e {
	case UsbReadOptionsNone:
		return "UsbReadOptionsNone"
	case UsbReadOptionsAutoClearStall:
		return "UsbReadOptionsAutoClearStall"
	case UsbReadOptionsOverrideAutomaticBufferManagement:
		return "UsbReadOptionsOverrideAutomaticBufferManagement"
	case UsbReadOptionsIgnoreShortPacket:
		return "UsbReadOptionsIgnoreShortPacket"
	case UsbReadOptionsAllowPartialReads:
		return "UsbReadOptionsAllowPartialReads"
	default:
		return fmt.Sprintf("UsbReadOptions(%d)", uint32(e))
	}
}

// UsbTransferDirection is Windows.Devices.Usb.UsbTransferDirection.
type UsbTransferDirection int32

const (
	UsbTransferDirectionOut UsbTransferDirection = 0
	UsbTransferDirectionIn  UsbTransferDirection = 1
)

// String returns the UsbTransferDirection constant's name, or its numeric form when
// the value is not a known constant.
func (e UsbTransferDirection) String() string {
	switch e {
	case UsbTransferDirectionOut:
		return "UsbTransferDirectionOut"
	case UsbTransferDirectionIn:
		return "UsbTransferDirectionIn"
	default:
		return fmt.Sprintf("UsbTransferDirection(%d)", int32(e))
	}
}

// UsbWriteOptions is Windows.Devices.Usb.UsbWriteOptions.
// Bitmask — values may be combined with |.
type UsbWriteOptions uint32

const (
	UsbWriteOptionsNone                 UsbWriteOptions = 0
	UsbWriteOptionsAutoClearStall       UsbWriteOptions = 1
	UsbWriteOptionsShortPacketTerminate UsbWriteOptions = 2
)

// String returns the UsbWriteOptions constant's name, or its numeric form when
// the value is not a known constant.
func (e UsbWriteOptions) String() string {
	switch e {
	case UsbWriteOptionsNone:
		return "UsbWriteOptionsNone"
	case UsbWriteOptionsAutoClearStall:
		return "UsbWriteOptionsAutoClearStall"
	case UsbWriteOptionsShortPacketTerminate:
		return "UsbWriteOptionsShortPacketTerminate"
	default:
		return fmt.Sprintf("UsbWriteOptions(%d)", uint32(e))
	}
}
