// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package input

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// TypedEventHandlerOfMouseDeviceAndMouseEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.MouseDevice, Windows.Devices.Input.MouseEventArgs>.
// IID: 5d72e594-28e4-5895-a34b-ea910f70fdbb
type TypedEventHandlerOfMouseDeviceAndMouseEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfMouseDeviceAndMouseEventArgs is the delegate identifier for TypedEventHandlerOfMouseDeviceAndMouseEventArgs.
var IID_TypedEventHandlerOfMouseDeviceAndMouseEventArgs = win32.GUID{Data1: 0x5d72e594, Data2: 0x28e4, Data3: 0x5895, Data4: [8]byte{0xa3, 0x4b, 0xea, 0x91, 0x0f, 0x70, 0xfd, 0xbb}}

// NewTypedEventHandlerOfMouseDeviceAndMouseEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.MouseDevice, Windows.Devices.Input.MouseEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfMouseDeviceAndMouseEventArgs(fn func(sender *IMouseDevice, args *IMouseEventArgs)) (*TypedEventHandlerOfMouseDeviceAndMouseEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfMouseDeviceAndMouseEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IMouseDevice)(unsafe.Pointer(raw[0])), (*IMouseEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfMouseDeviceAndMouseEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfMouseDeviceAndMouseEventArgs) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfMouseDeviceAndMouseEventArgs) Close() { h.delegate.Release() }

// TypedEventHandlerOfPenButtonListenerAndObject is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenButtonListener, Object>.
// IID: 0a0ee5ed-041b-5569-b4a4-a1e58f1343a2
type TypedEventHandlerOfPenButtonListenerAndObject struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfPenButtonListenerAndObject is the delegate identifier for TypedEventHandlerOfPenButtonListenerAndObject.
var IID_TypedEventHandlerOfPenButtonListenerAndObject = win32.GUID{Data1: 0x0a0ee5ed, Data2: 0x041b, Data3: 0x5569, Data4: [8]byte{0xb4, 0xa4, 0xa1, 0xe5, 0x8f, 0x13, 0x43, 0xa2}}

// NewTypedEventHandlerOfPenButtonListenerAndObject wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenButtonListener, Object>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfPenButtonListenerAndObject(fn func(sender *IPenButtonListener, args *syswinrt.IInspectable)) (*TypedEventHandlerOfPenButtonListenerAndObject, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfPenButtonListenerAndObject, 2, func(raw []uintptr) uintptr {
		fn((*IPenButtonListener)(unsafe.Pointer(raw[0])), (*syswinrt.IInspectable)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfPenButtonListenerAndObject{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfPenButtonListenerAndObject) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfPenButtonListenerAndObject) Close() { h.delegate.Release() }

// TypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenButtonListener, Windows.Devices.Input.PenTailButtonClickedEventArgs>.
// IID: 2eda7109-f1c9-5f26-a054-3d25062cc0de
type TypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs is the delegate identifier for TypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs.
var IID_TypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs = win32.GUID{Data1: 0x2eda7109, Data2: 0xf1c9, Data3: 0x5f26, Data4: [8]byte{0xa0, 0x54, 0x3d, 0x25, 0x06, 0x2c, 0xc0, 0xde}}

// NewTypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenButtonListener, Windows.Devices.Input.PenTailButtonClickedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs(fn func(sender *IPenButtonListener, args *IPenTailButtonClickedEventArgs)) (*TypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IPenButtonListener)(unsafe.Pointer(raw[0])), (*IPenTailButtonClickedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfPenButtonListenerAndPenTailButtonClickedEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenButtonListener, Windows.Devices.Input.PenTailButtonDoubleClickedEventArgs>.
// IID: e6e58d94-6f7b-593f-81f0-033150b4432c
type TypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs is the delegate identifier for TypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs.
var IID_TypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs = win32.GUID{Data1: 0xe6e58d94, Data2: 0x6f7b, Data3: 0x593f, Data4: [8]byte{0x81, 0xf0, 0x03, 0x31, 0x50, 0xb4, 0x43, 0x2c}}

// NewTypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenButtonListener, Windows.Devices.Input.PenTailButtonDoubleClickedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs(fn func(sender *IPenButtonListener, args *IPenTailButtonDoubleClickedEventArgs)) (*TypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IPenButtonListener)(unsafe.Pointer(raw[0])), (*IPenTailButtonDoubleClickedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfPenButtonListenerAndPenTailButtonDoubleClickedEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenButtonListener, Windows.Devices.Input.PenTailButtonLongPressedEventArgs>.
// IID: ca6dab1f-20d6-52b0-94ce-6dcc75a1a984
type TypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs is the delegate identifier for TypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs.
var IID_TypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs = win32.GUID{Data1: 0xca6dab1f, Data2: 0x20d6, Data3: 0x52b0, Data4: [8]byte{0x94, 0xce, 0x6d, 0xcc, 0x75, 0xa1, 0xa9, 0x84}}

// NewTypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenButtonListener, Windows.Devices.Input.PenTailButtonLongPressedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs(fn func(sender *IPenButtonListener, args *IPenTailButtonLongPressedEventArgs)) (*TypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IPenButtonListener)(unsafe.Pointer(raw[0])), (*IPenTailButtonLongPressedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfPenButtonListenerAndPenTailButtonLongPressedEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfPenDockListenerAndObject is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenDockListener, Object>.
// IID: 7ceae82f-499a-5b31-a1d8-3b11c53c7871
type TypedEventHandlerOfPenDockListenerAndObject struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfPenDockListenerAndObject is the delegate identifier for TypedEventHandlerOfPenDockListenerAndObject.
var IID_TypedEventHandlerOfPenDockListenerAndObject = win32.GUID{Data1: 0x7ceae82f, Data2: 0x499a, Data3: 0x5b31, Data4: [8]byte{0xa1, 0xd8, 0x3b, 0x11, 0xc5, 0x3c, 0x78, 0x71}}

// NewTypedEventHandlerOfPenDockListenerAndObject wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenDockListener, Object>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfPenDockListenerAndObject(fn func(sender *IPenDockListener, args *syswinrt.IInspectable)) (*TypedEventHandlerOfPenDockListenerAndObject, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfPenDockListenerAndObject, 2, func(raw []uintptr) uintptr {
		fn((*IPenDockListener)(unsafe.Pointer(raw[0])), (*syswinrt.IInspectable)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfPenDockListenerAndObject{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfPenDockListenerAndObject) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfPenDockListenerAndObject) Close() { h.delegate.Release() }

// TypedEventHandlerOfPenDockListenerAndPenDockedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenDockListener, Windows.Devices.Input.PenDockedEventArgs>.
// IID: 19786a6c-8e23-5de7-a773-e711a5a068c5
type TypedEventHandlerOfPenDockListenerAndPenDockedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfPenDockListenerAndPenDockedEventArgs is the delegate identifier for TypedEventHandlerOfPenDockListenerAndPenDockedEventArgs.
var IID_TypedEventHandlerOfPenDockListenerAndPenDockedEventArgs = win32.GUID{Data1: 0x19786a6c, Data2: 0x8e23, Data3: 0x5de7, Data4: [8]byte{0xa7, 0x73, 0xe7, 0x11, 0xa5, 0xa0, 0x68, 0xc5}}

// NewTypedEventHandlerOfPenDockListenerAndPenDockedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenDockListener, Windows.Devices.Input.PenDockedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfPenDockListenerAndPenDockedEventArgs(fn func(sender *IPenDockListener, args *IPenDockedEventArgs)) (*TypedEventHandlerOfPenDockListenerAndPenDockedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfPenDockListenerAndPenDockedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IPenDockListener)(unsafe.Pointer(raw[0])), (*IPenDockedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfPenDockListenerAndPenDockedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfPenDockListenerAndPenDockedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfPenDockListenerAndPenDockedEventArgs) Close() { h.delegate.Release() }

// TypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenDockListener, Windows.Devices.Input.PenUndockedEventArgs>.
// IID: 51dba508-3194-5c91-a2e7-f94637e75a13
type TypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs is the delegate identifier for TypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs.
var IID_TypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs = win32.GUID{Data1: 0x51dba508, Data2: 0x3194, Data3: 0x5c91, Data4: [8]byte{0xa2, 0xe7, 0xf9, 0x46, 0x37, 0xe7, 0x5a, 0x13}}

// NewTypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.PenDockListener, Windows.Devices.Input.PenUndockedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs(fn func(sender *IPenDockListener, args *IPenUndockedEventArgs)) (*TypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IPenDockListener)(unsafe.Pointer(raw[0])), (*IPenUndockedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfPenDockListenerAndPenUndockedEventArgs) Close() { h.delegate.Release() }
