// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package enumeration

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
	storagestreams "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/storage/streams"
)

// IAsyncOperationOfDeviceInformation is the WinRT interface Windows.Foundation.IAsyncOperation`1<Windows.Devices.Enumeration.DeviceInformation>.
// IID: 07faa053-eb2f-5cba-b25b-d9d57be6715f
// Requires: Windows.Foundation.IAsyncInfo.
type IAsyncOperationOfDeviceInformation struct {
	syswinrt.IInspectable
}

// IID_IAsyncOperationOfDeviceInformation is the interface identifier for IAsyncOperationOfDeviceInformation.
var IID_IAsyncOperationOfDeviceInformation = win32.GUID{Data1: 0x07faa053, Data2: 0xeb2f, Data3: 0x5cba, Data4: [8]byte{0xb2, 0x5b, 0xd9, 0xd5, 0x7b, 0xe6, 0x71, 0x5f}}

// SetCompleted (propput put_Completed) dispatches through IAsyncOperationOfDeviceInformation's vtable slot 6.
// A nil handler passes NULL at the ABI (WinRT accepts it where a handler may be cleared).
func (self *IAsyncOperationOfDeviceInformation) SetCompleted(handler *AsyncOperationCompletedHandlerOfDeviceInformation) error {
	_handler := uintptr(0)
	if handler != nil {
		_handler = handler.Ptr()
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), _handler)
	return win32.ErrIfFailed(int32(r1))
}

// slot 7: get_Completed skipped: parameterized type Windows.Foundation.AsyncOperationCompletedHandler`1

// GetResults dispatches through IAsyncOperationOfDeviceInformation's vtable slot 8.
func (self *IAsyncOperationOfDeviceInformation) GetResults() (*IDeviceInformation, error) {
	result := new(*IDeviceInformation)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Await registers a Completed handler and blocks until IAsyncOperationOfDeviceInformation reaches
// a terminal state, then returns GetResults() — or, when the status is not
// Completed, an error carrying the status and the IAsyncInfo error code (see
// winrt.AsyncError). Safe on an operation that already completed: WinRT
// invokes a handler assigned after completion immediately. put_Completed
// accepts a single assignment per operation, so Await (or SetCompleted) can
// be used at most once per instance. Await blocks indefinitely by design; a
// context-aware variant is future work. The completion signal is sent from
// the handler's Invoke, which the delegate runtime runs on a fresh goroutine
// — it never contends with the runtime's callback worker, so a completed
// operation cannot deadlock Await.
func (self *IAsyncOperationOfDeviceInformation) Await() (*IDeviceInformation, error) {
	completion := make(chan foundation.AsyncStatus, 1)
	handler, err := NewAsyncOperationCompletedHandlerOfDeviceInformation(func(_ *IAsyncOperationOfDeviceInformation, asyncStatus foundation.AsyncStatus) {
		completion <- asyncStatus
	})
	if err != nil {
		return nil, err
	}
	defer handler.Close()
	if err := self.SetCompleted(handler); err != nil {
		return nil, err
	}
	status := <-completion
	if status != foundation.AsyncStatusCompleted {
		info, err := winrt.QueryInterface[foundation.IAsyncInfo](unsafe.Pointer(self), &foundation.IID_IAsyncInfo)
		if err != nil {
			return nil, err
		}
		defer info.Release()
		code, err := info.ErrorCode()
		if err != nil {
			return nil, err
		}
		return nil, winrt.AsyncError(int32(status), code)
	}
	return self.GetResults()
}

// IAsyncOperationOfDeviceInformationCollection is the WinRT interface Windows.Foundation.IAsyncOperation`1<Windows.Devices.Enumeration.DeviceInformationCollection>.
// IID: 45180254-082e-5274-b2e7-ac0517f44d07
// Requires: Windows.Foundation.IAsyncInfo.
type IAsyncOperationOfDeviceInformationCollection struct {
	syswinrt.IInspectable
}

// IID_IAsyncOperationOfDeviceInformationCollection is the interface identifier for IAsyncOperationOfDeviceInformationCollection.
var IID_IAsyncOperationOfDeviceInformationCollection = win32.GUID{Data1: 0x45180254, Data2: 0x082e, Data3: 0x5274, Data4: [8]byte{0xb2, 0xe7, 0xac, 0x05, 0x17, 0xf4, 0x4d, 0x07}}

// SetCompleted (propput put_Completed) dispatches through IAsyncOperationOfDeviceInformationCollection's vtable slot 6.
// A nil handler passes NULL at the ABI (WinRT accepts it where a handler may be cleared).
func (self *IAsyncOperationOfDeviceInformationCollection) SetCompleted(handler *AsyncOperationCompletedHandlerOfDeviceInformationCollection) error {
	_handler := uintptr(0)
	if handler != nil {
		_handler = handler.Ptr()
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), _handler)
	return win32.ErrIfFailed(int32(r1))
}

// slot 7: get_Completed skipped: parameterized type Windows.Foundation.AsyncOperationCompletedHandler`1

// GetResults dispatches through IAsyncOperationOfDeviceInformationCollection's vtable slot 8.
// The return value's class Windows.Devices.Enumeration.DeviceInformationCollection is projected as IInspectable (the class is not emitted this wave).
func (self *IAsyncOperationOfDeviceInformationCollection) GetResults() (*syswinrt.IInspectable, error) {
	result := new(*syswinrt.IInspectable)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Await registers a Completed handler and blocks until IAsyncOperationOfDeviceInformationCollection reaches
// a terminal state, then returns GetResults() — or, when the status is not
// Completed, an error carrying the status and the IAsyncInfo error code (see
// winrt.AsyncError). Safe on an operation that already completed: WinRT
// invokes a handler assigned after completion immediately. put_Completed
// accepts a single assignment per operation, so Await (or SetCompleted) can
// be used at most once per instance. Await blocks indefinitely by design; a
// context-aware variant is future work. The completion signal is sent from
// the handler's Invoke, which the delegate runtime runs on a fresh goroutine
// — it never contends with the runtime's callback worker, so a completed
// operation cannot deadlock Await.
func (self *IAsyncOperationOfDeviceInformationCollection) Await() (*syswinrt.IInspectable, error) {
	completion := make(chan foundation.AsyncStatus, 1)
	handler, err := NewAsyncOperationCompletedHandlerOfDeviceInformationCollection(func(_ *IAsyncOperationOfDeviceInformationCollection, asyncStatus foundation.AsyncStatus) {
		completion <- asyncStatus
	})
	if err != nil {
		return nil, err
	}
	defer handler.Close()
	if err := self.SetCompleted(handler); err != nil {
		return nil, err
	}
	status := <-completion
	if status != foundation.AsyncStatusCompleted {
		info, err := winrt.QueryInterface[foundation.IAsyncInfo](unsafe.Pointer(self), &foundation.IID_IAsyncInfo)
		if err != nil {
			return nil, err
		}
		defer info.Release()
		code, err := info.ErrorCode()
		if err != nil {
			return nil, err
		}
		return nil, winrt.AsyncError(int32(status), code)
	}
	return self.GetResults()
}

// IAsyncOperationOfDevicePairingResult is the WinRT interface Windows.Foundation.IAsyncOperation`1<Windows.Devices.Enumeration.DevicePairingResult>.
// IID: 1002db74-8948-591e-815d-e40b667599a3
// Requires: Windows.Foundation.IAsyncInfo.
type IAsyncOperationOfDevicePairingResult struct {
	syswinrt.IInspectable
}

// IID_IAsyncOperationOfDevicePairingResult is the interface identifier for IAsyncOperationOfDevicePairingResult.
var IID_IAsyncOperationOfDevicePairingResult = win32.GUID{Data1: 0x1002db74, Data2: 0x8948, Data3: 0x591e, Data4: [8]byte{0x81, 0x5d, 0xe4, 0x0b, 0x66, 0x75, 0x99, 0xa3}}

// SetCompleted (propput put_Completed) dispatches through IAsyncOperationOfDevicePairingResult's vtable slot 6.
// A nil handler passes NULL at the ABI (WinRT accepts it where a handler may be cleared).
func (self *IAsyncOperationOfDevicePairingResult) SetCompleted(handler *AsyncOperationCompletedHandlerOfDevicePairingResult) error {
	_handler := uintptr(0)
	if handler != nil {
		_handler = handler.Ptr()
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), _handler)
	return win32.ErrIfFailed(int32(r1))
}

// slot 7: get_Completed skipped: parameterized type Windows.Foundation.AsyncOperationCompletedHandler`1

// GetResults dispatches through IAsyncOperationOfDevicePairingResult's vtable slot 8.
func (self *IAsyncOperationOfDevicePairingResult) GetResults() (*IDevicePairingResult, error) {
	result := new(*IDevicePairingResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Await registers a Completed handler and blocks until IAsyncOperationOfDevicePairingResult reaches
// a terminal state, then returns GetResults() — or, when the status is not
// Completed, an error carrying the status and the IAsyncInfo error code (see
// winrt.AsyncError). Safe on an operation that already completed: WinRT
// invokes a handler assigned after completion immediately. put_Completed
// accepts a single assignment per operation, so Await (or SetCompleted) can
// be used at most once per instance. Await blocks indefinitely by design; a
// context-aware variant is future work. The completion signal is sent from
// the handler's Invoke, which the delegate runtime runs on a fresh goroutine
// — it never contends with the runtime's callback worker, so a completed
// operation cannot deadlock Await.
func (self *IAsyncOperationOfDevicePairingResult) Await() (*IDevicePairingResult, error) {
	completion := make(chan foundation.AsyncStatus, 1)
	handler, err := NewAsyncOperationCompletedHandlerOfDevicePairingResult(func(_ *IAsyncOperationOfDevicePairingResult, asyncStatus foundation.AsyncStatus) {
		completion <- asyncStatus
	})
	if err != nil {
		return nil, err
	}
	defer handler.Close()
	if err := self.SetCompleted(handler); err != nil {
		return nil, err
	}
	status := <-completion
	if status != foundation.AsyncStatusCompleted {
		info, err := winrt.QueryInterface[foundation.IAsyncInfo](unsafe.Pointer(self), &foundation.IID_IAsyncInfo)
		if err != nil {
			return nil, err
		}
		defer info.Release()
		code, err := info.ErrorCode()
		if err != nil {
			return nil, err
		}
		return nil, winrt.AsyncError(int32(status), code)
	}
	return self.GetResults()
}

// IAsyncOperationOfDeviceThumbnail is the WinRT interface Windows.Foundation.IAsyncOperation`1<Windows.Devices.Enumeration.DeviceThumbnail>.
// IID: bac083a3-3a19-5072-9d90-133323a049ba
// Requires: Windows.Foundation.IAsyncInfo.
type IAsyncOperationOfDeviceThumbnail struct {
	syswinrt.IInspectable
}

// IID_IAsyncOperationOfDeviceThumbnail is the interface identifier for IAsyncOperationOfDeviceThumbnail.
var IID_IAsyncOperationOfDeviceThumbnail = win32.GUID{Data1: 0xbac083a3, Data2: 0x3a19, Data3: 0x5072, Data4: [8]byte{0x9d, 0x90, 0x13, 0x33, 0x23, 0xa0, 0x49, 0xba}}

// SetCompleted (propput put_Completed) dispatches through IAsyncOperationOfDeviceThumbnail's vtable slot 6.
// A nil handler passes NULL at the ABI (WinRT accepts it where a handler may be cleared).
func (self *IAsyncOperationOfDeviceThumbnail) SetCompleted(handler *AsyncOperationCompletedHandlerOfDeviceThumbnail) error {
	_handler := uintptr(0)
	if handler != nil {
		_handler = handler.Ptr()
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), _handler)
	return win32.ErrIfFailed(int32(r1))
}

// slot 7: get_Completed skipped: parameterized type Windows.Foundation.AsyncOperationCompletedHandler`1

// GetResults dispatches through IAsyncOperationOfDeviceThumbnail's vtable slot 8.
func (self *IAsyncOperationOfDeviceThumbnail) GetResults() (*storagestreams.IRandomAccessStreamWithContentType, error) {
	result := new(*storagestreams.IRandomAccessStreamWithContentType)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Await registers a Completed handler and blocks until IAsyncOperationOfDeviceThumbnail reaches
// a terminal state, then returns GetResults() — or, when the status is not
// Completed, an error carrying the status and the IAsyncInfo error code (see
// winrt.AsyncError). Safe on an operation that already completed: WinRT
// invokes a handler assigned after completion immediately. put_Completed
// accepts a single assignment per operation, so Await (or SetCompleted) can
// be used at most once per instance. Await blocks indefinitely by design; a
// context-aware variant is future work. The completion signal is sent from
// the handler's Invoke, which the delegate runtime runs on a fresh goroutine
// — it never contends with the runtime's callback worker, so a completed
// operation cannot deadlock Await.
func (self *IAsyncOperationOfDeviceThumbnail) Await() (*storagestreams.IRandomAccessStreamWithContentType, error) {
	completion := make(chan foundation.AsyncStatus, 1)
	handler, err := NewAsyncOperationCompletedHandlerOfDeviceThumbnail(func(_ *IAsyncOperationOfDeviceThumbnail, asyncStatus foundation.AsyncStatus) {
		completion <- asyncStatus
	})
	if err != nil {
		return nil, err
	}
	defer handler.Close()
	if err := self.SetCompleted(handler); err != nil {
		return nil, err
	}
	status := <-completion
	if status != foundation.AsyncStatusCompleted {
		info, err := winrt.QueryInterface[foundation.IAsyncInfo](unsafe.Pointer(self), &foundation.IID_IAsyncInfo)
		if err != nil {
			return nil, err
		}
		defer info.Release()
		code, err := info.ErrorCode()
		if err != nil {
			return nil, err
		}
		return nil, winrt.AsyncError(int32(status), code)
	}
	return self.GetResults()
}

// IAsyncOperationOfDeviceUnpairingResult is the WinRT interface Windows.Foundation.IAsyncOperation`1<Windows.Devices.Enumeration.DeviceUnpairingResult>.
// IID: 2bb4df3d-bd7e-5fe0-9020-56dc0d30b935
// Requires: Windows.Foundation.IAsyncInfo.
type IAsyncOperationOfDeviceUnpairingResult struct {
	syswinrt.IInspectable
}

// IID_IAsyncOperationOfDeviceUnpairingResult is the interface identifier for IAsyncOperationOfDeviceUnpairingResult.
var IID_IAsyncOperationOfDeviceUnpairingResult = win32.GUID{Data1: 0x2bb4df3d, Data2: 0xbd7e, Data3: 0x5fe0, Data4: [8]byte{0x90, 0x20, 0x56, 0xdc, 0x0d, 0x30, 0xb9, 0x35}}

// SetCompleted (propput put_Completed) dispatches through IAsyncOperationOfDeviceUnpairingResult's vtable slot 6.
// A nil handler passes NULL at the ABI (WinRT accepts it where a handler may be cleared).
func (self *IAsyncOperationOfDeviceUnpairingResult) SetCompleted(handler *AsyncOperationCompletedHandlerOfDeviceUnpairingResult) error {
	_handler := uintptr(0)
	if handler != nil {
		_handler = handler.Ptr()
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), _handler)
	return win32.ErrIfFailed(int32(r1))
}

// slot 7: get_Completed skipped: parameterized type Windows.Foundation.AsyncOperationCompletedHandler`1

// GetResults dispatches through IAsyncOperationOfDeviceUnpairingResult's vtable slot 8.
func (self *IAsyncOperationOfDeviceUnpairingResult) GetResults() (*IDeviceUnpairingResult, error) {
	result := new(*IDeviceUnpairingResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Await registers a Completed handler and blocks until IAsyncOperationOfDeviceUnpairingResult reaches
// a terminal state, then returns GetResults() — or, when the status is not
// Completed, an error carrying the status and the IAsyncInfo error code (see
// winrt.AsyncError). Safe on an operation that already completed: WinRT
// invokes a handler assigned after completion immediately. put_Completed
// accepts a single assignment per operation, so Await (or SetCompleted) can
// be used at most once per instance. Await blocks indefinitely by design; a
// context-aware variant is future work. The completion signal is sent from
// the handler's Invoke, which the delegate runtime runs on a fresh goroutine
// — it never contends with the runtime's callback worker, so a completed
// operation cannot deadlock Await.
func (self *IAsyncOperationOfDeviceUnpairingResult) Await() (*IDeviceUnpairingResult, error) {
	completion := make(chan foundation.AsyncStatus, 1)
	handler, err := NewAsyncOperationCompletedHandlerOfDeviceUnpairingResult(func(_ *IAsyncOperationOfDeviceUnpairingResult, asyncStatus foundation.AsyncStatus) {
		completion <- asyncStatus
	})
	if err != nil {
		return nil, err
	}
	defer handler.Close()
	if err := self.SetCompleted(handler); err != nil {
		return nil, err
	}
	status := <-completion
	if status != foundation.AsyncStatusCompleted {
		info, err := winrt.QueryInterface[foundation.IAsyncInfo](unsafe.Pointer(self), &foundation.IID_IAsyncInfo)
		if err != nil {
			return nil, err
		}
		defer info.Release()
		code, err := info.ErrorCode()
		if err != nil {
			return nil, err
		}
		return nil, winrt.AsyncError(int32(status), code)
	}
	return self.GetResults()
}

// IIterableOfDeviceClass is the WinRT interface Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceClass>.
// IID: 47d4be05-58f1-522e-81c6-975eb4131bb9
type IIterableOfDeviceClass struct {
	syswinrt.IInspectable
}

// IID_IIterableOfDeviceClass is the interface identifier for IIterableOfDeviceClass.
var IID_IIterableOfDeviceClass = win32.GUID{Data1: 0x47d4be05, Data2: 0x58f1, Data3: 0x522e, Data4: [8]byte{0x81, 0xc6, 0x97, 0x5e, 0xb4, 0x13, 0x1b, 0xb9}}

// First dispatches through IIterableOfDeviceClass's vtable slot 6.
func (self *IIterableOfDeviceClass) First() (*IIteratorOfDeviceClass, error) {
	result := new(*IIteratorOfDeviceClass)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// NewIIterableOfDeviceClass creates a Go-implemented Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceClass>
// over items, for passing INTO WinRT methods that consume the collection —
// native code drives it through Go-implemented vtables (see the runtime's
// collection core). The object starts with one caller-owned reference:
// Release it (through the embedded IInspectable) once no native code can
// still hold it.
func NewIIterableOfDeviceClass(items []DeviceClass) *IIterableOfDeviceClass {
	boxed := make([]any, len(items))
	for i, item := range items {
		boxed[i] = uint64(item)
	}
	obj := winrt.NewIterableObject("Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceClass>", winrt.CollectionIIDs{Iterable: IID_IIterableOfDeviceClass, Iterator: IID_IIteratorOfDeviceClass}, winrt.CodecScalar(4), boxed)
	return (*IIterableOfDeviceClass)(unsafe.Pointer(obj))
}

// IIterableOfDeviceInformation is the WinRT interface Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceInformation>.
// IID: dd9f8a5d-ec98-5f4b-a3ea-9c8b5ad53c4b
type IIterableOfDeviceInformation struct {
	syswinrt.IInspectable
}

// IID_IIterableOfDeviceInformation is the interface identifier for IIterableOfDeviceInformation.
var IID_IIterableOfDeviceInformation = win32.GUID{Data1: 0xdd9f8a5d, Data2: 0xec98, Data3: 0x5f4b, Data4: [8]byte{0xa3, 0xea, 0x9c, 0x8b, 0x5a, 0xd5, 0x3c, 0x4b}}

// First dispatches through IIterableOfDeviceInformation's vtable slot 6.
func (self *IIterableOfDeviceInformation) First() (*IIteratorOfDeviceInformation, error) {
	result := new(*IIteratorOfDeviceInformation)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// NewIIterableOfDeviceInformation creates a Go-implemented Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceInformation>
// over items, for passing INTO WinRT methods that consume the collection —
// native code drives it through Go-implemented vtables (see the runtime's
// collection core). The object starts with one caller-owned reference:
// Release it (through the embedded IInspectable) once no native code can
// still hold it.
// Items are BORROWED: the collection AddRefs each element and releases it
// as it is displaced, removed, or when the collection itself is released.
// IndexOf compares COM identity WORDS (no QueryInterface is issued): an
// element matches only the exact interface pointer it was built from.
func NewIIterableOfDeviceInformation(items []*IDeviceInformation) *IIterableOfDeviceInformation {
	boxed := make([]any, len(items))
	for i, item := range items {
		boxed[i] = uintptr(unsafe.Pointer(item))
	}
	obj := winrt.NewIterableObject("Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceInformation>", winrt.CollectionIIDs{Iterable: IID_IIterableOfDeviceInformation, Iterator: IID_IIteratorOfDeviceInformation}, winrt.CodecInterface, boxed)
	return (*IIterableOfDeviceInformation)(unsafe.Pointer(obj))
}

// IIterableOfDeviceWatcherEvent is the WinRT interface Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceWatcherEvent>.
// IID: b48fd051-eafa-523f-a66e-9d4151c5d522
type IIterableOfDeviceWatcherEvent struct {
	syswinrt.IInspectable
}

// IID_IIterableOfDeviceWatcherEvent is the interface identifier for IIterableOfDeviceWatcherEvent.
var IID_IIterableOfDeviceWatcherEvent = win32.GUID{Data1: 0xb48fd051, Data2: 0xeafa, Data3: 0x523f, Data4: [8]byte{0xa6, 0x6e, 0x9d, 0x41, 0x51, 0xc5, 0xd5, 0x22}}

// First dispatches through IIterableOfDeviceWatcherEvent's vtable slot 6.
func (self *IIterableOfDeviceWatcherEvent) First() (*IIteratorOfDeviceWatcherEvent, error) {
	result := new(*IIteratorOfDeviceWatcherEvent)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// NewIIterableOfDeviceWatcherEvent creates a Go-implemented Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceWatcherEvent>
// over items, for passing INTO WinRT methods that consume the collection —
// native code drives it through Go-implemented vtables (see the runtime's
// collection core). The object starts with one caller-owned reference:
// Release it (through the embedded IInspectable) once no native code can
// still hold it.
// Items are BORROWED: the collection AddRefs each element and releases it
// as it is displaced, removed, or when the collection itself is released.
// IndexOf compares COM identity WORDS (no QueryInterface is issued): an
// element matches only the exact interface pointer it was built from.
func NewIIterableOfDeviceWatcherEvent(items []*IDeviceWatcherEvent) *IIterableOfDeviceWatcherEvent {
	boxed := make([]any, len(items))
	for i, item := range items {
		boxed[i] = uintptr(unsafe.Pointer(item))
	}
	obj := winrt.NewIterableObject("Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceWatcherEvent>", winrt.CollectionIIDs{Iterable: IID_IIterableOfDeviceWatcherEvent, Iterator: IID_IIteratorOfDeviceWatcherEvent}, winrt.CodecInterface, boxed)
	return (*IIterableOfDeviceWatcherEvent)(unsafe.Pointer(obj))
}

// IIterableOfString is the WinRT interface Windows.Foundation.Collections.IIterable`1<String>.
// IID: e2fcc7c1-3bfc-5a0b-b2b0-72e769d1cb7e
type IIterableOfString struct {
	syswinrt.IInspectable
}

// IID_IIterableOfString is the interface identifier for IIterableOfString.
var IID_IIterableOfString = win32.GUID{Data1: 0xe2fcc7c1, Data2: 0x3bfc, Data3: 0x5a0b, Data4: [8]byte{0xb2, 0xb0, 0x72, 0xe7, 0x69, 0xd1, 0xcb, 0x7e}}

// First dispatches through IIterableOfString's vtable slot 6.
func (self *IIterableOfString) First() (*IIteratorOfString, error) {
	result := new(*IIteratorOfString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// NewIIterableOfString creates a Go-implemented Windows.Foundation.Collections.IIterable`1<String>
// over items, for passing INTO WinRT methods that consume the collection —
// native code drives it through Go-implemented vtables (see the runtime's
// collection core). The object starts with one caller-owned reference:
// Release it (through the embedded IInspectable) once no native code can
// still hold it.
// Items are copied; IndexOf compares string values.
func NewIIterableOfString(items []string) *IIterableOfString {
	boxed := make([]any, len(items))
	for i, item := range items {
		boxed[i] = item
	}
	obj := winrt.NewIterableObject("Windows.Foundation.Collections.IIterable`1<String>", winrt.CollectionIIDs{Iterable: IID_IIterableOfString, Iterator: IID_IIteratorOfString}, winrt.CodecString, boxed)
	return (*IIterableOfString)(unsafe.Pointer(obj))
}

// IIteratorOfDeviceClass is the WinRT interface Windows.Foundation.Collections.IIterator`1<Windows.Devices.Enumeration.DeviceClass>.
// IID: c3807283-1416-593c-955c-0b4a286ff7bb
type IIteratorOfDeviceClass struct {
	syswinrt.IInspectable
}

// IID_IIteratorOfDeviceClass is the interface identifier for IIteratorOfDeviceClass.
var IID_IIteratorOfDeviceClass = win32.GUID{Data1: 0xc3807283, Data2: 0x1416, Data3: 0x593c, Data4: [8]byte{0x95, 0x5c, 0x0b, 0x4a, 0x28, 0x6f, 0xf7, 0xbb}}

// Current (propget get_Current) dispatches through IIteratorOfDeviceClass's vtable slot 6.
func (self *IIteratorOfDeviceClass) Current() (DeviceClass, error) {
	result := new(DeviceClass)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// HasCurrent (propget get_HasCurrent) dispatches through IIteratorOfDeviceClass's vtable slot 7.
func (self *IIteratorOfDeviceClass) HasCurrent() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// MoveNext dispatches through IIteratorOfDeviceClass's vtable slot 8.
func (self *IIteratorOfDeviceClass) MoveNext() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// IIteratorOfDeviceInformation is the WinRT interface Windows.Foundation.Collections.IIterator`1<Windows.Devices.Enumeration.DeviceInformation>.
// IID: 6f85d843-e8ab-5b46-85d7-327c58d18712
type IIteratorOfDeviceInformation struct {
	syswinrt.IInspectable
}

// IID_IIteratorOfDeviceInformation is the interface identifier for IIteratorOfDeviceInformation.
var IID_IIteratorOfDeviceInformation = win32.GUID{Data1: 0x6f85d843, Data2: 0xe8ab, Data3: 0x5b46, Data4: [8]byte{0x85, 0xd7, 0x32, 0x7c, 0x58, 0xd1, 0x87, 0x12}}

// Current (propget get_Current) dispatches through IIteratorOfDeviceInformation's vtable slot 6.
func (self *IIteratorOfDeviceInformation) Current() (*IDeviceInformation, error) {
	result := new(*IDeviceInformation)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// HasCurrent (propget get_HasCurrent) dispatches through IIteratorOfDeviceInformation's vtable slot 7.
func (self *IIteratorOfDeviceInformation) HasCurrent() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// MoveNext dispatches through IIteratorOfDeviceInformation's vtable slot 8.
func (self *IIteratorOfDeviceInformation) MoveNext() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// IIteratorOfDeviceWatcherEvent is the WinRT interface Windows.Foundation.Collections.IIterator`1<Windows.Devices.Enumeration.DeviceWatcherEvent>.
// IID: 74f7d6cc-9c20-5bb9-bace-b2ffa38687f9
type IIteratorOfDeviceWatcherEvent struct {
	syswinrt.IInspectable
}

// IID_IIteratorOfDeviceWatcherEvent is the interface identifier for IIteratorOfDeviceWatcherEvent.
var IID_IIteratorOfDeviceWatcherEvent = win32.GUID{Data1: 0x74f7d6cc, Data2: 0x9c20, Data3: 0x5bb9, Data4: [8]byte{0xba, 0xce, 0xb2, 0xff, 0xa3, 0x86, 0x87, 0xf9}}

// Current (propget get_Current) dispatches through IIteratorOfDeviceWatcherEvent's vtable slot 6.
func (self *IIteratorOfDeviceWatcherEvent) Current() (*IDeviceWatcherEvent, error) {
	result := new(*IDeviceWatcherEvent)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// HasCurrent (propget get_HasCurrent) dispatches through IIteratorOfDeviceWatcherEvent's vtable slot 7.
func (self *IIteratorOfDeviceWatcherEvent) HasCurrent() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// MoveNext dispatches through IIteratorOfDeviceWatcherEvent's vtable slot 8.
func (self *IIteratorOfDeviceWatcherEvent) MoveNext() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// IIteratorOfString is the WinRT interface Windows.Foundation.Collections.IIterator`1<String>.
// IID: 8c304ebb-6615-50a4-8829-879ecd443236
type IIteratorOfString struct {
	syswinrt.IInspectable
}

// IID_IIteratorOfString is the interface identifier for IIteratorOfString.
var IID_IIteratorOfString = win32.GUID{Data1: 0x8c304ebb, Data2: 0x6615, Data3: 0x50a4, Data4: [8]byte{0x88, 0x29, 0x87, 0x9e, 0xcd, 0x44, 0x32, 0x36}}

// Current (propget get_Current) dispatches through IIteratorOfString's vtable slot 6.
func (self *IIteratorOfString) Current() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// HasCurrent (propget get_HasCurrent) dispatches through IIteratorOfString's vtable slot 7.
func (self *IIteratorOfString) HasCurrent() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// MoveNext dispatches through IIteratorOfString's vtable slot 8.
func (self *IIteratorOfString) MoveNext() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// IMapViewOfStringAndObject is the WinRT interface Windows.Foundation.Collections.IMapView`2<String, Object>.
// IID: bb78502a-f79d-54fa-92c9-90c5039fdf7e
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Foundation.Collections.IKeyValuePair`2<String, Object>>.
type IMapViewOfStringAndObject struct {
	syswinrt.IInspectable
}

// IID_IMapViewOfStringAndObject is the interface identifier for IMapViewOfStringAndObject.
var IID_IMapViewOfStringAndObject = win32.GUID{Data1: 0xbb78502a, Data2: 0xf79d, Data3: 0x54fa, Data4: [8]byte{0x92, 0xc9, 0x90, 0xc5, 0x03, 0x9f, 0xdf, 0x7e}}

// Lookup dispatches through IMapViewOfStringAndObject's vtable slot 6.
func (self *IMapViewOfStringAndObject) Lookup(key string) (*syswinrt.IInspectable, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return nil, err
	}
	defer hKey.Close()
	result := new(*syswinrt.IInspectable)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IMapViewOfStringAndObject's vtable slot 7.
func (self *IMapViewOfStringAndObject) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// HasKey dispatches through IMapViewOfStringAndObject's vtable slot 8.
func (self *IMapViewOfStringAndObject) HasKey(key string) (bool, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return false, err
	}
	defer hKey.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// Split dispatches through IMapViewOfStringAndObject's vtable slot 9.
func (self *IMapViewOfStringAndObject) Split(first **IMapViewOfStringAndObject, second **IMapViewOfStringAndObject) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(first))), uintptr(winrt.OutParam(unsafe.Pointer(second))))
	return win32.ErrIfFailed(int32(r1))
}

// IVectorOfDeviceClass is the WinRT interface Windows.Foundation.Collections.IVector`1<Windows.Devices.Enumeration.DeviceClass>.
// IID: ee662d37-b0eb-5729-9832-156fd2889d48
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceClass>.
type IVectorOfDeviceClass struct {
	syswinrt.IInspectable
}

// IID_IVectorOfDeviceClass is the interface identifier for IVectorOfDeviceClass.
var IID_IVectorOfDeviceClass = win32.GUID{Data1: 0xee662d37, Data2: 0xb0eb, Data3: 0x5729, Data4: [8]byte{0x98, 0x32, 0x15, 0x6f, 0xd2, 0x88, 0x9d, 0x48}}

// GetAt dispatches through IVectorOfDeviceClass's vtable slot 6.
func (self *IVectorOfDeviceClass) GetAt(index uint32) (DeviceClass, error) {
	result := new(DeviceClass)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorOfDeviceClass's vtable slot 7.
func (self *IVectorOfDeviceClass) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IVectorOfDeviceClass's vtable slot 8.
func (self *IVectorOfDeviceClass) GetView() (*IVectorViewOfDeviceClass, error) {
	result := new(*IVectorViewOfDeviceClass)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorOfDeviceClass's vtable slot 9.
func (self *IVectorOfDeviceClass) IndexOf(value DeviceClass, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(value), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetAt dispatches through IVectorOfDeviceClass's vtable slot 10.
func (self *IVectorOfDeviceClass) SetAt(index uint32, value DeviceClass) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(value))
	return win32.ErrIfFailed(int32(r1))
}

// InsertAt dispatches through IVectorOfDeviceClass's vtable slot 11.
func (self *IVectorOfDeviceClass) InsertAt(index uint32, value DeviceClass) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(value))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAt dispatches through IVectorOfDeviceClass's vtable slot 12.
func (self *IVectorOfDeviceClass) RemoveAt(index uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(index))
	return win32.ErrIfFailed(int32(r1))
}

// Append dispatches through IVectorOfDeviceClass's vtable slot 13.
func (self *IVectorOfDeviceClass) Append(value DeviceClass) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(value))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAtEnd dispatches through IVectorOfDeviceClass's vtable slot 14.
func (self *IVectorOfDeviceClass) RemoveAtEnd() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IVectorOfDeviceClass's vtable slot 15.
func (self *IVectorOfDeviceClass) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// slot 16: GetMany skipped: conformant array

// slot 17: ReplaceAll skipped: conformant array

// NewIVectorOfDeviceClass creates a Go-implemented Windows.Foundation.Collections.IVector`1<Windows.Devices.Enumeration.DeviceClass>
// over items, for passing INTO WinRT methods that consume the collection —
// native code drives it through Go-implemented vtables (see the runtime's
// collection core). The object starts with one caller-owned reference:
// Release it (through the embedded IInspectable) once no native code can
// still hold it.
// The vector is writable through the WinRT ABI (the Go side exposes no
// mutation API); GetView returns an immutable SNAPSHOT of the contents at
// call time.
func NewIVectorOfDeviceClass(items []DeviceClass) *IVectorOfDeviceClass {
	boxed := make([]any, len(items))
	for i, item := range items {
		boxed[i] = uint64(item)
	}
	obj := winrt.NewVectorObject("Windows.Foundation.Collections.IVector`1<Windows.Devices.Enumeration.DeviceClass>", winrt.CollectionIIDs{Iterable: IID_IIterableOfDeviceClass, Iterator: IID_IIteratorOfDeviceClass, VectorView: IID_IVectorViewOfDeviceClass, Vector: IID_IVectorOfDeviceClass}, winrt.CodecScalar(4), boxed)
	return (*IVectorOfDeviceClass)(unsafe.Pointer(obj))
}

// IVectorOfString is the WinRT interface Windows.Foundation.Collections.IVector`1<String>.
// IID: 98b9acc1-4b56-532e-ac73-03d5291cca90
// Requires: Windows.Foundation.Collections.IIterable`1<String>.
type IVectorOfString struct {
	syswinrt.IInspectable
}

// IID_IVectorOfString is the interface identifier for IVectorOfString.
var IID_IVectorOfString = win32.GUID{Data1: 0x98b9acc1, Data2: 0x4b56, Data3: 0x532e, Data4: [8]byte{0xac, 0x73, 0x03, 0xd5, 0x29, 0x1c, 0xca, 0x90}}

// GetAt dispatches through IVectorOfString's vtable slot 6.
func (self *IVectorOfString) GetAt(index uint32) (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Size (propget get_Size) dispatches through IVectorOfString's vtable slot 7.
func (self *IVectorOfString) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IVectorOfString's vtable slot 8.
func (self *IVectorOfString) GetView() (*IVectorViewOfString, error) {
	result := new(*IVectorViewOfString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorOfString's vtable slot 9.
func (self *IVectorOfString) IndexOf(value string, index *uint32) (bool, error) {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return false, err
	}
	defer hValue.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetAt dispatches through IVectorOfString's vtable slot 10.
func (self *IVectorOfString) SetAt(index uint32, value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// InsertAt dispatches through IVectorOfString's vtable slot 11.
func (self *IVectorOfString) InsertAt(index uint32, value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAt dispatches through IVectorOfString's vtable slot 12.
func (self *IVectorOfString) RemoveAt(index uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(index))
	return win32.ErrIfFailed(int32(r1))
}

// Append dispatches through IVectorOfString's vtable slot 13.
func (self *IVectorOfString) Append(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAtEnd dispatches through IVectorOfString's vtable slot 14.
func (self *IVectorOfString) RemoveAtEnd() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IVectorOfString's vtable slot 15.
func (self *IVectorOfString) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// slot 16: GetMany skipped: conformant array

// slot 17: ReplaceAll skipped: conformant array

// NewIVectorOfString creates a Go-implemented Windows.Foundation.Collections.IVector`1<String>
// over items, for passing INTO WinRT methods that consume the collection —
// native code drives it through Go-implemented vtables (see the runtime's
// collection core). The object starts with one caller-owned reference:
// Release it (through the embedded IInspectable) once no native code can
// still hold it.
// Items are copied; IndexOf compares string values.
// The vector is writable through the WinRT ABI (the Go side exposes no
// mutation API); GetView returns an immutable SNAPSHOT of the contents at
// call time.
func NewIVectorOfString(items []string) *IVectorOfString {
	boxed := make([]any, len(items))
	for i, item := range items {
		boxed[i] = item
	}
	obj := winrt.NewVectorObject("Windows.Foundation.Collections.IVector`1<String>", winrt.CollectionIIDs{Iterable: IID_IIterableOfString, Iterator: IID_IIteratorOfString, VectorView: IID_IVectorViewOfString, Vector: IID_IVectorOfString}, winrt.CodecString, boxed)
	return (*IVectorOfString)(unsafe.Pointer(obj))
}

// IVectorViewOfDeviceClass is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Enumeration.DeviceClass>.
// IID: 01a80a97-bd87-5c8a-97fd-d449c98bdac6
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceClass>.
type IVectorViewOfDeviceClass struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfDeviceClass is the interface identifier for IVectorViewOfDeviceClass.
var IID_IVectorViewOfDeviceClass = win32.GUID{Data1: 0x01a80a97, Data2: 0xbd87, Data3: 0x5c8a, Data4: [8]byte{0x97, 0xfd, 0xd4, 0x49, 0xc9, 0x8b, 0xda, 0xc6}}

// GetAt dispatches through IVectorViewOfDeviceClass's vtable slot 6.
func (self *IVectorViewOfDeviceClass) GetAt(index uint32) (DeviceClass, error) {
	result := new(DeviceClass)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfDeviceClass's vtable slot 7.
func (self *IVectorViewOfDeviceClass) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfDeviceClass's vtable slot 8.
func (self *IVectorViewOfDeviceClass) IndexOf(value DeviceClass, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(value), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// NewIVectorViewOfDeviceClass creates a Go-implemented Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Enumeration.DeviceClass>
// over items, for passing INTO WinRT methods that consume the collection —
// native code drives it through Go-implemented vtables (see the runtime's
// collection core). The object starts with one caller-owned reference:
// Release it (through the embedded IInspectable) once no native code can
// still hold it.
func NewIVectorViewOfDeviceClass(items []DeviceClass) *IVectorViewOfDeviceClass {
	boxed := make([]any, len(items))
	for i, item := range items {
		boxed[i] = uint64(item)
	}
	obj := winrt.NewVectorViewObject("Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Enumeration.DeviceClass>", winrt.CollectionIIDs{Iterable: IID_IIterableOfDeviceClass, Iterator: IID_IIteratorOfDeviceClass, VectorView: IID_IVectorViewOfDeviceClass}, winrt.CodecScalar(4), boxed)
	return (*IVectorViewOfDeviceClass)(unsafe.Pointer(obj))
}

// IVectorViewOfDeviceInformation is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Enumeration.DeviceInformation>.
// IID: e170688f-3495-5bf6-aab5-9cac17e0f10f
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceInformation>.
type IVectorViewOfDeviceInformation struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfDeviceInformation is the interface identifier for IVectorViewOfDeviceInformation.
var IID_IVectorViewOfDeviceInformation = win32.GUID{Data1: 0xe170688f, Data2: 0x3495, Data3: 0x5bf6, Data4: [8]byte{0xaa, 0xb5, 0x9c, 0xac, 0x17, 0xe0, 0xf1, 0x0f}}

// GetAt dispatches through IVectorViewOfDeviceInformation's vtable slot 6.
func (self *IVectorViewOfDeviceInformation) GetAt(index uint32) (*IDeviceInformation, error) {
	result := new(*IDeviceInformation)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfDeviceInformation's vtable slot 7.
func (self *IVectorViewOfDeviceInformation) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfDeviceInformation's vtable slot 8.
func (self *IVectorViewOfDeviceInformation) IndexOf(value *IDeviceInformation, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// NewIVectorViewOfDeviceInformation creates a Go-implemented Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Enumeration.DeviceInformation>
// over items, for passing INTO WinRT methods that consume the collection —
// native code drives it through Go-implemented vtables (see the runtime's
// collection core). The object starts with one caller-owned reference:
// Release it (through the embedded IInspectable) once no native code can
// still hold it.
// Items are BORROWED: the collection AddRefs each element and releases it
// as it is displaced, removed, or when the collection itself is released.
// IndexOf compares COM identity WORDS (no QueryInterface is issued): an
// element matches only the exact interface pointer it was built from.
func NewIVectorViewOfDeviceInformation(items []*IDeviceInformation) *IVectorViewOfDeviceInformation {
	boxed := make([]any, len(items))
	for i, item := range items {
		boxed[i] = uintptr(unsafe.Pointer(item))
	}
	obj := winrt.NewVectorViewObject("Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Enumeration.DeviceInformation>", winrt.CollectionIIDs{Iterable: IID_IIterableOfDeviceInformation, Iterator: IID_IIteratorOfDeviceInformation, VectorView: IID_IVectorViewOfDeviceInformation}, winrt.CodecInterface, boxed)
	return (*IVectorViewOfDeviceInformation)(unsafe.Pointer(obj))
}

// IVectorViewOfDeviceWatcherEvent is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Enumeration.DeviceWatcherEvent>.
// IID: 8f994d37-8fab-51c6-a1e0-c93f68a20ef0
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Devices.Enumeration.DeviceWatcherEvent>.
type IVectorViewOfDeviceWatcherEvent struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfDeviceWatcherEvent is the interface identifier for IVectorViewOfDeviceWatcherEvent.
var IID_IVectorViewOfDeviceWatcherEvent = win32.GUID{Data1: 0x8f994d37, Data2: 0x8fab, Data3: 0x51c6, Data4: [8]byte{0xa1, 0xe0, 0xc9, 0x3f, 0x68, 0xa2, 0x0e, 0xf0}}

// GetAt dispatches through IVectorViewOfDeviceWatcherEvent's vtable slot 6.
func (self *IVectorViewOfDeviceWatcherEvent) GetAt(index uint32) (*IDeviceWatcherEvent, error) {
	result := new(*IDeviceWatcherEvent)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfDeviceWatcherEvent's vtable slot 7.
func (self *IVectorViewOfDeviceWatcherEvent) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfDeviceWatcherEvent's vtable slot 8.
func (self *IVectorViewOfDeviceWatcherEvent) IndexOf(value *IDeviceWatcherEvent, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// NewIVectorViewOfDeviceWatcherEvent creates a Go-implemented Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Enumeration.DeviceWatcherEvent>
// over items, for passing INTO WinRT methods that consume the collection —
// native code drives it through Go-implemented vtables (see the runtime's
// collection core). The object starts with one caller-owned reference:
// Release it (through the embedded IInspectable) once no native code can
// still hold it.
// Items are BORROWED: the collection AddRefs each element and releases it
// as it is displaced, removed, or when the collection itself is released.
// IndexOf compares COM identity WORDS (no QueryInterface is issued): an
// element matches only the exact interface pointer it was built from.
func NewIVectorViewOfDeviceWatcherEvent(items []*IDeviceWatcherEvent) *IVectorViewOfDeviceWatcherEvent {
	boxed := make([]any, len(items))
	for i, item := range items {
		boxed[i] = uintptr(unsafe.Pointer(item))
	}
	obj := winrt.NewVectorViewObject("Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Enumeration.DeviceWatcherEvent>", winrt.CollectionIIDs{Iterable: IID_IIterableOfDeviceWatcherEvent, Iterator: IID_IIteratorOfDeviceWatcherEvent, VectorView: IID_IVectorViewOfDeviceWatcherEvent}, winrt.CodecInterface, boxed)
	return (*IVectorViewOfDeviceWatcherEvent)(unsafe.Pointer(obj))
}

// IVectorViewOfString is the WinRT interface Windows.Foundation.Collections.IVectorView`1<String>.
// IID: 2f13c006-a03a-5f69-b090-75a43e33423e
// Requires: Windows.Foundation.Collections.IIterable`1<String>.
type IVectorViewOfString struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfString is the interface identifier for IVectorViewOfString.
var IID_IVectorViewOfString = win32.GUID{Data1: 0x2f13c006, Data2: 0xa03a, Data3: 0x5f69, Data4: [8]byte{0xb0, 0x90, 0x75, 0xa4, 0x3e, 0x33, 0x42, 0x3e}}

// GetAt dispatches through IVectorViewOfString's vtable slot 6.
func (self *IVectorViewOfString) GetAt(index uint32) (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Size (propget get_Size) dispatches through IVectorViewOfString's vtable slot 7.
func (self *IVectorViewOfString) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfString's vtable slot 8.
func (self *IVectorViewOfString) IndexOf(value string, index *uint32) (bool, error) {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return false, err
	}
	defer hValue.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// NewIVectorViewOfString creates a Go-implemented Windows.Foundation.Collections.IVectorView`1<String>
// over items, for passing INTO WinRT methods that consume the collection —
// native code drives it through Go-implemented vtables (see the runtime's
// collection core). The object starts with one caller-owned reference:
// Release it (through the embedded IInspectable) once no native code can
// still hold it.
// Items are copied; IndexOf compares string values.
func NewIVectorViewOfString(items []string) *IVectorViewOfString {
	boxed := make([]any, len(items))
	for i, item := range items {
		boxed[i] = item
	}
	obj := winrt.NewVectorViewObject("Windows.Foundation.Collections.IVectorView`1<String>", winrt.CollectionIIDs{Iterable: IID_IIterableOfString, Iterator: IID_IIteratorOfString, VectorView: IID_IVectorViewOfString}, winrt.CodecString, boxed)
	return (*IVectorViewOfString)(unsafe.Pointer(obj))
}
