// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package display

import (
	"fmt"
)

// AdvancedColorKind is Windows.Graphics.Display.AdvancedColorKind.
type AdvancedColorKind int32

const (
	AdvancedColorKindStandardDynamicRange AdvancedColorKind = 0
	AdvancedColorKindWideColorGamut       AdvancedColorKind = 1
	AdvancedColorKindHighDynamicRange     AdvancedColorKind = 2
)

// String returns the AdvancedColorKind constant's name, or its numeric form when
// the value is not a known constant.
func (e AdvancedColorKind) String() string {
	switch e {
	case AdvancedColorKindStandardDynamicRange:
		return "AdvancedColorKindStandardDynamicRange"
	case AdvancedColorKindWideColorGamut:
		return "AdvancedColorKindWideColorGamut"
	case AdvancedColorKindHighDynamicRange:
		return "AdvancedColorKindHighDynamicRange"
	default:
		return fmt.Sprintf("AdvancedColorKind(%d)", int32(e))
	}
}

// DisplayBrightnessOverrideOptions is Windows.Graphics.Display.DisplayBrightnessOverrideOptions.
// Bitmask — values may be combined with |.
type DisplayBrightnessOverrideOptions uint32

const (
	DisplayBrightnessOverrideOptionsNone                            DisplayBrightnessOverrideOptions = 0
	DisplayBrightnessOverrideOptionsUseDimmedPolicyWhenBatteryIsLow DisplayBrightnessOverrideOptions = 1
)

// String returns the DisplayBrightnessOverrideOptions constant's name, or its numeric form when
// the value is not a known constant.
func (e DisplayBrightnessOverrideOptions) String() string {
	switch e {
	case DisplayBrightnessOverrideOptionsNone:
		return "DisplayBrightnessOverrideOptionsNone"
	case DisplayBrightnessOverrideOptionsUseDimmedPolicyWhenBatteryIsLow:
		return "DisplayBrightnessOverrideOptionsUseDimmedPolicyWhenBatteryIsLow"
	default:
		return fmt.Sprintf("DisplayBrightnessOverrideOptions(%d)", uint32(e))
	}
}

// DisplayBrightnessOverrideScenario is Windows.Graphics.Display.DisplayBrightnessOverrideScenario.
type DisplayBrightnessOverrideScenario int32

const (
	DisplayBrightnessOverrideScenarioIdleBrightness           DisplayBrightnessOverrideScenario = 0
	DisplayBrightnessOverrideScenarioBarcodeReadingBrightness DisplayBrightnessOverrideScenario = 1
	DisplayBrightnessOverrideScenarioFullBrightness           DisplayBrightnessOverrideScenario = 2
)

// String returns the DisplayBrightnessOverrideScenario constant's name, or its numeric form when
// the value is not a known constant.
func (e DisplayBrightnessOverrideScenario) String() string {
	switch e {
	case DisplayBrightnessOverrideScenarioIdleBrightness:
		return "DisplayBrightnessOverrideScenarioIdleBrightness"
	case DisplayBrightnessOverrideScenarioBarcodeReadingBrightness:
		return "DisplayBrightnessOverrideScenarioBarcodeReadingBrightness"
	case DisplayBrightnessOverrideScenarioFullBrightness:
		return "DisplayBrightnessOverrideScenarioFullBrightness"
	default:
		return fmt.Sprintf("DisplayBrightnessOverrideScenario(%d)", int32(e))
	}
}

// DisplayBrightnessScenario is Windows.Graphics.Display.DisplayBrightnessScenario.
type DisplayBrightnessScenario int32

const (
	DisplayBrightnessScenarioDefaultBrightness        DisplayBrightnessScenario = 0
	DisplayBrightnessScenarioIdleBrightness           DisplayBrightnessScenario = 1
	DisplayBrightnessScenarioBarcodeReadingBrightness DisplayBrightnessScenario = 2
	DisplayBrightnessScenarioFullBrightness           DisplayBrightnessScenario = 3
)

// String returns the DisplayBrightnessScenario constant's name, or its numeric form when
// the value is not a known constant.
func (e DisplayBrightnessScenario) String() string {
	switch e {
	case DisplayBrightnessScenarioDefaultBrightness:
		return "DisplayBrightnessScenarioDefaultBrightness"
	case DisplayBrightnessScenarioIdleBrightness:
		return "DisplayBrightnessScenarioIdleBrightness"
	case DisplayBrightnessScenarioBarcodeReadingBrightness:
		return "DisplayBrightnessScenarioBarcodeReadingBrightness"
	case DisplayBrightnessScenarioFullBrightness:
		return "DisplayBrightnessScenarioFullBrightness"
	default:
		return fmt.Sprintf("DisplayBrightnessScenario(%d)", int32(e))
	}
}

// DisplayColorOverrideScenario is Windows.Graphics.Display.DisplayColorOverrideScenario.
type DisplayColorOverrideScenario int32

const (
	DisplayColorOverrideScenarioAccurate DisplayColorOverrideScenario = 0
)

// String returns the DisplayColorOverrideScenario constant's name, or its numeric form when
// the value is not a known constant.
func (e DisplayColorOverrideScenario) String() string {
	switch e {
	case DisplayColorOverrideScenarioAccurate:
		return "DisplayColorOverrideScenarioAccurate"
	default:
		return fmt.Sprintf("DisplayColorOverrideScenario(%d)", int32(e))
	}
}

// DisplayOrientations is Windows.Graphics.Display.DisplayOrientations.
// Bitmask — values may be combined with |.
type DisplayOrientations uint32

const (
	DisplayOrientationsNone             DisplayOrientations = 0
	DisplayOrientationsLandscape        DisplayOrientations = 1
	DisplayOrientationsPortrait         DisplayOrientations = 2
	DisplayOrientationsLandscapeFlipped DisplayOrientations = 4
	DisplayOrientationsPortraitFlipped  DisplayOrientations = 8
)

// String returns the DisplayOrientations constant's name, or its numeric form when
// the value is not a known constant.
func (e DisplayOrientations) String() string {
	switch e {
	case DisplayOrientationsNone:
		return "DisplayOrientationsNone"
	case DisplayOrientationsLandscape:
		return "DisplayOrientationsLandscape"
	case DisplayOrientationsPortrait:
		return "DisplayOrientationsPortrait"
	case DisplayOrientationsLandscapeFlipped:
		return "DisplayOrientationsLandscapeFlipped"
	case DisplayOrientationsPortraitFlipped:
		return "DisplayOrientationsPortraitFlipped"
	default:
		return fmt.Sprintf("DisplayOrientations(%d)", uint32(e))
	}
}

// HdrMetadataFormat is Windows.Graphics.Display.HdrMetadataFormat.
type HdrMetadataFormat int32

const (
	HdrMetadataFormatHdr10     HdrMetadataFormat = 0
	HdrMetadataFormatHdr10Plus HdrMetadataFormat = 1
)

// String returns the HdrMetadataFormat constant's name, or its numeric form when
// the value is not a known constant.
func (e HdrMetadataFormat) String() string {
	switch e {
	case HdrMetadataFormatHdr10:
		return "HdrMetadataFormatHdr10"
	case HdrMetadataFormatHdr10Plus:
		return "HdrMetadataFormatHdr10Plus"
	default:
		return fmt.Sprintf("HdrMetadataFormat(%d)", int32(e))
	}
}

// ResolutionScale is Windows.Graphics.Display.ResolutionScale.
type ResolutionScale int32

const (
	ResolutionScaleInvalid         ResolutionScale = 0
	ResolutionScaleScale100Percent ResolutionScale = 100
	ResolutionScaleScale120Percent ResolutionScale = 120
	ResolutionScaleScale125Percent ResolutionScale = 125
	ResolutionScaleScale140Percent ResolutionScale = 140
	ResolutionScaleScale150Percent ResolutionScale = 150
	ResolutionScaleScale160Percent ResolutionScale = 160
	ResolutionScaleScale175Percent ResolutionScale = 175
	ResolutionScaleScale180Percent ResolutionScale = 180
	ResolutionScaleScale200Percent ResolutionScale = 200
	ResolutionScaleScale225Percent ResolutionScale = 225
	ResolutionScaleScale250Percent ResolutionScale = 250
	ResolutionScaleScale300Percent ResolutionScale = 300
	ResolutionScaleScale350Percent ResolutionScale = 350
	ResolutionScaleScale400Percent ResolutionScale = 400
	ResolutionScaleScale450Percent ResolutionScale = 450
	ResolutionScaleScale500Percent ResolutionScale = 500
)

// String returns the ResolutionScale constant's name, or its numeric form when
// the value is not a known constant.
func (e ResolutionScale) String() string {
	switch e {
	case ResolutionScaleInvalid:
		return "ResolutionScaleInvalid"
	case ResolutionScaleScale100Percent:
		return "ResolutionScaleScale100Percent"
	case ResolutionScaleScale120Percent:
		return "ResolutionScaleScale120Percent"
	case ResolutionScaleScale125Percent:
		return "ResolutionScaleScale125Percent"
	case ResolutionScaleScale140Percent:
		return "ResolutionScaleScale140Percent"
	case ResolutionScaleScale150Percent:
		return "ResolutionScaleScale150Percent"
	case ResolutionScaleScale160Percent:
		return "ResolutionScaleScale160Percent"
	case ResolutionScaleScale175Percent:
		return "ResolutionScaleScale175Percent"
	case ResolutionScaleScale180Percent:
		return "ResolutionScaleScale180Percent"
	case ResolutionScaleScale200Percent:
		return "ResolutionScaleScale200Percent"
	case ResolutionScaleScale225Percent:
		return "ResolutionScaleScale225Percent"
	case ResolutionScaleScale250Percent:
		return "ResolutionScaleScale250Percent"
	case ResolutionScaleScale300Percent:
		return "ResolutionScaleScale300Percent"
	case ResolutionScaleScale350Percent:
		return "ResolutionScaleScale350Percent"
	case ResolutionScaleScale400Percent:
		return "ResolutionScaleScale400Percent"
	case ResolutionScaleScale450Percent:
		return "ResolutionScaleScale450Percent"
	case ResolutionScaleScale500Percent:
		return "ResolutionScaleScale500Percent"
	default:
		return fmt.Sprintf("ResolutionScale(%d)", int32(e))
	}
}
