// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package diagnostics

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	uicomposition "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/ui/composition"
)

// ICompositionDebugHeatMaps is the WinRT interface Windows.UI.Composition.Diagnostics.ICompositionDebugHeatMaps.
// IID: e49c90ac-2ff3-5805-718c-b725ee07650f
// Exclusive to the Windows.UI.Composition.Diagnostics.CompositionDebugHeatMaps runtime class.
type ICompositionDebugHeatMaps struct {
	syswinrt.IInspectable
}

// IID_ICompositionDebugHeatMaps is the interface identifier for ICompositionDebugHeatMaps.
var IID_ICompositionDebugHeatMaps = win32.GUID{Data1: 0xe49c90ac, Data2: 0x2ff3, Data3: 0x5805, Data4: [8]byte{0x71, 0x8c, 0xb7, 0x25, 0xee, 0x07, 0x65, 0x0f}}

// Hide dispatches through ICompositionDebugHeatMaps's vtable slot 6.
// Parameter subtree's class Windows.UI.Composition.Visual is projected as IInspectable (the class is not emitted this wave).
func (self *ICompositionDebugHeatMaps) Hide(subtree *syswinrt.IInspectable) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(subtree)))
	return win32.ErrIfFailed(int32(r1))
}

// ShowMemoryUsage dispatches through ICompositionDebugHeatMaps's vtable slot 7.
// Parameter subtree's class Windows.UI.Composition.Visual is projected as IInspectable (the class is not emitted this wave).
func (self *ICompositionDebugHeatMaps) ShowMemoryUsage(subtree *syswinrt.IInspectable) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(subtree)))
	return win32.ErrIfFailed(int32(r1))
}

// ShowOverdraw dispatches through ICompositionDebugHeatMaps's vtable slot 8.
// Parameter subtree's class Windows.UI.Composition.Visual is projected as IInspectable (the class is not emitted this wave).
func (self *ICompositionDebugHeatMaps) ShowOverdraw(subtree *syswinrt.IInspectable, contentKinds CompositionDebugOverdrawContentKinds) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(subtree)), uintptr(contentKinds))
	return win32.ErrIfFailed(int32(r1))
}

// ShowRedraw dispatches through ICompositionDebugHeatMaps's vtable slot 9.
// Parameter subtree's class Windows.UI.Composition.Visual is projected as IInspectable (the class is not emitted this wave).
func (self *ICompositionDebugHeatMaps) ShowRedraw(subtree *syswinrt.IInspectable) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(subtree)))
	return win32.ErrIfFailed(int32(r1))
}

// ICompositionDebugSettings is the WinRT interface Windows.UI.Composition.Diagnostics.ICompositionDebugSettings.
// IID: 2831987e-1d82-4d38-b7b7-efd11c7bc3d1
// Exclusive to the Windows.UI.Composition.Diagnostics.CompositionDebugSettings runtime class.
type ICompositionDebugSettings struct {
	syswinrt.IInspectable
}

// IID_ICompositionDebugSettings is the interface identifier for ICompositionDebugSettings.
var IID_ICompositionDebugSettings = win32.GUID{Data1: 0x2831987e, Data2: 0x1d82, Data3: 0x4d38, Data4: [8]byte{0xb7, 0xb7, 0xef, 0xd1, 0x1c, 0x7b, 0xc3, 0xd1}}

// HeatMaps (propget get_HeatMaps) dispatches through ICompositionDebugSettings's vtable slot 6.
func (self *ICompositionDebugSettings) HeatMaps() (*ICompositionDebugHeatMaps, error) {
	result := new(*ICompositionDebugHeatMaps)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ICompositionDebugSettingsStatics is the WinRT interface Windows.UI.Composition.Diagnostics.ICompositionDebugSettingsStatics.
// IID: 64ec1f1e-6af8-4af8-b814-c870fd5a9505
// Exclusive to the Windows.UI.Composition.Diagnostics.CompositionDebugSettings runtime class.
type ICompositionDebugSettingsStatics struct {
	syswinrt.IInspectable
}

// IID_ICompositionDebugSettingsStatics is the interface identifier for ICompositionDebugSettingsStatics.
var IID_ICompositionDebugSettingsStatics = win32.GUID{Data1: 0x64ec1f1e, Data2: 0x6af8, Data3: 0x4af8, Data4: [8]byte{0xb8, 0x14, 0xc8, 0x70, 0xfd, 0x5a, 0x95, 0x05}}

// TryGetSettings dispatches through ICompositionDebugSettingsStatics's vtable slot 6.
func (self *ICompositionDebugSettingsStatics) TryGetSettings(compositor *uicomposition.ICompositor) (*ICompositionDebugSettings, error) {
	result := new(*ICompositionDebugSettings)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(compositor)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
