// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package media

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
	graphicsimaging "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/graphics/imaging"
)

// IAsyncOperationOfBool is the WinRT interface Windows.Foundation.IAsyncOperation`1<Bool>.
// IID: cdb5efb3-5788-509d-9be1-71ccb8a3362a
// Requires: Windows.Foundation.IAsyncInfo.
type IAsyncOperationOfBool struct {
	syswinrt.IInspectable
}

// IID_IAsyncOperationOfBool is the interface identifier for IAsyncOperationOfBool.
var IID_IAsyncOperationOfBool = win32.GUID{Data1: 0xcdb5efb3, Data2: 0x5788, Data3: 0x509d, Data4: [8]byte{0x9b, 0xe1, 0x71, 0xcc, 0xb8, 0xa3, 0x36, 0x2a}}

// SetCompleted (propput put_Completed) dispatches through IAsyncOperationOfBool's vtable slot 6.
// A nil handler passes NULL at the ABI (WinRT accepts it where a handler may be cleared).
func (self *IAsyncOperationOfBool) SetCompleted(handler *AsyncOperationCompletedHandlerOfBool) error {
	_handler := uintptr(0)
	if handler != nil {
		_handler = handler.Ptr()
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), _handler)
	return win32.ErrIfFailed(int32(r1))
}

// slot 7: get_Completed skipped: parameterized type Windows.Foundation.AsyncOperationCompletedHandler`1

// GetResults dispatches through IAsyncOperationOfBool's vtable slot 8.
func (self *IAsyncOperationOfBool) GetResults() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// Await registers a Completed handler and blocks until IAsyncOperationOfBool reaches
// a terminal state, then returns GetResults() — or, when the status is not
// Completed, an error carrying the status and the IAsyncInfo error code (see
// winrt.AsyncError). Safe on an operation that already completed: WinRT
// invokes a handler assigned after completion immediately. put_Completed
// accepts a single assignment per operation, so Await (or SetCompleted) can
// be used at most once per instance. Await blocks indefinitely by design; a
// context-aware variant is future work. The completion signal is sent from
// the handler's Invoke, which the delegate runtime runs on a fresh goroutine
// — it never contends with the runtime's callback worker, so a completed
// operation cannot deadlock Await.
func (self *IAsyncOperationOfBool) Await() (bool, error) {
	completion := make(chan foundation.AsyncStatus, 1)
	handler, err := NewAsyncOperationCompletedHandlerOfBool(func(_ *IAsyncOperationOfBool, asyncStatus foundation.AsyncStatus) {
		completion <- asyncStatus
	})
	if err != nil {
		return false, err
	}
	defer handler.Close()
	if err := self.SetCompleted(handler); err != nil {
		return false, err
	}
	status := <-completion
	if status != foundation.AsyncStatusCompleted {
		info, err := winrt.QueryInterface[foundation.IAsyncInfo](unsafe.Pointer(self), &foundation.IID_IAsyncInfo)
		if err != nil {
			return false, err
		}
		defer info.Release()
		code, err := info.ErrorCode()
		if err != nil {
			return false, err
		}
		return false, winrt.AsyncError(int32(status), code)
	}
	return self.GetResults()
}

// IReferenceOfBitmapBounds is the WinRT interface Windows.Foundation.IReference`1<Windows.Graphics.Imaging.BitmapBounds>.
// IID: aa19da70-dee6-5b42-b562-2fcd218c34ca
// Requires: Windows.Foundation.IPropertyValue.
type IReferenceOfBitmapBounds struct {
	syswinrt.IInspectable
}

// IID_IReferenceOfBitmapBounds is the interface identifier for IReferenceOfBitmapBounds.
var IID_IReferenceOfBitmapBounds = win32.GUID{Data1: 0xaa19da70, Data2: 0xdee6, Data3: 0x5b42, Data4: [8]byte{0xb5, 0x62, 0x2f, 0xcd, 0x21, 0x8c, 0x34, 0xca}}

// Value (propget get_Value) dispatches through IReferenceOfBitmapBounds's vtable slot 6.
func (self *IReferenceOfBitmapBounds) Value() (graphicsimaging.BitmapBounds, error) {
	result := new(graphicsimaging.BitmapBounds)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IReferenceOfTimeSpan is the WinRT interface Windows.Foundation.IReference`1<Windows.Foundation.TimeSpan>.
// IID: 604d0c4c-91de-5c2a-935f-362f13eaf800
// Requires: Windows.Foundation.IPropertyValue.
type IReferenceOfTimeSpan struct {
	syswinrt.IInspectable
}

// IID_IReferenceOfTimeSpan is the interface identifier for IReferenceOfTimeSpan.
var IID_IReferenceOfTimeSpan = win32.GUID{Data1: 0x604d0c4c, Data2: 0x91de, Data3: 0x5c2a, Data4: [8]byte{0x93, 0x5f, 0x36, 0x2f, 0x13, 0xea, 0xf8, 0x00}}

// Value (propget get_Value) dispatches through IReferenceOfTimeSpan's vtable slot 6.
func (self *IReferenceOfTimeSpan) Value() (foundation.TimeSpan, error) {
	result := new(foundation.TimeSpan)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IVectorOfString is the WinRT interface Windows.Foundation.Collections.IVector`1<String>.
// IID: 98b9acc1-4b56-532e-ac73-03d5291cca90
// Requires: Windows.Foundation.Collections.IIterable`1<String>.
type IVectorOfString struct {
	syswinrt.IInspectable
}

// IID_IVectorOfString is the interface identifier for IVectorOfString.
var IID_IVectorOfString = win32.GUID{Data1: 0x98b9acc1, Data2: 0x4b56, Data3: 0x532e, Data4: [8]byte{0xac, 0x73, 0x03, 0xd5, 0x29, 0x1c, 0xca, 0x90}}

// GetAt dispatches through IVectorOfString's vtable slot 6.
func (self *IVectorOfString) GetAt(index uint32) (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Size (propget get_Size) dispatches through IVectorOfString's vtable slot 7.
func (self *IVectorOfString) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IVectorOfString's vtable slot 8.
func (self *IVectorOfString) GetView() (*IVectorViewOfString, error) {
	result := new(*IVectorViewOfString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorOfString's vtable slot 9.
func (self *IVectorOfString) IndexOf(value string, index *uint32) (bool, error) {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return false, err
	}
	defer hValue.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetAt dispatches through IVectorOfString's vtable slot 10.
func (self *IVectorOfString) SetAt(index uint32, value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// InsertAt dispatches through IVectorOfString's vtable slot 11.
func (self *IVectorOfString) InsertAt(index uint32, value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAt dispatches through IVectorOfString's vtable slot 12.
func (self *IVectorOfString) RemoveAt(index uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(index))
	return win32.ErrIfFailed(int32(r1))
}

// Append dispatches through IVectorOfString's vtable slot 13.
func (self *IVectorOfString) Append(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAtEnd dispatches through IVectorOfString's vtable slot 14.
func (self *IVectorOfString) RemoveAtEnd() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IVectorOfString's vtable slot 15.
func (self *IVectorOfString) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// slot 16: GetMany skipped: conformant array

// slot 17: ReplaceAll skipped: conformant array

// IVectorViewOfIMediaMarker is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Windows.Media.IMediaMarker>.
// IID: b543562c-02b1-5824-80a8-9854130cdadd
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Media.IMediaMarker>.
type IVectorViewOfIMediaMarker struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfIMediaMarker is the interface identifier for IVectorViewOfIMediaMarker.
var IID_IVectorViewOfIMediaMarker = win32.GUID{Data1: 0xb543562c, Data2: 0x02b1, Data3: 0x5824, Data4: [8]byte{0x80, 0xa8, 0x98, 0x54, 0x13, 0x0c, 0xda, 0xdd}}

// GetAt dispatches through IVectorViewOfIMediaMarker's vtable slot 6.
func (self *IVectorViewOfIMediaMarker) GetAt(index uint32) (*IMediaMarker, error) {
	result := new(*IMediaMarker)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfIMediaMarker's vtable slot 7.
func (self *IVectorViewOfIMediaMarker) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfIMediaMarker's vtable slot 8.
func (self *IVectorViewOfIMediaMarker) IndexOf(value *IMediaMarker, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// IVectorViewOfString is the WinRT interface Windows.Foundation.Collections.IVectorView`1<String>.
// IID: 2f13c006-a03a-5f69-b090-75a43e33423e
// Requires: Windows.Foundation.Collections.IIterable`1<String>.
type IVectorViewOfString struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfString is the interface identifier for IVectorViewOfString.
var IID_IVectorViewOfString = win32.GUID{Data1: 0x2f13c006, Data2: 0xa03a, Data3: 0x5f69, Data4: [8]byte{0xb0, 0x90, 0x75, 0xa4, 0x3e, 0x33, 0x42, 0x3e}}

// GetAt dispatches through IVectorViewOfString's vtable slot 6.
func (self *IVectorViewOfString) GetAt(index uint32) (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Size (propget get_Size) dispatches through IVectorViewOfString's vtable slot 7.
func (self *IVectorViewOfString) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfString's vtable slot 8.
func (self *IVectorViewOfString) IndexOf(value string, index *uint32) (bool, error) {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return false, err
	}
	defer hValue.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array
