// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package miracast

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
)

// AsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverApplySettingsResult>.
// IID: afcb4574-7ac3-56ea-9a6a-cf535f0cf01e
type AsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult is the delegate identifier for AsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult.
var IID_AsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult = win32.GUID{Data1: 0xafcb4574, Data2: 0x7ac3, Data3: 0x56ea, Data4: [8]byte{0x9a, 0x6a, 0xcf, 0x53, 0x5f, 0x0c, 0xf0, 0x1e}}

// NewAsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverApplySettingsResult>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult(fn func(asyncInfo *IAsyncOperationOfMiracastReceiverApplySettingsResult, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfMiracastReceiverApplySettingsResult)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverApplySettingsResult) Close() {
	h.delegate.Release()
}

// AsyncOperationCompletedHandlerOfMiracastReceiverSession is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverSession>.
// IID: 9d4308cb-4bcf-5b1b-b8b3-0484de9f3537
type AsyncOperationCompletedHandlerOfMiracastReceiverSession struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfMiracastReceiverSession is the delegate identifier for AsyncOperationCompletedHandlerOfMiracastReceiverSession.
var IID_AsyncOperationCompletedHandlerOfMiracastReceiverSession = win32.GUID{Data1: 0x9d4308cb, Data2: 0x4bcf, Data3: 0x5b1b, Data4: [8]byte{0xb8, 0xb3, 0x04, 0x84, 0xde, 0x9f, 0x35, 0x37}}

// NewAsyncOperationCompletedHandlerOfMiracastReceiverSession wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverSession>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfMiracastReceiverSession(fn func(asyncInfo *IAsyncOperationOfMiracastReceiverSession, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfMiracastReceiverSession, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfMiracastReceiverSession, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfMiracastReceiverSession)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfMiracastReceiverSession{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverSession) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverSession) Close() { h.delegate.Release() }

// AsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverSessionStartResult>.
// IID: eb315ed3-f94b-5fcc-9512-98ac9d8a423f
type AsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult is the delegate identifier for AsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult.
var IID_AsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult = win32.GUID{Data1: 0xeb315ed3, Data2: 0xf94b, Data3: 0x5fcc, Data4: [8]byte{0x95, 0x12, 0x98, 0xac, 0x9d, 0x8a, 0x42, 0x3f}}

// NewAsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverSessionStartResult>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult(fn func(asyncInfo *IAsyncOperationOfMiracastReceiverSessionStartResult, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfMiracastReceiverSessionStartResult)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverSessionStartResult) Close() {
	h.delegate.Release()
}

// AsyncOperationCompletedHandlerOfMiracastReceiverSettings is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverSettings>.
// IID: 5e89ca08-40e1-52f6-8649-04841e01820d
type AsyncOperationCompletedHandlerOfMiracastReceiverSettings struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfMiracastReceiverSettings is the delegate identifier for AsyncOperationCompletedHandlerOfMiracastReceiverSettings.
var IID_AsyncOperationCompletedHandlerOfMiracastReceiverSettings = win32.GUID{Data1: 0x5e89ca08, Data2: 0x40e1, Data3: 0x52f6, Data4: [8]byte{0x86, 0x49, 0x04, 0x84, 0x1e, 0x01, 0x82, 0x0d}}

// NewAsyncOperationCompletedHandlerOfMiracastReceiverSettings wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverSettings>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfMiracastReceiverSettings(fn func(asyncInfo *IAsyncOperationOfMiracastReceiverSettings, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfMiracastReceiverSettings, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfMiracastReceiverSettings, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfMiracastReceiverSettings)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfMiracastReceiverSettings{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverSettings) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverSettings) Close() { h.delegate.Release() }

// AsyncOperationCompletedHandlerOfMiracastReceiverStatus is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverStatus>.
// IID: 8243f2be-82a3-5335-b3c9-ae653b3b695c
type AsyncOperationCompletedHandlerOfMiracastReceiverStatus struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfMiracastReceiverStatus is the delegate identifier for AsyncOperationCompletedHandlerOfMiracastReceiverStatus.
var IID_AsyncOperationCompletedHandlerOfMiracastReceiverStatus = win32.GUID{Data1: 0x8243f2be, Data2: 0x82a3, Data3: 0x5335, Data4: [8]byte{0xb3, 0xc9, 0xae, 0x65, 0x3b, 0x3b, 0x69, 0x5c}}

// NewAsyncOperationCompletedHandlerOfMiracastReceiverStatus wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverStatus>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfMiracastReceiverStatus(fn func(asyncInfo *IAsyncOperationOfMiracastReceiverStatus, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfMiracastReceiverStatus, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfMiracastReceiverStatus, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfMiracastReceiverStatus)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfMiracastReceiverStatus{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverStatus) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverStatus) Close() { h.delegate.Release() }

// AsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverVideoStreamSettings>.
// IID: b88cbc92-b616-57d1-9f9b-6bba5d5acfa9
type AsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings is the delegate identifier for AsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings.
var IID_AsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings = win32.GUID{Data1: 0xb88cbc92, Data2: 0xb616, Data3: 0x57d1, Data4: [8]byte{0x9f, 0x9b, 0x6b, 0xba, 0x5d, 0x5a, 0xcf, 0xa9}}

// NewAsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Media.Miracast.MiracastReceiverVideoStreamSettings>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings(fn func(asyncInfo *IAsyncOperationOfMiracastReceiverVideoStreamSettings, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfMiracastReceiverVideoStreamSettings)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfMiracastReceiverVideoStreamSettings) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfMiracastReceiverAndObject is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiver, Object>.
// IID: 44eb06ea-0014-5aed-83a1-95d225d06688
type TypedEventHandlerOfMiracastReceiverAndObject struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfMiracastReceiverAndObject is the delegate identifier for TypedEventHandlerOfMiracastReceiverAndObject.
var IID_TypedEventHandlerOfMiracastReceiverAndObject = win32.GUID{Data1: 0x44eb06ea, Data2: 0x0014, Data3: 0x5aed, Data4: [8]byte{0x83, 0xa1, 0x95, 0xd2, 0x25, 0xd0, 0x66, 0x88}}

// NewTypedEventHandlerOfMiracastReceiverAndObject wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiver, Object>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfMiracastReceiverAndObject(fn func(sender *IMiracastReceiver, args *syswinrt.IInspectable)) (*TypedEventHandlerOfMiracastReceiverAndObject, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfMiracastReceiverAndObject, 2, func(raw []uintptr) uintptr {
		fn((*IMiracastReceiver)(unsafe.Pointer(raw[0])), (*syswinrt.IInspectable)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfMiracastReceiverAndObject{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfMiracastReceiverAndObject) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfMiracastReceiverAndObject) Close() { h.delegate.Release() }

// TypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverCursorImageChannel, Object>.
// IID: 401d6f64-cb30-59c3-a663-f84ab6edf1fa
type TypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject is the delegate identifier for TypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject.
var IID_TypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject = win32.GUID{Data1: 0x401d6f64, Data2: 0xcb30, Data3: 0x59c3, Data4: [8]byte{0xa6, 0x63, 0xf8, 0x4a, 0xb6, 0xed, 0xf1, 0xfa}}

// NewTypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverCursorImageChannel, Object>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject(fn func(sender *IMiracastReceiverCursorImageChannel, args *syswinrt.IInspectable)) (*TypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject, 2, func(raw []uintptr) uintptr {
		fn((*IMiracastReceiverCursorImageChannel)(unsafe.Pointer(raw[0])), (*syswinrt.IInspectable)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfMiracastReceiverCursorImageChannelAndObject) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverGameControllerDevice, Object>.
// IID: 10a9d2a7-5049-5e19-9d22-72da7d6bb643
type TypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject is the delegate identifier for TypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject.
var IID_TypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject = win32.GUID{Data1: 0x10a9d2a7, Data2: 0x5049, Data3: 0x5e19, Data4: [8]byte{0x9d, 0x22, 0x72, 0xda, 0x7d, 0x6b, 0xb6, 0x43}}

// NewTypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverGameControllerDevice, Object>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject(fn func(sender *IMiracastReceiverGameControllerDevice, args *syswinrt.IInspectable)) (*TypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject, 2, func(raw []uintptr) uintptr {
		fn((*IMiracastReceiverGameControllerDevice)(unsafe.Pointer(raw[0])), (*syswinrt.IInspectable)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfMiracastReceiverGameControllerDeviceAndObject) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverKeyboardDevice, Object>.
// IID: 97d896c7-a5ea-5209-92c0-a0278087afd1
type TypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject is the delegate identifier for TypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject.
var IID_TypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject = win32.GUID{Data1: 0x97d896c7, Data2: 0xa5ea, Data3: 0x5209, Data4: [8]byte{0x92, 0xc0, 0xa0, 0x27, 0x80, 0x87, 0xaf, 0xd1}}

// NewTypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverKeyboardDevice, Object>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject(fn func(sender *IMiracastReceiverKeyboardDevice, args *syswinrt.IInspectable)) (*TypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject, 2, func(raw []uintptr) uintptr {
		fn((*IMiracastReceiverKeyboardDevice)(unsafe.Pointer(raw[0])), (*syswinrt.IInspectable)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfMiracastReceiverKeyboardDeviceAndObject) Close() { h.delegate.Release() }

// TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverSession, Windows.Media.Miracast.MiracastReceiverConnectionCreatedEventArgs>.
// IID: 69d03828-7a8a-549a-8253-7850e4db605a
type TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs is the delegate identifier for TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs.
var IID_TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs = win32.GUID{Data1: 0x69d03828, Data2: 0x7a8a, Data3: 0x549a, Data4: [8]byte{0x82, 0x53, 0x78, 0x50, 0xe4, 0xdb, 0x60, 0x5a}}

// NewTypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverSession, Windows.Media.Miracast.MiracastReceiverConnectionCreatedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs(fn func(sender *IMiracastReceiverSession, args *IMiracastReceiverConnectionCreatedEventArgs)) (*TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IMiracastReceiverSession)(unsafe.Pointer(raw[0])), (*IMiracastReceiverConnectionCreatedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverConnectionCreatedEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverSession, Windows.Media.Miracast.MiracastReceiverDisconnectedEventArgs>.
// IID: a4964b5f-147c-57e3-82d0-cc7de5ff2def
type TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs is the delegate identifier for TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs.
var IID_TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs = win32.GUID{Data1: 0xa4964b5f, Data2: 0x147c, Data3: 0x57e3, Data4: [8]byte{0x82, 0xd0, 0xcc, 0x7d, 0xe5, 0xff, 0x2d, 0xef}}

// NewTypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverSession, Windows.Media.Miracast.MiracastReceiverDisconnectedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs(fn func(sender *IMiracastReceiverSession, args *IMiracastReceiverDisconnectedEventArgs)) (*TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IMiracastReceiverSession)(unsafe.Pointer(raw[0])), (*IMiracastReceiverDisconnectedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverDisconnectedEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverSession, Windows.Media.Miracast.MiracastReceiverMediaSourceCreatedEventArgs>.
// IID: 929ec57a-92cc-50f8-ae4a-bb6a67152e82
type TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs is the delegate identifier for TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs.
var IID_TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs = win32.GUID{Data1: 0x929ec57a, Data2: 0x92cc, Data3: 0x50f8, Data4: [8]byte{0xae, 0x4a, 0xbb, 0x6a, 0x67, 0x15, 0x2e, 0x82}}

// NewTypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Media.Miracast.MiracastReceiverSession, Windows.Media.Miracast.MiracastReceiverMediaSourceCreatedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs(fn func(sender *IMiracastReceiverSession, args *IMiracastReceiverMediaSourceCreatedEventArgs)) (*TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IMiracastReceiverSession)(unsafe.Pointer(raw[0])), (*IMiracastReceiverMediaSourceCreatedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfMiracastReceiverSessionAndMiracastReceiverMediaSourceCreatedEventArgs) Close() {
	h.delegate.Release()
}
