// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package sharetarget

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	applicationmodelcontacts "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/applicationmodel/contacts"
)

// IVectorOfString is the WinRT interface Windows.Foundation.Collections.IVector`1<String>.
// IID: 98b9acc1-4b56-532e-ac73-03d5291cca90
// Requires: Windows.Foundation.Collections.IIterable`1<String>.
type IVectorOfString struct {
	syswinrt.IInspectable
}

// IID_IVectorOfString is the interface identifier for IVectorOfString.
var IID_IVectorOfString = win32.GUID{Data1: 0x98b9acc1, Data2: 0x4b56, Data3: 0x532e, Data4: [8]byte{0xac, 0x73, 0x03, 0xd5, 0x29, 0x1c, 0xca, 0x90}}

// GetAt dispatches through IVectorOfString's vtable slot 6.
func (self *IVectorOfString) GetAt(index uint32) (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Size (propget get_Size) dispatches through IVectorOfString's vtable slot 7.
func (self *IVectorOfString) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IVectorOfString's vtable slot 8.
func (self *IVectorOfString) GetView() (*IVectorViewOfString, error) {
	result := new(*IVectorViewOfString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorOfString's vtable slot 9.
func (self *IVectorOfString) IndexOf(value string, index *uint32) (bool, error) {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return false, err
	}
	defer hValue.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetAt dispatches through IVectorOfString's vtable slot 10.
func (self *IVectorOfString) SetAt(index uint32, value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// InsertAt dispatches through IVectorOfString's vtable slot 11.
func (self *IVectorOfString) InsertAt(index uint32, value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAt dispatches through IVectorOfString's vtable slot 12.
func (self *IVectorOfString) RemoveAt(index uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(index))
	return win32.ErrIfFailed(int32(r1))
}

// Append dispatches through IVectorOfString's vtable slot 13.
func (self *IVectorOfString) Append(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAtEnd dispatches through IVectorOfString's vtable slot 14.
func (self *IVectorOfString) RemoveAtEnd() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IVectorOfString's vtable slot 15.
func (self *IVectorOfString) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// slot 16: GetMany skipped: conformant array

// slot 17: ReplaceAll skipped: conformant array

// IVectorViewOfContact is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Windows.ApplicationModel.Contacts.Contact>.
// IID: 9bca75b8-b0fa-5761-b959-381927a5f9d0
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.ApplicationModel.Contacts.Contact>.
type IVectorViewOfContact struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfContact is the interface identifier for IVectorViewOfContact.
var IID_IVectorViewOfContact = win32.GUID{Data1: 0x9bca75b8, Data2: 0xb0fa, Data3: 0x5761, Data4: [8]byte{0xb9, 0x59, 0x38, 0x19, 0x27, 0xa5, 0xf9, 0xd0}}

// GetAt dispatches through IVectorViewOfContact's vtable slot 6.
func (self *IVectorViewOfContact) GetAt(index uint32) (*applicationmodelcontacts.IContact, error) {
	result := new(*applicationmodelcontacts.IContact)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfContact's vtable slot 7.
func (self *IVectorViewOfContact) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfContact's vtable slot 8.
func (self *IVectorViewOfContact) IndexOf(value *applicationmodelcontacts.IContact, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// IVectorViewOfString is the WinRT interface Windows.Foundation.Collections.IVectorView`1<String>.
// IID: 2f13c006-a03a-5f69-b090-75a43e33423e
// Requires: Windows.Foundation.Collections.IIterable`1<String>.
type IVectorViewOfString struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfString is the interface identifier for IVectorViewOfString.
var IID_IVectorViewOfString = win32.GUID{Data1: 0x2f13c006, Data2: 0xa03a, Data3: 0x5f69, Data4: [8]byte{0xb0, 0x90, 0x75, 0xa4, 0x3e, 0x33, 0x42, 0x3e}}

// GetAt dispatches through IVectorViewOfString's vtable slot 6.
func (self *IVectorViewOfString) GetAt(index uint32) (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Size (propget get_Size) dispatches through IVectorViewOfString's vtable slot 7.
func (self *IVectorViewOfString) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfString's vtable slot 8.
func (self *IVectorViewOfString) IndexOf(value string, index *uint32) (bool, error) {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return false, err
	}
	defer hValue.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array
