// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package proximity

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
)

// AsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Foundation.Collections.IVectorView`1<Windows.Networking.Proximity.PeerInformation>>.
// IID: ecf90f2c-e3f4-5b62-a066-8b9c818fd41a
type AsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation is the delegate identifier for AsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation.
var IID_AsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation = win32.GUID{Data1: 0xecf90f2c, Data2: 0xe3f4, Data3: 0x5b62, Data4: [8]byte{0xa0, 0x66, 0x8b, 0x9c, 0x81, 0x8f, 0xd4, 0x1a}}

// NewAsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Foundation.Collections.IVectorView`1<Windows.Networking.Proximity.PeerInformation>>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation(fn func(asyncInfo *IAsyncOperationOfIVectorViewOfPeerInformation, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfIVectorViewOfPeerInformation)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfIVectorViewOfPeerInformation) Close() { h.delegate.Release() }

// AsyncOperationCompletedHandlerOfStreamSocket is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Networking.Sockets.StreamSocket>.
// IID: 71b5d99e-3854-5e9a-b4dc-d1b58bf198fc
type AsyncOperationCompletedHandlerOfStreamSocket struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfStreamSocket is the delegate identifier for AsyncOperationCompletedHandlerOfStreamSocket.
var IID_AsyncOperationCompletedHandlerOfStreamSocket = win32.GUID{Data1: 0x71b5d99e, Data2: 0x3854, Data3: 0x5e9a, Data4: [8]byte{0xb4, 0xdc, 0xd1, 0xb5, 0x8b, 0xf1, 0x98, 0xfc}}

// NewAsyncOperationCompletedHandlerOfStreamSocket wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Networking.Sockets.StreamSocket>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfStreamSocket(fn func(asyncInfo *IAsyncOperationOfStreamSocket, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfStreamSocket, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfStreamSocket, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfStreamSocket)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfStreamSocket{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfStreamSocket) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfStreamSocket) Close() { h.delegate.Release() }

// DeviceArrivedEventHandler is a Go-implemented handler for the WinRT delegate
// Windows.Networking.Proximity.DeviceArrivedEventHandler.
// IID: efa9da69-f6e1-49c9-a49e-8e0fc58fb911
type DeviceArrivedEventHandler struct {
	delegate *winrt.Delegate
}

// IID_DeviceArrivedEventHandler is the delegate identifier for DeviceArrivedEventHandler.
var IID_DeviceArrivedEventHandler = win32.GUID{Data1: 0xefa9da69, Data2: 0xf6e1, Data3: 0x49c9, Data4: [8]byte{0xa4, 0x9e, 0x8e, 0x0f, 0xc5, 0x8f, 0xb9, 0x11}}

// NewDeviceArrivedEventHandler wraps fn as a COM-callable Windows.Networking.Proximity.DeviceArrivedEventHandler.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewDeviceArrivedEventHandler(fn func(sender *IProximityDevice)) (*DeviceArrivedEventHandler, error) {
	delegate, err := winrt.NewDelegate(IID_DeviceArrivedEventHandler, 1, func(raw []uintptr) uintptr {
		fn((*IProximityDevice)(unsafe.Pointer(raw[0])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &DeviceArrivedEventHandler{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *DeviceArrivedEventHandler) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *DeviceArrivedEventHandler) Close() { h.delegate.Release() }

// DeviceDepartedEventHandler is a Go-implemented handler for the WinRT delegate
// Windows.Networking.Proximity.DeviceDepartedEventHandler.
// IID: efa9da69-f6e2-49c9-a49e-8e0fc58fb911
type DeviceDepartedEventHandler struct {
	delegate *winrt.Delegate
}

// IID_DeviceDepartedEventHandler is the delegate identifier for DeviceDepartedEventHandler.
var IID_DeviceDepartedEventHandler = win32.GUID{Data1: 0xefa9da69, Data2: 0xf6e2, Data3: 0x49c9, Data4: [8]byte{0xa4, 0x9e, 0x8e, 0x0f, 0xc5, 0x8f, 0xb9, 0x11}}

// NewDeviceDepartedEventHandler wraps fn as a COM-callable Windows.Networking.Proximity.DeviceDepartedEventHandler.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewDeviceDepartedEventHandler(fn func(sender *IProximityDevice)) (*DeviceDepartedEventHandler, error) {
	delegate, err := winrt.NewDelegate(IID_DeviceDepartedEventHandler, 1, func(raw []uintptr) uintptr {
		fn((*IProximityDevice)(unsafe.Pointer(raw[0])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &DeviceDepartedEventHandler{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *DeviceDepartedEventHandler) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *DeviceDepartedEventHandler) Close() { h.delegate.Release() }

// MessageReceivedHandler is a Go-implemented handler for the WinRT delegate
// Windows.Networking.Proximity.MessageReceivedHandler.
// IID: efab0782-f6e2-4675-a045-d8e320c24808
type MessageReceivedHandler struct {
	delegate *winrt.Delegate
}

// IID_MessageReceivedHandler is the delegate identifier for MessageReceivedHandler.
var IID_MessageReceivedHandler = win32.GUID{Data1: 0xefab0782, Data2: 0xf6e2, Data3: 0x4675, Data4: [8]byte{0xa0, 0x45, 0xd8, 0xe3, 0x20, 0xc2, 0x48, 0x08}}

// NewMessageReceivedHandler wraps fn as a COM-callable Windows.Networking.Proximity.MessageReceivedHandler.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewMessageReceivedHandler(fn func(sender *IProximityDevice, message *IProximityMessage)) (*MessageReceivedHandler, error) {
	delegate, err := winrt.NewDelegate(IID_MessageReceivedHandler, 2, func(raw []uintptr) uintptr {
		fn((*IProximityDevice)(unsafe.Pointer(raw[0])), (*IProximityMessage)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &MessageReceivedHandler{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *MessageReceivedHandler) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *MessageReceivedHandler) Close() { h.delegate.Release() }

// MessageTransmittedHandler is a Go-implemented handler for the WinRT delegate
// Windows.Networking.Proximity.MessageTransmittedHandler.
// IID: efaa0b4a-f6e2-4d7d-856c-78fc8efc021e
type MessageTransmittedHandler struct {
	delegate *winrt.Delegate
}

// IID_MessageTransmittedHandler is the delegate identifier for MessageTransmittedHandler.
var IID_MessageTransmittedHandler = win32.GUID{Data1: 0xefaa0b4a, Data2: 0xf6e2, Data3: 0x4d7d, Data4: [8]byte{0x85, 0x6c, 0x78, 0xfc, 0x8e, 0xfc, 0x02, 0x1e}}

// NewMessageTransmittedHandler wraps fn as a COM-callable Windows.Networking.Proximity.MessageTransmittedHandler.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewMessageTransmittedHandler(fn func(sender *IProximityDevice, messageId int64)) (*MessageTransmittedHandler, error) {
	delegate, err := winrt.NewDelegate(IID_MessageTransmittedHandler, 2, func(raw []uintptr) uintptr {
		fn((*IProximityDevice)(unsafe.Pointer(raw[0])), int64(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &MessageTransmittedHandler{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *MessageTransmittedHandler) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *MessageTransmittedHandler) Close() { h.delegate.Release() }

// TypedEventHandlerOfObjectAndConnectionRequestedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Object, Windows.Networking.Proximity.ConnectionRequestedEventArgs>.
// IID: 512c383c-8b29-5079-953e-8dee8f8a8224
type TypedEventHandlerOfObjectAndConnectionRequestedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfObjectAndConnectionRequestedEventArgs is the delegate identifier for TypedEventHandlerOfObjectAndConnectionRequestedEventArgs.
var IID_TypedEventHandlerOfObjectAndConnectionRequestedEventArgs = win32.GUID{Data1: 0x512c383c, Data2: 0x8b29, Data3: 0x5079, Data4: [8]byte{0x95, 0x3e, 0x8d, 0xee, 0x8f, 0x8a, 0x82, 0x24}}

// NewTypedEventHandlerOfObjectAndConnectionRequestedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Object, Windows.Networking.Proximity.ConnectionRequestedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfObjectAndConnectionRequestedEventArgs(fn func(sender *syswinrt.IInspectable, args *IConnectionRequestedEventArgs)) (*TypedEventHandlerOfObjectAndConnectionRequestedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfObjectAndConnectionRequestedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*syswinrt.IInspectable)(unsafe.Pointer(raw[0])), (*IConnectionRequestedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfObjectAndConnectionRequestedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfObjectAndConnectionRequestedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfObjectAndConnectionRequestedEventArgs) Close() { h.delegate.Release() }

// TypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Object, Windows.Networking.Proximity.TriggeredConnectionStateChangedEventArgs>.
// IID: 2e5ad6fa-3ca6-5518-bd4d-fefc4535580e
type TypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs is the delegate identifier for TypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs.
var IID_TypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs = win32.GUID{Data1: 0x2e5ad6fa, Data2: 0x3ca6, Data3: 0x5518, Data4: [8]byte{0xbd, 0x4d, 0xfe, 0xfc, 0x45, 0x35, 0x58, 0x0e}}

// NewTypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Object, Windows.Networking.Proximity.TriggeredConnectionStateChangedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs(fn func(sender *syswinrt.IInspectable, args *ITriggeredConnectionStateChangedEventArgs)) (*TypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*syswinrt.IInspectable)(unsafe.Pointer(raw[0])), (*ITriggeredConnectionStateChangedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfObjectAndTriggeredConnectionStateChangedEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfPeerWatcherAndObject is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Networking.Proximity.PeerWatcher, Object>.
// IID: f4979ea1-7e06-50a8-88dc-3f29524e4fdb
type TypedEventHandlerOfPeerWatcherAndObject struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfPeerWatcherAndObject is the delegate identifier for TypedEventHandlerOfPeerWatcherAndObject.
var IID_TypedEventHandlerOfPeerWatcherAndObject = win32.GUID{Data1: 0xf4979ea1, Data2: 0x7e06, Data3: 0x50a8, Data4: [8]byte{0x88, 0xdc, 0x3f, 0x29, 0x52, 0x4e, 0x4f, 0xdb}}

// NewTypedEventHandlerOfPeerWatcherAndObject wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Networking.Proximity.PeerWatcher, Object>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfPeerWatcherAndObject(fn func(sender *IPeerWatcher, args *syswinrt.IInspectable)) (*TypedEventHandlerOfPeerWatcherAndObject, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfPeerWatcherAndObject, 2, func(raw []uintptr) uintptr {
		fn((*IPeerWatcher)(unsafe.Pointer(raw[0])), (*syswinrt.IInspectable)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfPeerWatcherAndObject{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfPeerWatcherAndObject) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfPeerWatcherAndObject) Close() { h.delegate.Release() }

// TypedEventHandlerOfPeerWatcherAndPeerInformation is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Networking.Proximity.PeerWatcher, Windows.Networking.Proximity.PeerInformation>.
// IID: ad674bbf-6281-5943-9772-e0fd7664d4e1
type TypedEventHandlerOfPeerWatcherAndPeerInformation struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfPeerWatcherAndPeerInformation is the delegate identifier for TypedEventHandlerOfPeerWatcherAndPeerInformation.
var IID_TypedEventHandlerOfPeerWatcherAndPeerInformation = win32.GUID{Data1: 0xad674bbf, Data2: 0x6281, Data3: 0x5943, Data4: [8]byte{0x97, 0x72, 0xe0, 0xfd, 0x76, 0x64, 0xd4, 0xe1}}

// NewTypedEventHandlerOfPeerWatcherAndPeerInformation wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Networking.Proximity.PeerWatcher, Windows.Networking.Proximity.PeerInformation>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfPeerWatcherAndPeerInformation(fn func(sender *IPeerWatcher, args *IPeerInformation)) (*TypedEventHandlerOfPeerWatcherAndPeerInformation, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfPeerWatcherAndPeerInformation, 2, func(raw []uintptr) uintptr {
		fn((*IPeerWatcher)(unsafe.Pointer(raw[0])), (*IPeerInformation)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfPeerWatcherAndPeerInformation{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfPeerWatcherAndPeerInformation) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfPeerWatcherAndPeerInformation) Close() { h.delegate.Release() }
