// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package foreground

import (
	"fmt"
)

// ExtendedExecutionForegroundReason is Windows.ApplicationModel.ExtendedExecution.Foreground.ExtendedExecutionForegroundReason.
type ExtendedExecutionForegroundReason int32

const (
	ExtendedExecutionForegroundReasonUnspecified     ExtendedExecutionForegroundReason = 0
	ExtendedExecutionForegroundReasonSavingData      ExtendedExecutionForegroundReason = 1
	ExtendedExecutionForegroundReasonBackgroundAudio ExtendedExecutionForegroundReason = 2
	ExtendedExecutionForegroundReasonUnconstrained   ExtendedExecutionForegroundReason = 3
)

// String returns the ExtendedExecutionForegroundReason constant's name, or its numeric form when
// the value is not a known constant.
func (e ExtendedExecutionForegroundReason) String() string {
	switch e {
	case ExtendedExecutionForegroundReasonUnspecified:
		return "ExtendedExecutionForegroundReasonUnspecified"
	case ExtendedExecutionForegroundReasonSavingData:
		return "ExtendedExecutionForegroundReasonSavingData"
	case ExtendedExecutionForegroundReasonBackgroundAudio:
		return "ExtendedExecutionForegroundReasonBackgroundAudio"
	case ExtendedExecutionForegroundReasonUnconstrained:
		return "ExtendedExecutionForegroundReasonUnconstrained"
	default:
		return fmt.Sprintf("ExtendedExecutionForegroundReason(%d)", int32(e))
	}
}

// ExtendedExecutionForegroundResult is Windows.ApplicationModel.ExtendedExecution.Foreground.ExtendedExecutionForegroundResult.
type ExtendedExecutionForegroundResult int32

const (
	ExtendedExecutionForegroundResultAllowed ExtendedExecutionForegroundResult = 0
	ExtendedExecutionForegroundResultDenied  ExtendedExecutionForegroundResult = 1
)

// String returns the ExtendedExecutionForegroundResult constant's name, or its numeric form when
// the value is not a known constant.
func (e ExtendedExecutionForegroundResult) String() string {
	switch e {
	case ExtendedExecutionForegroundResultAllowed:
		return "ExtendedExecutionForegroundResultAllowed"
	case ExtendedExecutionForegroundResultDenied:
		return "ExtendedExecutionForegroundResultDenied"
	default:
		return fmt.Sprintf("ExtendedExecutionForegroundResult(%d)", int32(e))
	}
}

// ExtendedExecutionForegroundRevokedReason is Windows.ApplicationModel.ExtendedExecution.Foreground.ExtendedExecutionForegroundRevokedReason.
type ExtendedExecutionForegroundRevokedReason int32

const (
	ExtendedExecutionForegroundRevokedReasonResumed      ExtendedExecutionForegroundRevokedReason = 0
	ExtendedExecutionForegroundRevokedReasonSystemPolicy ExtendedExecutionForegroundRevokedReason = 1
)

// String returns the ExtendedExecutionForegroundRevokedReason constant's name, or its numeric form when
// the value is not a known constant.
func (e ExtendedExecutionForegroundRevokedReason) String() string {
	switch e {
	case ExtendedExecutionForegroundRevokedReasonResumed:
		return "ExtendedExecutionForegroundRevokedReasonResumed"
	case ExtendedExecutionForegroundRevokedReasonSystemPolicy:
		return "ExtendedExecutionForegroundRevokedReasonSystemPolicy"
	default:
		return fmt.Sprintf("ExtendedExecutionForegroundRevokedReason(%d)", int32(e))
	}
}
