// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package applicationsettings

import (
	"fmt"
)

// SupportedWebAccountActions is Windows.UI.ApplicationSettings.SupportedWebAccountActions.
// Bitmask — values may be combined with |.
type SupportedWebAccountActions uint32

const (
	SupportedWebAccountActionsNone        SupportedWebAccountActions = 0
	SupportedWebAccountActionsReconnect   SupportedWebAccountActions = 1
	SupportedWebAccountActionsRemove      SupportedWebAccountActions = 2
	SupportedWebAccountActionsViewDetails SupportedWebAccountActions = 4
	SupportedWebAccountActionsManage      SupportedWebAccountActions = 8
	SupportedWebAccountActionsMore        SupportedWebAccountActions = 16
)

// String returns the SupportedWebAccountActions constant's name, or its numeric form when
// the value is not a known constant.
func (e SupportedWebAccountActions) String() string {
	switch e {
	case SupportedWebAccountActionsNone:
		return "SupportedWebAccountActionsNone"
	case SupportedWebAccountActionsReconnect:
		return "SupportedWebAccountActionsReconnect"
	case SupportedWebAccountActionsRemove:
		return "SupportedWebAccountActionsRemove"
	case SupportedWebAccountActionsViewDetails:
		return "SupportedWebAccountActionsViewDetails"
	case SupportedWebAccountActionsManage:
		return "SupportedWebAccountActionsManage"
	case SupportedWebAccountActionsMore:
		return "SupportedWebAccountActionsMore"
	default:
		return fmt.Sprintf("SupportedWebAccountActions(%d)", uint32(e))
	}
}

// WebAccountAction is Windows.UI.ApplicationSettings.WebAccountAction.
type WebAccountAction int32

const (
	WebAccountActionReconnect   WebAccountAction = 0
	WebAccountActionRemove      WebAccountAction = 1
	WebAccountActionViewDetails WebAccountAction = 2
	WebAccountActionManage      WebAccountAction = 3
	WebAccountActionMore        WebAccountAction = 4
)

// String returns the WebAccountAction constant's name, or its numeric form when
// the value is not a known constant.
func (e WebAccountAction) String() string {
	switch e {
	case WebAccountActionReconnect:
		return "WebAccountActionReconnect"
	case WebAccountActionRemove:
		return "WebAccountActionRemove"
	case WebAccountActionViewDetails:
		return "WebAccountActionViewDetails"
	case WebAccountActionManage:
		return "WebAccountActionManage"
	case WebAccountActionMore:
		return "WebAccountActionMore"
	default:
		return fmt.Sprintf("WebAccountAction(%d)", int32(e))
	}
}
