// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package provider

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	applicationmodelpayments "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/applicationmodel/payments"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
)

// IPaymentAppCanMakePaymentTriggerDetails is the WinRT interface Windows.ApplicationModel.Payments.Provider.IPaymentAppCanMakePaymentTriggerDetails.
// IID: 0ce201f0-8b93-4eb6-8c46-2e4a6c6a26f6
// Exclusive to the Windows.ApplicationModel.Payments.Provider.PaymentAppCanMakePaymentTriggerDetails runtime class.
type IPaymentAppCanMakePaymentTriggerDetails struct {
	syswinrt.IInspectable
}

// IID_IPaymentAppCanMakePaymentTriggerDetails is the interface identifier for IPaymentAppCanMakePaymentTriggerDetails.
var IID_IPaymentAppCanMakePaymentTriggerDetails = win32.GUID{Data1: 0x0ce201f0, Data2: 0x8b93, Data3: 0x4eb6, Data4: [8]byte{0x8c, 0x46, 0x2e, 0x4a, 0x6c, 0x6a, 0x26, 0xf6}}

// Request (propget get_Request) dispatches through IPaymentAppCanMakePaymentTriggerDetails's vtable slot 6.
func (self *IPaymentAppCanMakePaymentTriggerDetails) Request() (*applicationmodelpayments.IPaymentRequest, error) {
	result := new(*applicationmodelpayments.IPaymentRequest)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ReportCanMakePaymentResult dispatches through IPaymentAppCanMakePaymentTriggerDetails's vtable slot 7.
func (self *IPaymentAppCanMakePaymentTriggerDetails) ReportCanMakePaymentResult(value *applicationmodelpayments.IPaymentCanMakePaymentResult) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// IPaymentAppManager is the WinRT interface Windows.ApplicationModel.Payments.Provider.IPaymentAppManager.
// IID: 0e47aa53-8521-4969-a957-df2538a3a98f
// Exclusive to the Windows.ApplicationModel.Payments.Provider.PaymentAppManager runtime class.
type IPaymentAppManager struct {
	syswinrt.IInspectable
}

// IID_IPaymentAppManager is the interface identifier for IPaymentAppManager.
var IID_IPaymentAppManager = win32.GUID{Data1: 0x0e47aa53, Data2: 0x8521, Data3: 0x4969, Data4: [8]byte{0xa9, 0x57, 0xdf, 0x25, 0x38, 0xa3, 0xa9, 0x8f}}

// RegisterAsync dispatches through IPaymentAppManager's vtable slot 6.
func (self *IPaymentAppManager) RegisterAsync(supportedPaymentMethodIds *IIterableOfString) (*foundation.IAsyncAction, error) {
	result := new(*foundation.IAsyncAction)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(supportedPaymentMethodIds)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// UnregisterAsync dispatches through IPaymentAppManager's vtable slot 7.
func (self *IPaymentAppManager) UnregisterAsync() (*foundation.IAsyncAction, error) {
	result := new(*foundation.IAsyncAction)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IPaymentAppManagerStatics is the WinRT interface Windows.ApplicationModel.Payments.Provider.IPaymentAppManagerStatics.
// IID: a341ac28-fc89-4406-b4d9-34e7fe79dfb6
// Exclusive to the Windows.ApplicationModel.Payments.Provider.PaymentAppManager runtime class.
type IPaymentAppManagerStatics struct {
	syswinrt.IInspectable
}

// IID_IPaymentAppManagerStatics is the interface identifier for IPaymentAppManagerStatics.
var IID_IPaymentAppManagerStatics = win32.GUID{Data1: 0xa341ac28, Data2: 0xfc89, Data3: 0x4406, Data4: [8]byte{0xb4, 0xd9, 0x34, 0xe7, 0xfe, 0x79, 0xdf, 0xb6}}

// Current (propget get_Current) dispatches through IPaymentAppManagerStatics's vtable slot 6.
func (self *IPaymentAppManagerStatics) Current() (*IPaymentAppManager, error) {
	result := new(*IPaymentAppManager)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IPaymentTransaction is the WinRT interface Windows.ApplicationModel.Payments.Provider.IPaymentTransaction.
// IID: 62581da0-26a5-4e9b-a6eb-66606cf001d3
// Exclusive to the Windows.ApplicationModel.Payments.Provider.PaymentTransaction runtime class.
type IPaymentTransaction struct {
	syswinrt.IInspectable
}

// IID_IPaymentTransaction is the interface identifier for IPaymentTransaction.
var IID_IPaymentTransaction = win32.GUID{Data1: 0x62581da0, Data2: 0x26a5, Data3: 0x4e9b, Data4: [8]byte{0xa6, 0xeb, 0x66, 0x60, 0x6c, 0xf0, 0x01, 0xd3}}

// PaymentRequest (propget get_PaymentRequest) dispatches through IPaymentTransaction's vtable slot 6.
func (self *IPaymentTransaction) PaymentRequest() (*applicationmodelpayments.IPaymentRequest, error) {
	result := new(*applicationmodelpayments.IPaymentRequest)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// PayerEmail (propget get_PayerEmail) dispatches through IPaymentTransaction's vtable slot 7.
func (self *IPaymentTransaction) PayerEmail() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// SetPayerEmail (propput put_PayerEmail) dispatches through IPaymentTransaction's vtable slot 8.
func (self *IPaymentTransaction) SetPayerEmail(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// PayerName (propget get_PayerName) dispatches through IPaymentTransaction's vtable slot 9.
func (self *IPaymentTransaction) PayerName() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// SetPayerName (propput put_PayerName) dispatches through IPaymentTransaction's vtable slot 10.
func (self *IPaymentTransaction) SetPayerName(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// PayerPhoneNumber (propget get_PayerPhoneNumber) dispatches through IPaymentTransaction's vtable slot 11.
func (self *IPaymentTransaction) PayerPhoneNumber() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// SetPayerPhoneNumber (propput put_PayerPhoneNumber) dispatches through IPaymentTransaction's vtable slot 12.
func (self *IPaymentTransaction) SetPayerPhoneNumber(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// UpdateShippingAddressAsync dispatches through IPaymentTransaction's vtable slot 13.
func (self *IPaymentTransaction) UpdateShippingAddressAsync(shippingAddress *applicationmodelpayments.IPaymentAddress) (*IAsyncOperationOfPaymentRequestChangedResult, error) {
	result := new(*IAsyncOperationOfPaymentRequestChangedResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(shippingAddress)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// UpdateSelectedShippingOptionAsync dispatches through IPaymentTransaction's vtable slot 14.
func (self *IPaymentTransaction) UpdateSelectedShippingOptionAsync(selectedShippingOption *applicationmodelpayments.IPaymentShippingOption) (*IAsyncOperationOfPaymentRequestChangedResult, error) {
	result := new(*IAsyncOperationOfPaymentRequestChangedResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(selectedShippingOption)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// AcceptAsync dispatches through IPaymentTransaction's vtable slot 15.
func (self *IPaymentTransaction) AcceptAsync(paymentToken *applicationmodelpayments.IPaymentToken) (*IAsyncOperationOfPaymentTransactionAcceptResult, error) {
	result := new(*IAsyncOperationOfPaymentTransactionAcceptResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(paymentToken)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Reject dispatches through IPaymentTransaction's vtable slot 16.
func (self *IPaymentTransaction) Reject() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[16], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// IPaymentTransactionAcceptResult is the WinRT interface Windows.ApplicationModel.Payments.Provider.IPaymentTransactionAcceptResult.
// IID: 060e3276-d30c-4817-95a2-df7ae9273b56
// Exclusive to the Windows.ApplicationModel.Payments.Provider.PaymentTransactionAcceptResult runtime class.
type IPaymentTransactionAcceptResult struct {
	syswinrt.IInspectable
}

// IID_IPaymentTransactionAcceptResult is the interface identifier for IPaymentTransactionAcceptResult.
var IID_IPaymentTransactionAcceptResult = win32.GUID{Data1: 0x060e3276, Data2: 0xd30c, Data3: 0x4817, Data4: [8]byte{0x95, 0xa2, 0xdf, 0x7a, 0xe9, 0x27, 0x3b, 0x56}}

// Status (propget get_Status) dispatches through IPaymentTransactionAcceptResult's vtable slot 6.
func (self *IPaymentTransactionAcceptResult) Status() (applicationmodelpayments.PaymentRequestCompletionStatus, error) {
	result := new(applicationmodelpayments.PaymentRequestCompletionStatus)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IPaymentTransactionStatics is the WinRT interface Windows.ApplicationModel.Payments.Provider.IPaymentTransactionStatics.
// IID: 8d639750-ee0a-4df5-9b1e-1c0f9ec59881
// Exclusive to the Windows.ApplicationModel.Payments.Provider.PaymentTransaction runtime class.
type IPaymentTransactionStatics struct {
	syswinrt.IInspectable
}

// IID_IPaymentTransactionStatics is the interface identifier for IPaymentTransactionStatics.
var IID_IPaymentTransactionStatics = win32.GUID{Data1: 0x8d639750, Data2: 0xee0a, Data3: 0x4df5, Data4: [8]byte{0x9b, 0x1e, 0x1c, 0x0f, 0x9e, 0xc5, 0x98, 0x81}}

// FromIdAsync dispatches through IPaymentTransactionStatics's vtable slot 6.
func (self *IPaymentTransactionStatics) FromIdAsync(id string) (*IAsyncOperationOfPaymentTransaction, error) {
	hId, err := winrt.NewHString(id)
	if err != nil {
		return nil, err
	}
	defer hId.Close()
	result := new(*IAsyncOperationOfPaymentTransaction)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hId.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
