// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package power

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	systempower "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/system/power"
)

// IBattery is the WinRT interface Windows.Devices.Power.IBattery.
// IID: bc894fc6-0072-47c8-8b5d-614aaa7a437e
// Exclusive to the Windows.Devices.Power.Battery runtime class.
type IBattery struct {
	syswinrt.IInspectable
}

// IID_IBattery is the interface identifier for IBattery.
var IID_IBattery = win32.GUID{Data1: 0xbc894fc6, Data2: 0x0072, Data3: 0x47c8, Data4: [8]byte{0x8b, 0x5d, 0x61, 0x4a, 0xaa, 0x7a, 0x43, 0x7e}}

// DeviceId (propget get_DeviceId) dispatches through IBattery's vtable slot 6.
func (self *IBattery) DeviceId() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// GetReport dispatches through IBattery's vtable slot 7.
func (self *IBattery) GetReport() (*IBatteryReport, error) {
	result := new(*IBatteryReport)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// AddReportUpdated (event add add_ReportUpdated) dispatches through IBattery's vtable slot 8.
// The handler stays registered (and referenced by the runtime) until the
// returned token is passed to RemoveReportUpdated.
func (self *IBattery) AddReportUpdated(handler *TypedEventHandlerOfBatteryAndObject) (syswinrt.EventRegistrationToken, error) {
	result := new(syswinrt.EventRegistrationToken)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), handler.Ptr(), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemoveReportUpdated (event remove remove_ReportUpdated) dispatches through IBattery's vtable slot 9,
// unregistering the ReportUpdated handler the token was returned for.
func (self *IBattery) RemoveReportUpdated(token syswinrt.EventRegistrationToken) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(token.Value))
	return win32.ErrIfFailed(int32(r1))
}

// IBatteryReport is the WinRT interface Windows.Devices.Power.IBatteryReport.
// IID: c9858c3a-4e13-420a-a8d0-24f18f395401
// Exclusive to the Windows.Devices.Power.BatteryReport runtime class.
type IBatteryReport struct {
	syswinrt.IInspectable
}

// IID_IBatteryReport is the interface identifier for IBatteryReport.
var IID_IBatteryReport = win32.GUID{Data1: 0xc9858c3a, Data2: 0x4e13, Data3: 0x420a, Data4: [8]byte{0xa8, 0xd0, 0x24, 0xf1, 0x8f, 0x39, 0x54, 0x01}}

// ChargeRateInMilliwatts (propget get_ChargeRateInMilliwatts) dispatches through IBatteryReport's vtable slot 6.
func (self *IBatteryReport) ChargeRateInMilliwatts() (*IReferenceOfInt32, error) {
	result := new(*IReferenceOfInt32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DesignCapacityInMilliwattHours (propget get_DesignCapacityInMilliwattHours) dispatches through IBatteryReport's vtable slot 7.
func (self *IBatteryReport) DesignCapacityInMilliwattHours() (*IReferenceOfInt32, error) {
	result := new(*IReferenceOfInt32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// FullChargeCapacityInMilliwattHours (propget get_FullChargeCapacityInMilliwattHours) dispatches through IBatteryReport's vtable slot 8.
func (self *IBatteryReport) FullChargeCapacityInMilliwattHours() (*IReferenceOfInt32, error) {
	result := new(*IReferenceOfInt32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemainingCapacityInMilliwattHours (propget get_RemainingCapacityInMilliwattHours) dispatches through IBatteryReport's vtable slot 9.
func (self *IBatteryReport) RemainingCapacityInMilliwattHours() (*IReferenceOfInt32, error) {
	result := new(*IReferenceOfInt32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Status (propget get_Status) dispatches through IBatteryReport's vtable slot 10.
func (self *IBatteryReport) Status() (systempower.BatteryStatus, error) {
	result := new(systempower.BatteryStatus)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IBatteryStatics is the WinRT interface Windows.Devices.Power.IBatteryStatics.
// IID: 79cd72b6-9e5e-4452-bea6-dfcd541e597f
// Exclusive to the Windows.Devices.Power.Battery runtime class.
type IBatteryStatics struct {
	syswinrt.IInspectable
}

// IID_IBatteryStatics is the interface identifier for IBatteryStatics.
var IID_IBatteryStatics = win32.GUID{Data1: 0x79cd72b6, Data2: 0x9e5e, Data3: 0x4452, Data4: [8]byte{0xbe, 0xa6, 0xdf, 0xcd, 0x54, 0x1e, 0x59, 0x7f}}

// AggregateBattery (propget get_AggregateBattery) dispatches through IBatteryStatics's vtable slot 6.
func (self *IBatteryStatics) AggregateBattery() (*IBattery, error) {
	result := new(*IBattery)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// FromIdAsync dispatches through IBatteryStatics's vtable slot 7.
func (self *IBatteryStatics) FromIdAsync(deviceId string) (*IAsyncOperationOfBattery, error) {
	hDeviceId, err := winrt.NewHString(deviceId)
	if err != nil {
		return nil, err
	}
	defer hDeviceId.Close()
	result := new(*IAsyncOperationOfBattery)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(hDeviceId.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetDeviceSelector dispatches through IBatteryStatics's vtable slot 8.
func (self *IBatteryStatics) GetDeviceSelector() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}
