// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package provider

import (
	"fmt"
)

// BarcodeScannerTriggerState is Windows.Devices.PointOfService.Provider.BarcodeScannerTriggerState.
type BarcodeScannerTriggerState int32

const (
	BarcodeScannerTriggerStateReleased BarcodeScannerTriggerState = 0
	BarcodeScannerTriggerStatePressed  BarcodeScannerTriggerState = 1
)

// String returns the BarcodeScannerTriggerState constant's name, or its numeric form when
// the value is not a known constant.
func (e BarcodeScannerTriggerState) String() string {
	switch e {
	case BarcodeScannerTriggerStateReleased:
		return "BarcodeScannerTriggerStateReleased"
	case BarcodeScannerTriggerStatePressed:
		return "BarcodeScannerTriggerStatePressed"
	default:
		return fmt.Sprintf("BarcodeScannerTriggerState(%d)", int32(e))
	}
}
