// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package primitives

import (
	"fmt"
)

// AnimationDirection is Windows.UI.Xaml.Controls.Primitives.AnimationDirection.
type AnimationDirection int32

const (
	AnimationDirectionLeft   AnimationDirection = 0
	AnimationDirectionTop    AnimationDirection = 1
	AnimationDirectionRight  AnimationDirection = 2
	AnimationDirectionBottom AnimationDirection = 3
)

// String returns the AnimationDirection constant's name, or its numeric form when
// the value is not a known constant.
func (e AnimationDirection) String() string {
	switch e {
	case AnimationDirectionLeft:
		return "AnimationDirectionLeft"
	case AnimationDirectionTop:
		return "AnimationDirectionTop"
	case AnimationDirectionRight:
		return "AnimationDirectionRight"
	case AnimationDirectionBottom:
		return "AnimationDirectionBottom"
	default:
		return fmt.Sprintf("AnimationDirection(%d)", int32(e))
	}
}

// ComponentResourceLocation is Windows.UI.Xaml.Controls.Primitives.ComponentResourceLocation.
type ComponentResourceLocation int32

const (
	ComponentResourceLocationApplication ComponentResourceLocation = 0
	ComponentResourceLocationNested      ComponentResourceLocation = 1
)

// String returns the ComponentResourceLocation constant's name, or its numeric form when
// the value is not a known constant.
func (e ComponentResourceLocation) String() string {
	switch e {
	case ComponentResourceLocationApplication:
		return "ComponentResourceLocationApplication"
	case ComponentResourceLocationNested:
		return "ComponentResourceLocationNested"
	default:
		return fmt.Sprintf("ComponentResourceLocation(%d)", int32(e))
	}
}

// EdgeTransitionLocation is Windows.UI.Xaml.Controls.Primitives.EdgeTransitionLocation.
type EdgeTransitionLocation int32

const (
	EdgeTransitionLocationLeft   EdgeTransitionLocation = 0
	EdgeTransitionLocationTop    EdgeTransitionLocation = 1
	EdgeTransitionLocationRight  EdgeTransitionLocation = 2
	EdgeTransitionLocationBottom EdgeTransitionLocation = 3
)

// String returns the EdgeTransitionLocation constant's name, or its numeric form when
// the value is not a known constant.
func (e EdgeTransitionLocation) String() string {
	switch e {
	case EdgeTransitionLocationLeft:
		return "EdgeTransitionLocationLeft"
	case EdgeTransitionLocationTop:
		return "EdgeTransitionLocationTop"
	case EdgeTransitionLocationRight:
		return "EdgeTransitionLocationRight"
	case EdgeTransitionLocationBottom:
		return "EdgeTransitionLocationBottom"
	default:
		return fmt.Sprintf("EdgeTransitionLocation(%d)", int32(e))
	}
}

// FlyoutPlacementMode is Windows.UI.Xaml.Controls.Primitives.FlyoutPlacementMode.
type FlyoutPlacementMode int32

const (
	FlyoutPlacementModeTop                    FlyoutPlacementMode = 0
	FlyoutPlacementModeBottom                 FlyoutPlacementMode = 1
	FlyoutPlacementModeLeft                   FlyoutPlacementMode = 2
	FlyoutPlacementModeRight                  FlyoutPlacementMode = 3
	FlyoutPlacementModeFull                   FlyoutPlacementMode = 4
	FlyoutPlacementModeTopEdgeAlignedLeft     FlyoutPlacementMode = 5
	FlyoutPlacementModeTopEdgeAlignedRight    FlyoutPlacementMode = 6
	FlyoutPlacementModeBottomEdgeAlignedLeft  FlyoutPlacementMode = 7
	FlyoutPlacementModeBottomEdgeAlignedRight FlyoutPlacementMode = 8
	FlyoutPlacementModeLeftEdgeAlignedTop     FlyoutPlacementMode = 9
	FlyoutPlacementModeLeftEdgeAlignedBottom  FlyoutPlacementMode = 10
	FlyoutPlacementModeRightEdgeAlignedTop    FlyoutPlacementMode = 11
	FlyoutPlacementModeRightEdgeAlignedBottom FlyoutPlacementMode = 12
	FlyoutPlacementModeAuto                   FlyoutPlacementMode = 13
)

// String returns the FlyoutPlacementMode constant's name, or its numeric form when
// the value is not a known constant.
func (e FlyoutPlacementMode) String() string {
	switch e {
	case FlyoutPlacementModeTop:
		return "FlyoutPlacementModeTop"
	case FlyoutPlacementModeBottom:
		return "FlyoutPlacementModeBottom"
	case FlyoutPlacementModeLeft:
		return "FlyoutPlacementModeLeft"
	case FlyoutPlacementModeRight:
		return "FlyoutPlacementModeRight"
	case FlyoutPlacementModeFull:
		return "FlyoutPlacementModeFull"
	case FlyoutPlacementModeTopEdgeAlignedLeft:
		return "FlyoutPlacementModeTopEdgeAlignedLeft"
	case FlyoutPlacementModeTopEdgeAlignedRight:
		return "FlyoutPlacementModeTopEdgeAlignedRight"
	case FlyoutPlacementModeBottomEdgeAlignedLeft:
		return "FlyoutPlacementModeBottomEdgeAlignedLeft"
	case FlyoutPlacementModeBottomEdgeAlignedRight:
		return "FlyoutPlacementModeBottomEdgeAlignedRight"
	case FlyoutPlacementModeLeftEdgeAlignedTop:
		return "FlyoutPlacementModeLeftEdgeAlignedTop"
	case FlyoutPlacementModeLeftEdgeAlignedBottom:
		return "FlyoutPlacementModeLeftEdgeAlignedBottom"
	case FlyoutPlacementModeRightEdgeAlignedTop:
		return "FlyoutPlacementModeRightEdgeAlignedTop"
	case FlyoutPlacementModeRightEdgeAlignedBottom:
		return "FlyoutPlacementModeRightEdgeAlignedBottom"
	case FlyoutPlacementModeAuto:
		return "FlyoutPlacementModeAuto"
	default:
		return fmt.Sprintf("FlyoutPlacementMode(%d)", int32(e))
	}
}

// FlyoutShowMode is Windows.UI.Xaml.Controls.Primitives.FlyoutShowMode.
type FlyoutShowMode int32

const (
	FlyoutShowModeAuto                                  FlyoutShowMode = 0
	FlyoutShowModeStandard                              FlyoutShowMode = 1
	FlyoutShowModeTransient                             FlyoutShowMode = 2
	FlyoutShowModeTransientWithDismissOnPointerMoveAway FlyoutShowMode = 3
)

// String returns the FlyoutShowMode constant's name, or its numeric form when
// the value is not a known constant.
func (e FlyoutShowMode) String() string {
	switch e {
	case FlyoutShowModeAuto:
		return "FlyoutShowModeAuto"
	case FlyoutShowModeStandard:
		return "FlyoutShowModeStandard"
	case FlyoutShowModeTransient:
		return "FlyoutShowModeTransient"
	case FlyoutShowModeTransientWithDismissOnPointerMoveAway:
		return "FlyoutShowModeTransientWithDismissOnPointerMoveAway"
	default:
		return fmt.Sprintf("FlyoutShowMode(%d)", int32(e))
	}
}

// GeneratorDirection is Windows.UI.Xaml.Controls.Primitives.GeneratorDirection.
type GeneratorDirection int32

const (
	GeneratorDirectionForward  GeneratorDirection = 0
	GeneratorDirectionBackward GeneratorDirection = 1
)

// String returns the GeneratorDirection constant's name, or its numeric form when
// the value is not a known constant.
func (e GeneratorDirection) String() string {
	switch e {
	case GeneratorDirectionForward:
		return "GeneratorDirectionForward"
	case GeneratorDirectionBackward:
		return "GeneratorDirectionBackward"
	default:
		return fmt.Sprintf("GeneratorDirection(%d)", int32(e))
	}
}

// GroupHeaderPlacement is Windows.UI.Xaml.Controls.Primitives.GroupHeaderPlacement.
type GroupHeaderPlacement int32

const (
	GroupHeaderPlacementTop  GroupHeaderPlacement = 0
	GroupHeaderPlacementLeft GroupHeaderPlacement = 1
)

// String returns the GroupHeaderPlacement constant's name, or its numeric form when
// the value is not a known constant.
func (e GroupHeaderPlacement) String() string {
	switch e {
	case GroupHeaderPlacementTop:
		return "GroupHeaderPlacementTop"
	case GroupHeaderPlacementLeft:
		return "GroupHeaderPlacementLeft"
	default:
		return fmt.Sprintf("GroupHeaderPlacement(%d)", int32(e))
	}
}

// ListViewItemPresenterCheckMode is Windows.UI.Xaml.Controls.Primitives.ListViewItemPresenterCheckMode.
type ListViewItemPresenterCheckMode int32

const (
	ListViewItemPresenterCheckModeInline  ListViewItemPresenterCheckMode = 0
	ListViewItemPresenterCheckModeOverlay ListViewItemPresenterCheckMode = 1
)

// String returns the ListViewItemPresenterCheckMode constant's name, or its numeric form when
// the value is not a known constant.
func (e ListViewItemPresenterCheckMode) String() string {
	switch e {
	case ListViewItemPresenterCheckModeInline:
		return "ListViewItemPresenterCheckModeInline"
	case ListViewItemPresenterCheckModeOverlay:
		return "ListViewItemPresenterCheckModeOverlay"
	default:
		return fmt.Sprintf("ListViewItemPresenterCheckMode(%d)", int32(e))
	}
}

// ListViewItemPresenterSelectionIndicatorMode is Windows.UI.Xaml.Controls.Primitives.ListViewItemPresenterSelectionIndicatorMode.
type ListViewItemPresenterSelectionIndicatorMode int32

const (
	ListViewItemPresenterSelectionIndicatorModeInline  ListViewItemPresenterSelectionIndicatorMode = 0
	ListViewItemPresenterSelectionIndicatorModeOverlay ListViewItemPresenterSelectionIndicatorMode = 1
)

// String returns the ListViewItemPresenterSelectionIndicatorMode constant's name, or its numeric form when
// the value is not a known constant.
func (e ListViewItemPresenterSelectionIndicatorMode) String() string {
	switch e {
	case ListViewItemPresenterSelectionIndicatorModeInline:
		return "ListViewItemPresenterSelectionIndicatorModeInline"
	case ListViewItemPresenterSelectionIndicatorModeOverlay:
		return "ListViewItemPresenterSelectionIndicatorModeOverlay"
	default:
		return fmt.Sprintf("ListViewItemPresenterSelectionIndicatorMode(%d)", int32(e))
	}
}

// PlacementMode is Windows.UI.Xaml.Controls.Primitives.PlacementMode.
type PlacementMode int32

const (
	PlacementModeBottom PlacementMode = 2
	PlacementModeLeft   PlacementMode = 9
	PlacementModeMouse  PlacementMode = 7
	PlacementModeRight  PlacementMode = 4
	PlacementModeTop    PlacementMode = 10
)

// String returns the PlacementMode constant's name, or its numeric form when
// the value is not a known constant.
func (e PlacementMode) String() string {
	switch e {
	case PlacementModeBottom:
		return "PlacementModeBottom"
	case PlacementModeLeft:
		return "PlacementModeLeft"
	case PlacementModeMouse:
		return "PlacementModeMouse"
	case PlacementModeRight:
		return "PlacementModeRight"
	case PlacementModeTop:
		return "PlacementModeTop"
	default:
		return fmt.Sprintf("PlacementMode(%d)", int32(e))
	}
}

// PopupPlacementMode is Windows.UI.Xaml.Controls.Primitives.PopupPlacementMode.
type PopupPlacementMode int32

const (
	PopupPlacementModeAuto                   PopupPlacementMode = 0
	PopupPlacementModeTop                    PopupPlacementMode = 1
	PopupPlacementModeBottom                 PopupPlacementMode = 2
	PopupPlacementModeLeft                   PopupPlacementMode = 3
	PopupPlacementModeRight                  PopupPlacementMode = 4
	PopupPlacementModeTopEdgeAlignedLeft     PopupPlacementMode = 5
	PopupPlacementModeTopEdgeAlignedRight    PopupPlacementMode = 6
	PopupPlacementModeBottomEdgeAlignedLeft  PopupPlacementMode = 7
	PopupPlacementModeBottomEdgeAlignedRight PopupPlacementMode = 8
	PopupPlacementModeLeftEdgeAlignedTop     PopupPlacementMode = 9
	PopupPlacementModeLeftEdgeAlignedBottom  PopupPlacementMode = 10
	PopupPlacementModeRightEdgeAlignedTop    PopupPlacementMode = 11
	PopupPlacementModeRightEdgeAlignedBottom PopupPlacementMode = 12
)

// String returns the PopupPlacementMode constant's name, or its numeric form when
// the value is not a known constant.
func (e PopupPlacementMode) String() string {
	switch e {
	case PopupPlacementModeAuto:
		return "PopupPlacementModeAuto"
	case PopupPlacementModeTop:
		return "PopupPlacementModeTop"
	case PopupPlacementModeBottom:
		return "PopupPlacementModeBottom"
	case PopupPlacementModeLeft:
		return "PopupPlacementModeLeft"
	case PopupPlacementModeRight:
		return "PopupPlacementModeRight"
	case PopupPlacementModeTopEdgeAlignedLeft:
		return "PopupPlacementModeTopEdgeAlignedLeft"
	case PopupPlacementModeTopEdgeAlignedRight:
		return "PopupPlacementModeTopEdgeAlignedRight"
	case PopupPlacementModeBottomEdgeAlignedLeft:
		return "PopupPlacementModeBottomEdgeAlignedLeft"
	case PopupPlacementModeBottomEdgeAlignedRight:
		return "PopupPlacementModeBottomEdgeAlignedRight"
	case PopupPlacementModeLeftEdgeAlignedTop:
		return "PopupPlacementModeLeftEdgeAlignedTop"
	case PopupPlacementModeLeftEdgeAlignedBottom:
		return "PopupPlacementModeLeftEdgeAlignedBottom"
	case PopupPlacementModeRightEdgeAlignedTop:
		return "PopupPlacementModeRightEdgeAlignedTop"
	case PopupPlacementModeRightEdgeAlignedBottom:
		return "PopupPlacementModeRightEdgeAlignedBottom"
	default:
		return fmt.Sprintf("PopupPlacementMode(%d)", int32(e))
	}
}

// ScrollEventType is Windows.UI.Xaml.Controls.Primitives.ScrollEventType.
type ScrollEventType int32

const (
	ScrollEventTypeSmallDecrement ScrollEventType = 0
	ScrollEventTypeSmallIncrement ScrollEventType = 1
	ScrollEventTypeLargeDecrement ScrollEventType = 2
	ScrollEventTypeLargeIncrement ScrollEventType = 3
	ScrollEventTypeThumbPosition  ScrollEventType = 4
	ScrollEventTypeThumbTrack     ScrollEventType = 5
	ScrollEventTypeFirst          ScrollEventType = 6
	ScrollEventTypeLast           ScrollEventType = 7
	ScrollEventTypeEndScroll      ScrollEventType = 8
)

// String returns the ScrollEventType constant's name, or its numeric form when
// the value is not a known constant.
func (e ScrollEventType) String() string {
	switch e {
	case ScrollEventTypeSmallDecrement:
		return "ScrollEventTypeSmallDecrement"
	case ScrollEventTypeSmallIncrement:
		return "ScrollEventTypeSmallIncrement"
	case ScrollEventTypeLargeDecrement:
		return "ScrollEventTypeLargeDecrement"
	case ScrollEventTypeLargeIncrement:
		return "ScrollEventTypeLargeIncrement"
	case ScrollEventTypeThumbPosition:
		return "ScrollEventTypeThumbPosition"
	case ScrollEventTypeThumbTrack:
		return "ScrollEventTypeThumbTrack"
	case ScrollEventTypeFirst:
		return "ScrollEventTypeFirst"
	case ScrollEventTypeLast:
		return "ScrollEventTypeLast"
	case ScrollEventTypeEndScroll:
		return "ScrollEventTypeEndScroll"
	default:
		return fmt.Sprintf("ScrollEventType(%d)", int32(e))
	}
}

// ScrollingIndicatorMode is Windows.UI.Xaml.Controls.Primitives.ScrollingIndicatorMode.
type ScrollingIndicatorMode int32

const (
	ScrollingIndicatorModeNone           ScrollingIndicatorMode = 0
	ScrollingIndicatorModeTouchIndicator ScrollingIndicatorMode = 1
	ScrollingIndicatorModeMouseIndicator ScrollingIndicatorMode = 2
)

// String returns the ScrollingIndicatorMode constant's name, or its numeric form when
// the value is not a known constant.
func (e ScrollingIndicatorMode) String() string {
	switch e {
	case ScrollingIndicatorModeNone:
		return "ScrollingIndicatorModeNone"
	case ScrollingIndicatorModeTouchIndicator:
		return "ScrollingIndicatorModeTouchIndicator"
	case ScrollingIndicatorModeMouseIndicator:
		return "ScrollingIndicatorModeMouseIndicator"
	default:
		return fmt.Sprintf("ScrollingIndicatorMode(%d)", int32(e))
	}
}

// SliderSnapsTo is Windows.UI.Xaml.Controls.Primitives.SliderSnapsTo.
type SliderSnapsTo int32

const (
	SliderSnapsToStepValues SliderSnapsTo = 0
	SliderSnapsToTicks      SliderSnapsTo = 1
)

// String returns the SliderSnapsTo constant's name, or its numeric form when
// the value is not a known constant.
func (e SliderSnapsTo) String() string {
	switch e {
	case SliderSnapsToStepValues:
		return "SliderSnapsToStepValues"
	case SliderSnapsToTicks:
		return "SliderSnapsToTicks"
	default:
		return fmt.Sprintf("SliderSnapsTo(%d)", int32(e))
	}
}

// SnapPointsAlignment is Windows.UI.Xaml.Controls.Primitives.SnapPointsAlignment.
type SnapPointsAlignment int32

const (
	SnapPointsAlignmentNear   SnapPointsAlignment = 0
	SnapPointsAlignmentCenter SnapPointsAlignment = 1
	SnapPointsAlignmentFar    SnapPointsAlignment = 2
)

// String returns the SnapPointsAlignment constant's name, or its numeric form when
// the value is not a known constant.
func (e SnapPointsAlignment) String() string {
	switch e {
	case SnapPointsAlignmentNear:
		return "SnapPointsAlignmentNear"
	case SnapPointsAlignmentCenter:
		return "SnapPointsAlignmentCenter"
	case SnapPointsAlignmentFar:
		return "SnapPointsAlignmentFar"
	default:
		return fmt.Sprintf("SnapPointsAlignment(%d)", int32(e))
	}
}

// TickPlacement is Windows.UI.Xaml.Controls.Primitives.TickPlacement.
type TickPlacement int32

const (
	TickPlacementNone        TickPlacement = 0
	TickPlacementTopLeft     TickPlacement = 1
	TickPlacementBottomRight TickPlacement = 2
	TickPlacementOutside     TickPlacement = 3
	TickPlacementInline      TickPlacement = 4
)

// String returns the TickPlacement constant's name, or its numeric form when
// the value is not a known constant.
func (e TickPlacement) String() string {
	switch e {
	case TickPlacementNone:
		return "TickPlacementNone"
	case TickPlacementTopLeft:
		return "TickPlacementTopLeft"
	case TickPlacementBottomRight:
		return "TickPlacementBottomRight"
	case TickPlacementOutside:
		return "TickPlacementOutside"
	case TickPlacementInline:
		return "TickPlacementInline"
	default:
		return fmt.Sprintf("TickPlacement(%d)", int32(e))
	}
}
