// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

// Package dialprotocol binds the Windows.Media.DialProtocol WinRT API surface.
package dialprotocol
