// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package preview

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
)

// AsyncOperationCompletedHandlerOfBool is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Bool>.
// IID: c1d3d1a2-ae17-5a5f-b5a2-bdcc8844889a
type AsyncOperationCompletedHandlerOfBool struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfBool is the delegate identifier for AsyncOperationCompletedHandlerOfBool.
var IID_AsyncOperationCompletedHandlerOfBool = win32.GUID{Data1: 0xc1d3d1a2, Data2: 0xae17, Data3: 0x5a5f, Data4: [8]byte{0xb5, 0xa2, 0xbd, 0xcc, 0x88, 0x44, 0x88, 0x9a}}

// NewAsyncOperationCompletedHandlerOfBool wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Bool>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfBool(fn func(asyncInfo *IAsyncOperationOfBool, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfBool, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfBool, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfBool)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfBool{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfBool) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfBool) Close() { h.delegate.Release() }

// TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeDeviceWatcherPreview, Windows.Devices.Input.Preview.GazeDeviceWatcherAddedPreviewEventArgs>.
// IID: 5bf95725-6889-544f-ba3b-dda986add8ae
type TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs is the delegate identifier for TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs.
var IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs = win32.GUID{Data1: 0x5bf95725, Data2: 0x6889, Data3: 0x544f, Data4: [8]byte{0xba, 0x3b, 0xdd, 0xa9, 0x86, 0xad, 0xd8, 0xae}}

// NewTypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeDeviceWatcherPreview, Windows.Devices.Input.Preview.GazeDeviceWatcherAddedPreviewEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs(fn func(sender *IGazeDeviceWatcherPreview, args *IGazeDeviceWatcherAddedPreviewEventArgs)) (*TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IGazeDeviceWatcherPreview)(unsafe.Pointer(raw[0])), (*IGazeDeviceWatcherAddedPreviewEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherAddedPreviewEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeDeviceWatcherPreview, Windows.Devices.Input.Preview.GazeDeviceWatcherRemovedPreviewEventArgs>.
// IID: 06c67a46-34b3-53fe-86df-ceb52e2d12e7
type TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs is the delegate identifier for TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs.
var IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs = win32.GUID{Data1: 0x06c67a46, Data2: 0x34b3, Data3: 0x53fe, Data4: [8]byte{0x86, 0xdf, 0xce, 0xb5, 0x2e, 0x2d, 0x12, 0xe7}}

// NewTypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeDeviceWatcherPreview, Windows.Devices.Input.Preview.GazeDeviceWatcherRemovedPreviewEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs(fn func(sender *IGazeDeviceWatcherPreview, args *IGazeDeviceWatcherRemovedPreviewEventArgs)) (*TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IGazeDeviceWatcherPreview)(unsafe.Pointer(raw[0])), (*IGazeDeviceWatcherRemovedPreviewEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherRemovedPreviewEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeDeviceWatcherPreview, Windows.Devices.Input.Preview.GazeDeviceWatcherUpdatedPreviewEventArgs>.
// IID: fe8090ac-7d5d-50a7-a3d3-f311648a7b89
type TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs is the delegate identifier for TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs.
var IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs = win32.GUID{Data1: 0xfe8090ac, Data2: 0x7d5d, Data3: 0x50a7, Data4: [8]byte{0xa3, 0xd3, 0xf3, 0x11, 0x64, 0x8a, 0x7b, 0x89}}

// NewTypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeDeviceWatcherPreview, Windows.Devices.Input.Preview.GazeDeviceWatcherUpdatedPreviewEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs(fn func(sender *IGazeDeviceWatcherPreview, args *IGazeDeviceWatcherUpdatedPreviewEventArgs)) (*TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IGazeDeviceWatcherPreview)(unsafe.Pointer(raw[0])), (*IGazeDeviceWatcherUpdatedPreviewEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfGazeDeviceWatcherPreviewAndGazeDeviceWatcherUpdatedPreviewEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfGazeDeviceWatcherPreviewAndObject is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeDeviceWatcherPreview, Object>.
// IID: 73a19afb-6081-551b-bf73-d5d23155da8e
type TypedEventHandlerOfGazeDeviceWatcherPreviewAndObject struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndObject is the delegate identifier for TypedEventHandlerOfGazeDeviceWatcherPreviewAndObject.
var IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndObject = win32.GUID{Data1: 0x73a19afb, Data2: 0x6081, Data3: 0x551b, Data4: [8]byte{0xbf, 0x73, 0xd5, 0xd2, 0x31, 0x55, 0xda, 0x8e}}

// NewTypedEventHandlerOfGazeDeviceWatcherPreviewAndObject wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeDeviceWatcherPreview, Object>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfGazeDeviceWatcherPreviewAndObject(fn func(sender *IGazeDeviceWatcherPreview, args *syswinrt.IInspectable)) (*TypedEventHandlerOfGazeDeviceWatcherPreviewAndObject, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfGazeDeviceWatcherPreviewAndObject, 2, func(raw []uintptr) uintptr {
		fn((*IGazeDeviceWatcherPreview)(unsafe.Pointer(raw[0])), (*syswinrt.IInspectable)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfGazeDeviceWatcherPreviewAndObject{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfGazeDeviceWatcherPreviewAndObject) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfGazeDeviceWatcherPreviewAndObject) Close() { h.delegate.Release() }

// TypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeInputSourcePreview, Windows.Devices.Input.Preview.GazeEnteredPreviewEventArgs>.
// IID: 3876b9c5-36a0-5221-be04-4aeefb9870b2
type TypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs is the delegate identifier for TypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs.
var IID_TypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs = win32.GUID{Data1: 0x3876b9c5, Data2: 0x36a0, Data3: 0x5221, Data4: [8]byte{0xbe, 0x04, 0x4a, 0xee, 0xfb, 0x98, 0x70, 0xb2}}

// NewTypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeInputSourcePreview, Windows.Devices.Input.Preview.GazeEnteredPreviewEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs(fn func(sender *IGazeInputSourcePreview, args *IGazeEnteredPreviewEventArgs)) (*TypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IGazeInputSourcePreview)(unsafe.Pointer(raw[0])), (*IGazeEnteredPreviewEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfGazeInputSourcePreviewAndGazeEnteredPreviewEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeInputSourcePreview, Windows.Devices.Input.Preview.GazeExitedPreviewEventArgs>.
// IID: 0f19b16c-73d9-5775-92a3-0f6f942e4eb0
type TypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs is the delegate identifier for TypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs.
var IID_TypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs = win32.GUID{Data1: 0x0f19b16c, Data2: 0x73d9, Data3: 0x5775, Data4: [8]byte{0x92, 0xa3, 0x0f, 0x6f, 0x94, 0x2e, 0x4e, 0xb0}}

// NewTypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeInputSourcePreview, Windows.Devices.Input.Preview.GazeExitedPreviewEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs(fn func(sender *IGazeInputSourcePreview, args *IGazeExitedPreviewEventArgs)) (*TypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IGazeInputSourcePreview)(unsafe.Pointer(raw[0])), (*IGazeExitedPreviewEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfGazeInputSourcePreviewAndGazeExitedPreviewEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeInputSourcePreview, Windows.Devices.Input.Preview.GazeMovedPreviewEventArgs>.
// IID: e7c08e8f-1aba-5952-af5c-d3a2707f4fe4
type TypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs is the delegate identifier for TypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs.
var IID_TypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs = win32.GUID{Data1: 0xe7c08e8f, Data2: 0x1aba, Data3: 0x5952, Data4: [8]byte{0xaf, 0x5c, 0xd3, 0xa2, 0x70, 0x7f, 0x4f, 0xe4}}

// NewTypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Input.Preview.GazeInputSourcePreview, Windows.Devices.Input.Preview.GazeMovedPreviewEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs(fn func(sender *IGazeInputSourcePreview, args *IGazeMovedPreviewEventArgs)) (*TypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*IGazeInputSourcePreview)(unsafe.Pointer(raw[0])), (*IGazeMovedPreviewEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfGazeInputSourcePreviewAndGazeMovedPreviewEventArgs) Close() {
	h.delegate.Release()
}
