// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package holographic

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	applicationmodelactivation "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/applicationmodel/activation"
)

// IHolographicApplicationPreviewStatics is the WinRT interface Windows.ApplicationModel.Preview.Holographic.IHolographicApplicationPreviewStatics.
// IID: fe038691-2a3a-45a9-a208-7bed691919f3
// Exclusive to the Windows.ApplicationModel.Preview.Holographic.HolographicApplicationPreview runtime class.
type IHolographicApplicationPreviewStatics struct {
	syswinrt.IInspectable
}

// IID_IHolographicApplicationPreviewStatics is the interface identifier for IHolographicApplicationPreviewStatics.
var IID_IHolographicApplicationPreviewStatics = win32.GUID{Data1: 0xfe038691, Data2: 0x2a3a, Data3: 0x45a9, Data4: [8]byte{0xa2, 0x08, 0x7b, 0xed, 0x69, 0x19, 0x19, 0xf3}}

// IsCurrentViewPresentedOnHolographicDisplay dispatches through IHolographicApplicationPreviewStatics's vtable slot 6.
func (self *IHolographicApplicationPreviewStatics) IsCurrentViewPresentedOnHolographicDisplay() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// IsHolographicActivation dispatches through IHolographicApplicationPreviewStatics's vtable slot 7.
func (self *IHolographicApplicationPreviewStatics) IsHolographicActivation(activatedEventArgs *applicationmodelactivation.IActivatedEventArgs) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(activatedEventArgs)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// IHolographicKeyboardPlacementOverridePreview is the WinRT interface Windows.ApplicationModel.Preview.Holographic.IHolographicKeyboardPlacementOverridePreview.
// IID: c8a8ce3a-dfde-5a14-8d5f-182c526dd9c4
// Exclusive to the Windows.ApplicationModel.Preview.Holographic.HolographicKeyboardPlacementOverridePreview runtime class.
type IHolographicKeyboardPlacementOverridePreview struct {
	syswinrt.IInspectable
}

// IID_IHolographicKeyboardPlacementOverridePreview is the interface identifier for IHolographicKeyboardPlacementOverridePreview.
var IID_IHolographicKeyboardPlacementOverridePreview = win32.GUID{Data1: 0xc8a8ce3a, Data2: 0xdfde, Data3: 0x5a14, Data4: [8]byte{0x8d, 0x5f, 0x18, 0x2c, 0x52, 0x6d, 0xd9, 0xc4}}

// slot 6: SetPlacementOverride skipped: by-value Windows.Foundation.Numerics.Vector3 parameter topCenterPosition does not flatten to one integer word

// slot 7: SetPlacementOverride skipped: by-value Windows.Foundation.Numerics.Vector3 parameter topCenterPosition does not flatten to one integer word

// ResetPlacementOverride dispatches through IHolographicKeyboardPlacementOverridePreview's vtable slot 8.
func (self *IHolographicKeyboardPlacementOverridePreview) ResetPlacementOverride() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// IHolographicKeyboardPlacementOverridePreviewStatics is the WinRT interface Windows.ApplicationModel.Preview.Holographic.IHolographicKeyboardPlacementOverridePreviewStatics.
// IID: 202e6039-1ff6-5a06-aac4-a5e24fa3ec4b
// Exclusive to the Windows.ApplicationModel.Preview.Holographic.HolographicKeyboardPlacementOverridePreview runtime class.
type IHolographicKeyboardPlacementOverridePreviewStatics struct {
	syswinrt.IInspectable
}

// IID_IHolographicKeyboardPlacementOverridePreviewStatics is the interface identifier for IHolographicKeyboardPlacementOverridePreviewStatics.
var IID_IHolographicKeyboardPlacementOverridePreviewStatics = win32.GUID{Data1: 0x202e6039, Data2: 0x1ff6, Data3: 0x5a06, Data4: [8]byte{0xaa, 0xc4, 0xa5, 0xe2, 0x4f, 0xa3, 0xec, 0x4b}}

// GetForCurrentView dispatches through IHolographicKeyboardPlacementOverridePreviewStatics's vtable slot 6.
func (self *IHolographicKeyboardPlacementOverridePreviewStatics) GetForCurrentView() (*IHolographicKeyboardPlacementOverridePreview, error) {
	result := new(*IHolographicKeyboardPlacementOverridePreview)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
