// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package collation

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// ICharacterGrouping is the WinRT interface Windows.Globalization.Collation.ICharacterGrouping.
// IID: fae761bb-805d-4bb0-95bb-c1f7c3e8eb8e
// Exclusive to the Windows.Globalization.Collation.CharacterGrouping runtime class.
type ICharacterGrouping struct {
	syswinrt.IInspectable
}

// IID_ICharacterGrouping is the interface identifier for ICharacterGrouping.
var IID_ICharacterGrouping = win32.GUID{Data1: 0xfae761bb, Data2: 0x805d, Data3: 0x4bb0, Data4: [8]byte{0x95, 0xbb, 0xc1, 0xf7, 0xc3, 0xe8, 0xeb, 0x8e}}

// First (propget get_First) dispatches through ICharacterGrouping's vtable slot 6.
func (self *ICharacterGrouping) First() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Label (propget get_Label) dispatches through ICharacterGrouping's vtable slot 7.
func (self *ICharacterGrouping) Label() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// ICharacterGroupings is the WinRT interface Windows.Globalization.Collation.ICharacterGroupings.
// IID: b8d20a75-d4cf-4055-80e5-ce169c226496
// Exclusive to the Windows.Globalization.Collation.CharacterGroupings runtime class.
// Requires: Windows.Foundation.Collections.IVectorView`1<Windows.Globalization.Collation.CharacterGrouping>, Windows.Foundation.Collections.IIterable`1<Windows.Globalization.Collation.CharacterGrouping>.
type ICharacterGroupings struct {
	syswinrt.IInspectable
}

// IID_ICharacterGroupings is the interface identifier for ICharacterGroupings.
var IID_ICharacterGroupings = win32.GUID{Data1: 0xb8d20a75, Data2: 0xd4cf, Data3: 0x4055, Data4: [8]byte{0x80, 0xe5, 0xce, 0x16, 0x9c, 0x22, 0x64, 0x96}}

// Lookup dispatches through ICharacterGroupings's vtable slot 6.
func (self *ICharacterGroupings) Lookup(text string) (string, error) {
	hText, err := winrt.NewHString(text)
	if err != nil {
		return "", err
	}
	defer hText.Close()
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hText.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// ICharacterGroupingsFactory is the WinRT interface Windows.Globalization.Collation.ICharacterGroupingsFactory.
// IID: 99ea9fd9-886d-4401-9f98-69c82d4c2f78
// Exclusive to the Windows.Globalization.Collation.CharacterGroupings runtime class.
type ICharacterGroupingsFactory struct {
	syswinrt.IInspectable
}

// IID_ICharacterGroupingsFactory is the interface identifier for ICharacterGroupingsFactory.
var IID_ICharacterGroupingsFactory = win32.GUID{Data1: 0x99ea9fd9, Data2: 0x886d, Data3: 0x4401, Data4: [8]byte{0x9f, 0x98, 0x69, 0xc8, 0x2d, 0x4c, 0x2f, 0x78}}

// Create dispatches through ICharacterGroupingsFactory's vtable slot 6.
func (self *ICharacterGroupingsFactory) Create(language string) (*ICharacterGroupings, error) {
	hLanguage, err := winrt.NewHString(language)
	if err != nil {
		return nil, err
	}
	defer hLanguage.Close()
	result := new(*ICharacterGroupings)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hLanguage.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
