// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package geofencing

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// TypedEventHandlerOfGeofenceMonitorAndObject is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Geolocation.Geofencing.GeofenceMonitor, Object>.
// IID: ecc5af2c-e47a-59ce-86be-9c3066fe26f7
type TypedEventHandlerOfGeofenceMonitorAndObject struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfGeofenceMonitorAndObject is the delegate identifier for TypedEventHandlerOfGeofenceMonitorAndObject.
var IID_TypedEventHandlerOfGeofenceMonitorAndObject = win32.GUID{Data1: 0xecc5af2c, Data2: 0xe47a, Data3: 0x59ce, Data4: [8]byte{0x86, 0xbe, 0x9c, 0x30, 0x66, 0xfe, 0x26, 0xf7}}

// NewTypedEventHandlerOfGeofenceMonitorAndObject wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Geolocation.Geofencing.GeofenceMonitor, Object>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfGeofenceMonitorAndObject(fn func(sender *IGeofenceMonitor, args *syswinrt.IInspectable)) (*TypedEventHandlerOfGeofenceMonitorAndObject, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfGeofenceMonitorAndObject, 2, func(raw []uintptr) uintptr {
		fn((*IGeofenceMonitor)(unsafe.Pointer(raw[0])), (*syswinrt.IInspectable)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfGeofenceMonitorAndObject{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfGeofenceMonitorAndObject) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfGeofenceMonitorAndObject) Close() { h.delegate.Release() }
