// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package geofencing

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// IVectorOfGeofence is the WinRT interface Windows.Foundation.Collections.IVector`1<Windows.Devices.Geolocation.Geofencing.Geofence>.
// IID: 096dc936-5f66-5c6e-95ce-ef5541fbf4c4
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Devices.Geolocation.Geofencing.Geofence>.
type IVectorOfGeofence struct {
	syswinrt.IInspectable
}

// IID_IVectorOfGeofence is the interface identifier for IVectorOfGeofence.
var IID_IVectorOfGeofence = win32.GUID{Data1: 0x096dc936, Data2: 0x5f66, Data3: 0x5c6e, Data4: [8]byte{0x95, 0xce, 0xef, 0x55, 0x41, 0xfb, 0xf4, 0xc4}}

// GetAt dispatches through IVectorOfGeofence's vtable slot 6.
func (self *IVectorOfGeofence) GetAt(index uint32) (*IGeofence, error) {
	result := new(*IGeofence)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorOfGeofence's vtable slot 7.
func (self *IVectorOfGeofence) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IVectorOfGeofence's vtable slot 8.
func (self *IVectorOfGeofence) GetView() (*IVectorViewOfGeofence, error) {
	result := new(*IVectorViewOfGeofence)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorOfGeofence's vtable slot 9.
func (self *IVectorOfGeofence) IndexOf(value *IGeofence, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetAt dispatches through IVectorOfGeofence's vtable slot 10.
func (self *IVectorOfGeofence) SetAt(index uint32, value *IGeofence) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// InsertAt dispatches through IVectorOfGeofence's vtable slot 11.
func (self *IVectorOfGeofence) InsertAt(index uint32, value *IGeofence) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAt dispatches through IVectorOfGeofence's vtable slot 12.
func (self *IVectorOfGeofence) RemoveAt(index uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(index))
	return win32.ErrIfFailed(int32(r1))
}

// Append dispatches through IVectorOfGeofence's vtable slot 13.
func (self *IVectorOfGeofence) Append(value *IGeofence) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAtEnd dispatches through IVectorOfGeofence's vtable slot 14.
func (self *IVectorOfGeofence) RemoveAtEnd() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IVectorOfGeofence's vtable slot 15.
func (self *IVectorOfGeofence) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// slot 16: GetMany skipped: conformant array

// slot 17: ReplaceAll skipped: conformant array

// IVectorViewOfGeofence is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Geolocation.Geofencing.Geofence>.
// IID: d8039aca-1a45-5d13-8cfd-4900c22b8ef1
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Devices.Geolocation.Geofencing.Geofence>.
type IVectorViewOfGeofence struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfGeofence is the interface identifier for IVectorViewOfGeofence.
var IID_IVectorViewOfGeofence = win32.GUID{Data1: 0xd8039aca, Data2: 0x1a45, Data3: 0x5d13, Data4: [8]byte{0x8c, 0xfd, 0x49, 0x00, 0xc2, 0x2b, 0x8e, 0xf1}}

// GetAt dispatches through IVectorViewOfGeofence's vtable slot 6.
func (self *IVectorViewOfGeofence) GetAt(index uint32) (*IGeofence, error) {
	result := new(*IGeofence)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfGeofence's vtable slot 7.
func (self *IVectorViewOfGeofence) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfGeofence's vtable slot 8.
func (self *IVectorViewOfGeofence) IndexOf(value *IGeofence, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// IVectorViewOfGeofenceStateChangeReport is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Geolocation.Geofencing.GeofenceStateChangeReport>.
// IID: ea91593d-ecf4-5041-86f2-837a282c4d94
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Devices.Geolocation.Geofencing.GeofenceStateChangeReport>.
type IVectorViewOfGeofenceStateChangeReport struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfGeofenceStateChangeReport is the interface identifier for IVectorViewOfGeofenceStateChangeReport.
var IID_IVectorViewOfGeofenceStateChangeReport = win32.GUID{Data1: 0xea91593d, Data2: 0xecf4, Data3: 0x5041, Data4: [8]byte{0x86, 0xf2, 0x83, 0x7a, 0x28, 0x2c, 0x4d, 0x94}}

// GetAt dispatches through IVectorViewOfGeofenceStateChangeReport's vtable slot 6.
func (self *IVectorViewOfGeofenceStateChangeReport) GetAt(index uint32) (*IGeofenceStateChangeReport, error) {
	result := new(*IGeofenceStateChangeReport)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfGeofenceStateChangeReport's vtable slot 7.
func (self *IVectorViewOfGeofenceStateChangeReport) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfGeofenceStateChangeReport's vtable slot 8.
func (self *IVectorViewOfGeofenceStateChangeReport) IndexOf(value *IGeofenceStateChangeReport, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array
