// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package syndication

import (
	"fmt"
)

// SyndicationErrorStatus is Windows.Web.Syndication.SyndicationErrorStatus.
type SyndicationErrorStatus int32

const (
	SyndicationErrorStatusUnknown                  SyndicationErrorStatus = 0
	SyndicationErrorStatusMissingRequiredElement   SyndicationErrorStatus = 1
	SyndicationErrorStatusMissingRequiredAttribute SyndicationErrorStatus = 2
	SyndicationErrorStatusInvalidXml               SyndicationErrorStatus = 3
	SyndicationErrorStatusUnexpectedContent        SyndicationErrorStatus = 4
	SyndicationErrorStatusUnsupportedFormat        SyndicationErrorStatus = 5
)

// String returns the SyndicationErrorStatus constant's name, or its numeric form when
// the value is not a known constant.
func (e SyndicationErrorStatus) String() string {
	switch e {
	case SyndicationErrorStatusUnknown:
		return "SyndicationErrorStatusUnknown"
	case SyndicationErrorStatusMissingRequiredElement:
		return "SyndicationErrorStatusMissingRequiredElement"
	case SyndicationErrorStatusMissingRequiredAttribute:
		return "SyndicationErrorStatusMissingRequiredAttribute"
	case SyndicationErrorStatusInvalidXml:
		return "SyndicationErrorStatusInvalidXml"
	case SyndicationErrorStatusUnexpectedContent:
		return "SyndicationErrorStatusUnexpectedContent"
	case SyndicationErrorStatusUnsupportedFormat:
		return "SyndicationErrorStatusUnsupportedFormat"
	default:
		return fmt.Sprintf("SyndicationErrorStatus(%d)", int32(e))
	}
}

// SyndicationFormat is Windows.Web.Syndication.SyndicationFormat.
type SyndicationFormat int32

const (
	SyndicationFormatAtom10 SyndicationFormat = 0
	SyndicationFormatRss20  SyndicationFormat = 1
	SyndicationFormatRss10  SyndicationFormat = 2
	SyndicationFormatRss092 SyndicationFormat = 3
	SyndicationFormatRss091 SyndicationFormat = 4
	SyndicationFormatAtom03 SyndicationFormat = 5
)

// String returns the SyndicationFormat constant's name, or its numeric form when
// the value is not a known constant.
func (e SyndicationFormat) String() string {
	switch e {
	case SyndicationFormatAtom10:
		return "SyndicationFormatAtom10"
	case SyndicationFormatRss20:
		return "SyndicationFormatRss20"
	case SyndicationFormatRss10:
		return "SyndicationFormatRss10"
	case SyndicationFormatRss092:
		return "SyndicationFormatRss092"
	case SyndicationFormatRss091:
		return "SyndicationFormatRss091"
	case SyndicationFormatAtom03:
		return "SyndicationFormatAtom03"
	default:
		return fmt.Sprintf("SyndicationFormat(%d)", int32(e))
	}
}

// SyndicationTextType is Windows.Web.Syndication.SyndicationTextType.
type SyndicationTextType int32

const (
	SyndicationTextTypeText  SyndicationTextType = 0
	SyndicationTextTypeHtml  SyndicationTextType = 1
	SyndicationTextTypeXhtml SyndicationTextType = 2
)

// String returns the SyndicationTextType constant's name, or its numeric form when
// the value is not a known constant.
func (e SyndicationTextType) String() string {
	switch e {
	case SyndicationTextTypeText:
		return "SyndicationTextTypeText"
	case SyndicationTextTypeHtml:
		return "SyndicationTextTypeHtml"
	case SyndicationTextTypeXhtml:
		return "SyndicationTextTypeXhtml"
	default:
		return fmt.Sprintf("SyndicationTextType(%d)", int32(e))
	}
}
