// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package shell

import (
	"fmt"
)

// ShareWindowCommand is Windows.UI.Shell.ShareWindowCommand.
type ShareWindowCommand int32

const (
	ShareWindowCommandNone         ShareWindowCommand = 0
	ShareWindowCommandStartSharing ShareWindowCommand = 1
	ShareWindowCommandStopSharing  ShareWindowCommand = 2
)

// String returns the ShareWindowCommand constant's name, or its numeric form when
// the value is not a known constant.
func (e ShareWindowCommand) String() string {
	switch e {
	case ShareWindowCommandNone:
		return "ShareWindowCommandNone"
	case ShareWindowCommandStartSharing:
		return "ShareWindowCommandStartSharing"
	case ShareWindowCommandStopSharing:
		return "ShareWindowCommandStopSharing"
	default:
		return fmt.Sprintf("ShareWindowCommand(%d)", int32(e))
	}
}
