// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package foundation

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// Deferral is the Windows.Foundation.Deferral runtime class, surfaced through its
// default interface IDeferral. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Deferral struct {
	IDeferral
}

// AsClosable queries the instance's IClosable interface.
// The returned reference is owned by the caller.
func (self *Deferral) AsClosable() (*IClosable, error) {
	return winrt.QueryInterface[IClosable](unsafe.Pointer(self), &IID_IClosable)
}

// MemoryBuffer is the Windows.Foundation.MemoryBuffer runtime class, surfaced through its
// default interface IMemoryBuffer. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type MemoryBuffer struct {
	IMemoryBuffer
}

// AsClosable queries the instance's IClosable interface.
// The returned reference is owned by the caller.
func (self *MemoryBuffer) AsClosable() (*IClosable, error) {
	return winrt.QueryInterface[IClosable](unsafe.Pointer(self), &IID_IClosable)
}

// Uri is the Windows.Foundation.Uri runtime class, surfaced through its
// default interface IUriRuntimeClass. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Uri struct {
	IUriRuntimeClass
}

// AsUriRuntimeClassWithAbsoluteCanonicalUri queries the instance's IUriRuntimeClassWithAbsoluteCanonicalUri interface.
// The returned reference is owned by the caller.
func (self *Uri) AsUriRuntimeClassWithAbsoluteCanonicalUri() (*IUriRuntimeClassWithAbsoluteCanonicalUri, error) {
	return winrt.QueryInterface[IUriRuntimeClassWithAbsoluteCanonicalUri](unsafe.Pointer(self), &IID_IUriRuntimeClassWithAbsoluteCanonicalUri)
}

// AsStringable queries the instance's IStringable interface.
// The returned reference is owned by the caller.
func (self *Uri) AsStringable() (*IStringable, error) {
	return winrt.QueryInterface[IStringable](unsafe.Pointer(self), &IID_IStringable)
}

// WwwFormUrlDecoder is the Windows.Foundation.WwwFormUrlDecoder runtime class, surfaced through its
// default interface IWwwFormUrlDecoderRuntimeClass. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type WwwFormUrlDecoder struct {
	IWwwFormUrlDecoderRuntimeClass
}

// WwwFormUrlDecoderEntry is the Windows.Foundation.WwwFormUrlDecoderEntry runtime class, surfaced through its
// default interface IWwwFormUrlDecoderEntry. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type WwwFormUrlDecoderEntry struct {
	IWwwFormUrlDecoderEntry
}
