// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package core

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	uiinputinking "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/ui/input/inking"
)

// IIterableOfInkPoint is the WinRT interface Windows.Foundation.Collections.IIterable`1<Windows.UI.Input.Inking.InkPoint>.
// IID: 0630c0ef-a4e2-5af6-b2e9-8e042e294e17
type IIterableOfInkPoint struct {
	syswinrt.IInspectable
}

// IID_IIterableOfInkPoint is the interface identifier for IIterableOfInkPoint.
var IID_IIterableOfInkPoint = win32.GUID{Data1: 0x0630c0ef, Data2: 0xa4e2, Data3: 0x5af6, Data4: [8]byte{0xb2, 0xe9, 0x8e, 0x04, 0x2e, 0x29, 0x4e, 0x17}}

// First dispatches through IIterableOfInkPoint's vtable slot 6.
func (self *IIterableOfInkPoint) First() (*IIteratorOfInkPoint, error) {
	result := new(*IIteratorOfInkPoint)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IIteratorOfInkPoint is the WinRT interface Windows.Foundation.Collections.IIterator`1<Windows.UI.Input.Inking.InkPoint>.
// IID: 47415452-db79-567e-84d5-e9912330f944
type IIteratorOfInkPoint struct {
	syswinrt.IInspectable
}

// IID_IIteratorOfInkPoint is the interface identifier for IIteratorOfInkPoint.
var IID_IIteratorOfInkPoint = win32.GUID{Data1: 0x47415452, Data2: 0xdb79, Data3: 0x567e, Data4: [8]byte{0x84, 0xd5, 0xe9, 0x91, 0x23, 0x30, 0xf9, 0x44}}

// Current (propget get_Current) dispatches through IIteratorOfInkPoint's vtable slot 6.
func (self *IIteratorOfInkPoint) Current() (*uiinputinking.IInkPoint, error) {
	result := new(*uiinputinking.IInkPoint)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// HasCurrent (propget get_HasCurrent) dispatches through IIteratorOfInkPoint's vtable slot 7.
func (self *IIteratorOfInkPoint) HasCurrent() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// MoveNext dispatches through IIteratorOfInkPoint's vtable slot 8.
func (self *IIteratorOfInkPoint) MoveNext() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// IVectorOfInkPoint is the WinRT interface Windows.Foundation.Collections.IVector`1<Windows.UI.Input.Inking.InkPoint>.
// IID: 10c47202-47ab-58bc-91de-d5000f1a74c0
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.UI.Input.Inking.InkPoint>.
type IVectorOfInkPoint struct {
	syswinrt.IInspectable
}

// IID_IVectorOfInkPoint is the interface identifier for IVectorOfInkPoint.
var IID_IVectorOfInkPoint = win32.GUID{Data1: 0x10c47202, Data2: 0x47ab, Data3: 0x58bc, Data4: [8]byte{0x91, 0xde, 0xd5, 0x00, 0x0f, 0x1a, 0x74, 0xc0}}

// GetAt dispatches through IVectorOfInkPoint's vtable slot 6.
func (self *IVectorOfInkPoint) GetAt(index uint32) (*uiinputinking.IInkPoint, error) {
	result := new(*uiinputinking.IInkPoint)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorOfInkPoint's vtable slot 7.
func (self *IVectorOfInkPoint) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IVectorOfInkPoint's vtable slot 8.
func (self *IVectorOfInkPoint) GetView() (*IVectorViewOfInkPoint, error) {
	result := new(*IVectorViewOfInkPoint)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorOfInkPoint's vtable slot 9.
func (self *IVectorOfInkPoint) IndexOf(value *uiinputinking.IInkPoint, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetAt dispatches through IVectorOfInkPoint's vtable slot 10.
func (self *IVectorOfInkPoint) SetAt(index uint32, value *uiinputinking.IInkPoint) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// InsertAt dispatches through IVectorOfInkPoint's vtable slot 11.
func (self *IVectorOfInkPoint) InsertAt(index uint32, value *uiinputinking.IInkPoint) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAt dispatches through IVectorOfInkPoint's vtable slot 12.
func (self *IVectorOfInkPoint) RemoveAt(index uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(index))
	return win32.ErrIfFailed(int32(r1))
}

// Append dispatches through IVectorOfInkPoint's vtable slot 13.
func (self *IVectorOfInkPoint) Append(value *uiinputinking.IInkPoint) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAtEnd dispatches through IVectorOfInkPoint's vtable slot 14.
func (self *IVectorOfInkPoint) RemoveAtEnd() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IVectorOfInkPoint's vtable slot 15.
func (self *IVectorOfInkPoint) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// slot 16: GetMany skipped: conformant array

// slot 17: ReplaceAll skipped: conformant array

// IVectorViewOfInkPoint is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Windows.UI.Input.Inking.InkPoint>.
// IID: d1ac414b-c87d-540f-8ab1-4e0d09d9d283
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.UI.Input.Inking.InkPoint>.
type IVectorViewOfInkPoint struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfInkPoint is the interface identifier for IVectorViewOfInkPoint.
var IID_IVectorViewOfInkPoint = win32.GUID{Data1: 0xd1ac414b, Data2: 0xc87d, Data3: 0x540f, Data4: [8]byte{0x8a, 0xb1, 0x4e, 0x0d, 0x09, 0xd9, 0xd2, 0x83}}

// GetAt dispatches through IVectorViewOfInkPoint's vtable slot 6.
func (self *IVectorViewOfInkPoint) GetAt(index uint32) (*uiinputinking.IInkPoint, error) {
	result := new(*uiinputinking.IInkPoint)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfInkPoint's vtable slot 7.
func (self *IVectorViewOfInkPoint) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfInkPoint's vtable slot 8.
func (self *IVectorViewOfInkPoint) IndexOf(value *uiinputinking.IInkPoint, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array
