// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package automation

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// AnnotationPatternIdentifiers is the Windows.UI.Xaml.Automation.AnnotationPatternIdentifiers runtime class, surfaced through its
// default interface IAnnotationPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type AnnotationPatternIdentifiers struct {
	IAnnotationPatternIdentifiers
}

// AnnotationPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IAnnotationPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.AnnotationPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AnnotationPatternIdentifiersStatics() (*IAnnotationPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AnnotationPatternIdentifiers", &IID_IAnnotationPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IAnnotationPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// AutomationElementIdentifiers is the Windows.UI.Xaml.Automation.AutomationElementIdentifiers runtime class, surfaced through its
// default interface IAutomationElementIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type AutomationElementIdentifiers struct {
	IAutomationElementIdentifiers
}

// AutomationElementIdentifiersStatics returns the Windows.UI.Xaml.Automation.IAutomationElementIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.AutomationElementIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationElementIdentifiersStatics() (*IAutomationElementIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationElementIdentifiers", &IID_IAutomationElementIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IAutomationElementIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// AutomationElementIdentifiersStatics2 returns the Windows.UI.Xaml.Automation.IAutomationElementIdentifiersStatics2 statics of the
// Windows.UI.Xaml.Automation.AutomationElementIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationElementIdentifiersStatics2() (*IAutomationElementIdentifiersStatics2, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationElementIdentifiers", &IID_IAutomationElementIdentifiersStatics2)
	if err != nil {
		return nil, err
	}
	return (*IAutomationElementIdentifiersStatics2)(unsafe.Pointer(factory)), nil
}

// AutomationElementIdentifiersStatics3 returns the Windows.UI.Xaml.Automation.IAutomationElementIdentifiersStatics3 statics of the
// Windows.UI.Xaml.Automation.AutomationElementIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationElementIdentifiersStatics3() (*IAutomationElementIdentifiersStatics3, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationElementIdentifiers", &IID_IAutomationElementIdentifiersStatics3)
	if err != nil {
		return nil, err
	}
	return (*IAutomationElementIdentifiersStatics3)(unsafe.Pointer(factory)), nil
}

// AutomationElementIdentifiersStatics4 returns the Windows.UI.Xaml.Automation.IAutomationElementIdentifiersStatics4 statics of the
// Windows.UI.Xaml.Automation.AutomationElementIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationElementIdentifiersStatics4() (*IAutomationElementIdentifiersStatics4, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationElementIdentifiers", &IID_IAutomationElementIdentifiersStatics4)
	if err != nil {
		return nil, err
	}
	return (*IAutomationElementIdentifiersStatics4)(unsafe.Pointer(factory)), nil
}

// AutomationElementIdentifiersStatics5 returns the Windows.UI.Xaml.Automation.IAutomationElementIdentifiersStatics5 statics of the
// Windows.UI.Xaml.Automation.AutomationElementIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationElementIdentifiersStatics5() (*IAutomationElementIdentifiersStatics5, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationElementIdentifiers", &IID_IAutomationElementIdentifiersStatics5)
	if err != nil {
		return nil, err
	}
	return (*IAutomationElementIdentifiersStatics5)(unsafe.Pointer(factory)), nil
}

// AutomationElementIdentifiersStatics6 returns the Windows.UI.Xaml.Automation.IAutomationElementIdentifiersStatics6 statics of the
// Windows.UI.Xaml.Automation.AutomationElementIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationElementIdentifiersStatics6() (*IAutomationElementIdentifiersStatics6, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationElementIdentifiers", &IID_IAutomationElementIdentifiersStatics6)
	if err != nil {
		return nil, err
	}
	return (*IAutomationElementIdentifiersStatics6)(unsafe.Pointer(factory)), nil
}

// AutomationElementIdentifiersStatics7 returns the Windows.UI.Xaml.Automation.IAutomationElementIdentifiersStatics7 statics of the
// Windows.UI.Xaml.Automation.AutomationElementIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationElementIdentifiersStatics7() (*IAutomationElementIdentifiersStatics7, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationElementIdentifiers", &IID_IAutomationElementIdentifiersStatics7)
	if err != nil {
		return nil, err
	}
	return (*IAutomationElementIdentifiersStatics7)(unsafe.Pointer(factory)), nil
}

// AutomationElementIdentifiersStatics8 returns the Windows.UI.Xaml.Automation.IAutomationElementIdentifiersStatics8 statics of the
// Windows.UI.Xaml.Automation.AutomationElementIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationElementIdentifiersStatics8() (*IAutomationElementIdentifiersStatics8, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationElementIdentifiers", &IID_IAutomationElementIdentifiersStatics8)
	if err != nil {
		return nil, err
	}
	return (*IAutomationElementIdentifiersStatics8)(unsafe.Pointer(factory)), nil
}

// AutomationProperties is the Windows.UI.Xaml.Automation.AutomationProperties runtime class, surfaced through its
// default interface IAutomationProperties. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type AutomationProperties struct {
	IAutomationProperties
}

// AutomationPropertiesStatics returns the Windows.UI.Xaml.Automation.IAutomationPropertiesStatics statics of the
// Windows.UI.Xaml.Automation.AutomationProperties runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationPropertiesStatics() (*IAutomationPropertiesStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationProperties", &IID_IAutomationPropertiesStatics)
	if err != nil {
		return nil, err
	}
	return (*IAutomationPropertiesStatics)(unsafe.Pointer(factory)), nil
}

// AutomationPropertiesStatics2 returns the Windows.UI.Xaml.Automation.IAutomationPropertiesStatics2 statics of the
// Windows.UI.Xaml.Automation.AutomationProperties runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationPropertiesStatics2() (*IAutomationPropertiesStatics2, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationProperties", &IID_IAutomationPropertiesStatics2)
	if err != nil {
		return nil, err
	}
	return (*IAutomationPropertiesStatics2)(unsafe.Pointer(factory)), nil
}

// AutomationPropertiesStatics3 returns the Windows.UI.Xaml.Automation.IAutomationPropertiesStatics3 statics of the
// Windows.UI.Xaml.Automation.AutomationProperties runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationPropertiesStatics3() (*IAutomationPropertiesStatics3, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationProperties", &IID_IAutomationPropertiesStatics3)
	if err != nil {
		return nil, err
	}
	return (*IAutomationPropertiesStatics3)(unsafe.Pointer(factory)), nil
}

// AutomationPropertiesStatics4 returns the Windows.UI.Xaml.Automation.IAutomationPropertiesStatics4 statics of the
// Windows.UI.Xaml.Automation.AutomationProperties runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationPropertiesStatics4() (*IAutomationPropertiesStatics4, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationProperties", &IID_IAutomationPropertiesStatics4)
	if err != nil {
		return nil, err
	}
	return (*IAutomationPropertiesStatics4)(unsafe.Pointer(factory)), nil
}

// AutomationPropertiesStatics5 returns the Windows.UI.Xaml.Automation.IAutomationPropertiesStatics5 statics of the
// Windows.UI.Xaml.Automation.AutomationProperties runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationPropertiesStatics5() (*IAutomationPropertiesStatics5, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationProperties", &IID_IAutomationPropertiesStatics5)
	if err != nil {
		return nil, err
	}
	return (*IAutomationPropertiesStatics5)(unsafe.Pointer(factory)), nil
}

// AutomationPropertiesStatics6 returns the Windows.UI.Xaml.Automation.IAutomationPropertiesStatics6 statics of the
// Windows.UI.Xaml.Automation.AutomationProperties runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationPropertiesStatics6() (*IAutomationPropertiesStatics6, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationProperties", &IID_IAutomationPropertiesStatics6)
	if err != nil {
		return nil, err
	}
	return (*IAutomationPropertiesStatics6)(unsafe.Pointer(factory)), nil
}

// AutomationPropertiesStatics7 returns the Windows.UI.Xaml.Automation.IAutomationPropertiesStatics7 statics of the
// Windows.UI.Xaml.Automation.AutomationProperties runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationPropertiesStatics7() (*IAutomationPropertiesStatics7, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationProperties", &IID_IAutomationPropertiesStatics7)
	if err != nil {
		return nil, err
	}
	return (*IAutomationPropertiesStatics7)(unsafe.Pointer(factory)), nil
}

// AutomationPropertiesStatics8 returns the Windows.UI.Xaml.Automation.IAutomationPropertiesStatics8 statics of the
// Windows.UI.Xaml.Automation.AutomationProperties runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationPropertiesStatics8() (*IAutomationPropertiesStatics8, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationProperties", &IID_IAutomationPropertiesStatics8)
	if err != nil {
		return nil, err
	}
	return (*IAutomationPropertiesStatics8)(unsafe.Pointer(factory)), nil
}

// AutomationPropertiesStatics9 returns the Windows.UI.Xaml.Automation.IAutomationPropertiesStatics9 statics of the
// Windows.UI.Xaml.Automation.AutomationProperties runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func AutomationPropertiesStatics9() (*IAutomationPropertiesStatics9, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.AutomationProperties", &IID_IAutomationPropertiesStatics9)
	if err != nil {
		return nil, err
	}
	return (*IAutomationPropertiesStatics9)(unsafe.Pointer(factory)), nil
}

// AutomationProperty is the Windows.UI.Xaml.Automation.AutomationProperty runtime class, surfaced through its
// default interface IAutomationProperty. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type AutomationProperty struct {
	IAutomationProperty
}

// DockPatternIdentifiers is the Windows.UI.Xaml.Automation.DockPatternIdentifiers runtime class, surfaced through its
// default interface IDockPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type DockPatternIdentifiers struct {
	IDockPatternIdentifiers
}

// DockPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IDockPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.DockPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func DockPatternIdentifiersStatics() (*IDockPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.DockPatternIdentifiers", &IID_IDockPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IDockPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// DragPatternIdentifiers is the Windows.UI.Xaml.Automation.DragPatternIdentifiers runtime class, surfaced through its
// default interface IDragPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type DragPatternIdentifiers struct {
	IDragPatternIdentifiers
}

// DragPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IDragPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.DragPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func DragPatternIdentifiersStatics() (*IDragPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.DragPatternIdentifiers", &IID_IDragPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IDragPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// DropTargetPatternIdentifiers is the Windows.UI.Xaml.Automation.DropTargetPatternIdentifiers runtime class, surfaced through its
// default interface IDropTargetPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type DropTargetPatternIdentifiers struct {
	IDropTargetPatternIdentifiers
}

// DropTargetPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IDropTargetPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.DropTargetPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func DropTargetPatternIdentifiersStatics() (*IDropTargetPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.DropTargetPatternIdentifiers", &IID_IDropTargetPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IDropTargetPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// ExpandCollapsePatternIdentifiers is the Windows.UI.Xaml.Automation.ExpandCollapsePatternIdentifiers runtime class, surfaced through its
// default interface IExpandCollapsePatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type ExpandCollapsePatternIdentifiers struct {
	IExpandCollapsePatternIdentifiers
}

// ExpandCollapsePatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IExpandCollapsePatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.ExpandCollapsePatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func ExpandCollapsePatternIdentifiersStatics() (*IExpandCollapsePatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.ExpandCollapsePatternIdentifiers", &IID_IExpandCollapsePatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IExpandCollapsePatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// GridItemPatternIdentifiers is the Windows.UI.Xaml.Automation.GridItemPatternIdentifiers runtime class, surfaced through its
// default interface IGridItemPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type GridItemPatternIdentifiers struct {
	IGridItemPatternIdentifiers
}

// GridItemPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IGridItemPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.GridItemPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func GridItemPatternIdentifiersStatics() (*IGridItemPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.GridItemPatternIdentifiers", &IID_IGridItemPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IGridItemPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// GridPatternIdentifiers is the Windows.UI.Xaml.Automation.GridPatternIdentifiers runtime class, surfaced through its
// default interface IGridPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type GridPatternIdentifiers struct {
	IGridPatternIdentifiers
}

// GridPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IGridPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.GridPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func GridPatternIdentifiersStatics() (*IGridPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.GridPatternIdentifiers", &IID_IGridPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IGridPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// MultipleViewPatternIdentifiers is the Windows.UI.Xaml.Automation.MultipleViewPatternIdentifiers runtime class, surfaced through its
// default interface IMultipleViewPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type MultipleViewPatternIdentifiers struct {
	IMultipleViewPatternIdentifiers
}

// MultipleViewPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IMultipleViewPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.MultipleViewPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func MultipleViewPatternIdentifiersStatics() (*IMultipleViewPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.MultipleViewPatternIdentifiers", &IID_IMultipleViewPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IMultipleViewPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// RangeValuePatternIdentifiers is the Windows.UI.Xaml.Automation.RangeValuePatternIdentifiers runtime class, surfaced through its
// default interface IRangeValuePatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type RangeValuePatternIdentifiers struct {
	IRangeValuePatternIdentifiers
}

// RangeValuePatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IRangeValuePatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.RangeValuePatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func RangeValuePatternIdentifiersStatics() (*IRangeValuePatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.RangeValuePatternIdentifiers", &IID_IRangeValuePatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IRangeValuePatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// ScrollPatternIdentifiers is the Windows.UI.Xaml.Automation.ScrollPatternIdentifiers runtime class, surfaced through its
// default interface IScrollPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type ScrollPatternIdentifiers struct {
	IScrollPatternIdentifiers
}

// ScrollPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IScrollPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.ScrollPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func ScrollPatternIdentifiersStatics() (*IScrollPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.ScrollPatternIdentifiers", &IID_IScrollPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IScrollPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// SelectionItemPatternIdentifiers is the Windows.UI.Xaml.Automation.SelectionItemPatternIdentifiers runtime class, surfaced through its
// default interface ISelectionItemPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SelectionItemPatternIdentifiers struct {
	ISelectionItemPatternIdentifiers
}

// SelectionItemPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.ISelectionItemPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.SelectionItemPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func SelectionItemPatternIdentifiersStatics() (*ISelectionItemPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.SelectionItemPatternIdentifiers", &IID_ISelectionItemPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*ISelectionItemPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// SelectionPatternIdentifiers is the Windows.UI.Xaml.Automation.SelectionPatternIdentifiers runtime class, surfaced through its
// default interface ISelectionPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SelectionPatternIdentifiers struct {
	ISelectionPatternIdentifiers
}

// SelectionPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.ISelectionPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.SelectionPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func SelectionPatternIdentifiersStatics() (*ISelectionPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.SelectionPatternIdentifiers", &IID_ISelectionPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*ISelectionPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// SpreadsheetItemPatternIdentifiers is the Windows.UI.Xaml.Automation.SpreadsheetItemPatternIdentifiers runtime class, surfaced through its
// default interface ISpreadsheetItemPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SpreadsheetItemPatternIdentifiers struct {
	ISpreadsheetItemPatternIdentifiers
}

// SpreadsheetItemPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.ISpreadsheetItemPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.SpreadsheetItemPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func SpreadsheetItemPatternIdentifiersStatics() (*ISpreadsheetItemPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.SpreadsheetItemPatternIdentifiers", &IID_ISpreadsheetItemPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*ISpreadsheetItemPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// StylesPatternIdentifiers is the Windows.UI.Xaml.Automation.StylesPatternIdentifiers runtime class, surfaced through its
// default interface IStylesPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type StylesPatternIdentifiers struct {
	IStylesPatternIdentifiers
}

// StylesPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IStylesPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.StylesPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func StylesPatternIdentifiersStatics() (*IStylesPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.StylesPatternIdentifiers", &IID_IStylesPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IStylesPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// TableItemPatternIdentifiers is the Windows.UI.Xaml.Automation.TableItemPatternIdentifiers runtime class, surfaced through its
// default interface ITableItemPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type TableItemPatternIdentifiers struct {
	ITableItemPatternIdentifiers
}

// TableItemPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.ITableItemPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.TableItemPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func TableItemPatternIdentifiersStatics() (*ITableItemPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.TableItemPatternIdentifiers", &IID_ITableItemPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*ITableItemPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// TablePatternIdentifiers is the Windows.UI.Xaml.Automation.TablePatternIdentifiers runtime class, surfaced through its
// default interface ITablePatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type TablePatternIdentifiers struct {
	ITablePatternIdentifiers
}

// TablePatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.ITablePatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.TablePatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func TablePatternIdentifiersStatics() (*ITablePatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.TablePatternIdentifiers", &IID_ITablePatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*ITablePatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// TogglePatternIdentifiers is the Windows.UI.Xaml.Automation.TogglePatternIdentifiers runtime class, surfaced through its
// default interface ITogglePatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type TogglePatternIdentifiers struct {
	ITogglePatternIdentifiers
}

// TogglePatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.ITogglePatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.TogglePatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func TogglePatternIdentifiersStatics() (*ITogglePatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.TogglePatternIdentifiers", &IID_ITogglePatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*ITogglePatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// TransformPattern2Identifiers is the Windows.UI.Xaml.Automation.TransformPattern2Identifiers runtime class, surfaced through its
// default interface ITransformPattern2Identifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type TransformPattern2Identifiers struct {
	ITransformPattern2Identifiers
}

// TransformPattern2IdentifiersStatics returns the Windows.UI.Xaml.Automation.ITransformPattern2IdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.TransformPattern2Identifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func TransformPattern2IdentifiersStatics() (*ITransformPattern2IdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.TransformPattern2Identifiers", &IID_ITransformPattern2IdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*ITransformPattern2IdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// TransformPatternIdentifiers is the Windows.UI.Xaml.Automation.TransformPatternIdentifiers runtime class, surfaced through its
// default interface ITransformPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type TransformPatternIdentifiers struct {
	ITransformPatternIdentifiers
}

// TransformPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.ITransformPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.TransformPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func TransformPatternIdentifiersStatics() (*ITransformPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.TransformPatternIdentifiers", &IID_ITransformPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*ITransformPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// ValuePatternIdentifiers is the Windows.UI.Xaml.Automation.ValuePatternIdentifiers runtime class, surfaced through its
// default interface IValuePatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type ValuePatternIdentifiers struct {
	IValuePatternIdentifiers
}

// ValuePatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IValuePatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.ValuePatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func ValuePatternIdentifiersStatics() (*IValuePatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.ValuePatternIdentifiers", &IID_IValuePatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IValuePatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}

// WindowPatternIdentifiers is the Windows.UI.Xaml.Automation.WindowPatternIdentifiers runtime class, surfaced through its
// default interface IWindowPatternIdentifiers. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type WindowPatternIdentifiers struct {
	IWindowPatternIdentifiers
}

// WindowPatternIdentifiersStatics returns the Windows.UI.Xaml.Automation.IWindowPatternIdentifiersStatics statics of the
// Windows.UI.Xaml.Automation.WindowPatternIdentifiers runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func WindowPatternIdentifiersStatics() (*IWindowPatternIdentifiersStatics, error) {
	factory, err := winrt.GetActivationFactory("Windows.UI.Xaml.Automation.WindowPatternIdentifiers", &IID_IWindowPatternIdentifiersStatics)
	if err != nil {
		return nil, err
	}
	return (*IWindowPatternIdentifiersStatics)(unsafe.Pointer(factory)), nil
}
