// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package imaging

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// DownloadProgressEventArgs is the Windows.UI.Xaml.Media.Imaging.DownloadProgressEventArgs runtime class, surfaced through its
// default interface IDownloadProgressEventArgs. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type DownloadProgressEventArgs struct {
	IDownloadProgressEventArgs
}

// SvgImageSourceFailedEventArgs is the Windows.UI.Xaml.Media.Imaging.SvgImageSourceFailedEventArgs runtime class, surfaced through its
// default interface ISvgImageSourceFailedEventArgs. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SvgImageSourceFailedEventArgs struct {
	ISvgImageSourceFailedEventArgs
}

// SvgImageSourceOpenedEventArgs is the Windows.UI.Xaml.Media.Imaging.SvgImageSourceOpenedEventArgs runtime class, surfaced through its
// default interface ISvgImageSourceOpenedEventArgs. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SvgImageSourceOpenedEventArgs struct {
	ISvgImageSourceOpenedEventArgs
}

// XamlRenderingBackgroundTask is the Windows.UI.Xaml.Media.Imaging.XamlRenderingBackgroundTask runtime class, surfaced through its
// default interface IXamlRenderingBackgroundTask. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type XamlRenderingBackgroundTask struct {
	IXamlRenderingBackgroundTask
}

// AsXamlRenderingBackgroundTaskOverrides queries the instance's IXamlRenderingBackgroundTaskOverrides interface.
// The returned reference is owned by the caller.
func (self *XamlRenderingBackgroundTask) AsXamlRenderingBackgroundTaskOverrides() (*IXamlRenderingBackgroundTaskOverrides, error) {
	return winrt.QueryInterface[IXamlRenderingBackgroundTaskOverrides](unsafe.Pointer(self), &IID_IXamlRenderingBackgroundTaskOverrides)
}
