// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package provider

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// UserDataAccountPartnerAccountInfo is the Windows.ApplicationModel.UserDataAccounts.Provider.UserDataAccountPartnerAccountInfo runtime class, surfaced through its
// default interface IUserDataAccountPartnerAccountInfo. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type UserDataAccountPartnerAccountInfo struct {
	IUserDataAccountPartnerAccountInfo
}

// UserDataAccountProviderAddAccountOperation is the Windows.ApplicationModel.UserDataAccounts.Provider.UserDataAccountProviderAddAccountOperation runtime class, surfaced through its
// default interface IUserDataAccountProviderAddAccountOperation. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type UserDataAccountProviderAddAccountOperation struct {
	IUserDataAccountProviderAddAccountOperation
}

// AsUserDataAccountProviderOperation queries the instance's IUserDataAccountProviderOperation interface.
// The returned reference is owned by the caller.
func (self *UserDataAccountProviderAddAccountOperation) AsUserDataAccountProviderOperation() (*IUserDataAccountProviderOperation, error) {
	return winrt.QueryInterface[IUserDataAccountProviderOperation](unsafe.Pointer(self), &IID_IUserDataAccountProviderOperation)
}

// UserDataAccountProviderResolveErrorsOperation is the Windows.ApplicationModel.UserDataAccounts.Provider.UserDataAccountProviderResolveErrorsOperation runtime class, surfaced through its
// default interface IUserDataAccountProviderResolveErrorsOperation. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type UserDataAccountProviderResolveErrorsOperation struct {
	IUserDataAccountProviderResolveErrorsOperation
}

// AsUserDataAccountProviderOperation queries the instance's IUserDataAccountProviderOperation interface.
// The returned reference is owned by the caller.
func (self *UserDataAccountProviderResolveErrorsOperation) AsUserDataAccountProviderOperation() (*IUserDataAccountProviderOperation, error) {
	return winrt.QueryInterface[IUserDataAccountProviderOperation](unsafe.Pointer(self), &IID_IUserDataAccountProviderOperation)
}

// UserDataAccountProviderSettingsOperation is the Windows.ApplicationModel.UserDataAccounts.Provider.UserDataAccountProviderSettingsOperation runtime class, surfaced through its
// default interface IUserDataAccountProviderSettingsOperation. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type UserDataAccountProviderSettingsOperation struct {
	IUserDataAccountProviderSettingsOperation
}

// AsUserDataAccountProviderOperation queries the instance's IUserDataAccountProviderOperation interface.
// The returned reference is owned by the caller.
func (self *UserDataAccountProviderSettingsOperation) AsUserDataAccountProviderOperation() (*IUserDataAccountProviderOperation, error) {
	return winrt.QueryInterface[IUserDataAccountProviderOperation](unsafe.Pointer(self), &IID_IUserDataAccountProviderOperation)
}
