// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package maps

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	devicesgeolocation "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/devices/geolocation"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
)

// IEnhancedWaypoint is the WinRT interface Windows.Services.Maps.IEnhancedWaypoint.
// IID: ed268c74-5913-11e6-8b77-86f30ca893d3
// Exclusive to the Windows.Services.Maps.EnhancedWaypoint runtime class.
type IEnhancedWaypoint struct {
	syswinrt.IInspectable
}

// IID_IEnhancedWaypoint is the interface identifier for IEnhancedWaypoint.
var IID_IEnhancedWaypoint = win32.GUID{Data1: 0xed268c74, Data2: 0x5913, Data3: 0x11e6, Data4: [8]byte{0x8b, 0x77, 0x86, 0xf3, 0x0c, 0xa8, 0x93, 0xd3}}

// Point (propget get_Point) dispatches through IEnhancedWaypoint's vtable slot 6.
func (self *IEnhancedWaypoint) Point() (*devicesgeolocation.IGeopoint, error) {
	result := new(*devicesgeolocation.IGeopoint)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Kind (propget get_Kind) dispatches through IEnhancedWaypoint's vtable slot 7.
func (self *IEnhancedWaypoint) Kind() (WaypointKind, error) {
	result := new(WaypointKind)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IEnhancedWaypointFactory is the WinRT interface Windows.Services.Maps.IEnhancedWaypointFactory.
// IID: af868477-a2aa-46dd-b645-23b31b8aa6c7
// Exclusive to the Windows.Services.Maps.EnhancedWaypoint runtime class.
type IEnhancedWaypointFactory struct {
	syswinrt.IInspectable
}

// IID_IEnhancedWaypointFactory is the interface identifier for IEnhancedWaypointFactory.
var IID_IEnhancedWaypointFactory = win32.GUID{Data1: 0xaf868477, Data2: 0xa2aa, Data3: 0x46dd, Data4: [8]byte{0xb6, 0x45, 0x23, 0xb3, 0x1b, 0x8a, 0xa6, 0xc7}}

// Create dispatches through IEnhancedWaypointFactory's vtable slot 6.
func (self *IEnhancedWaypointFactory) Create(point *devicesgeolocation.IGeopoint, kind WaypointKind) (*IEnhancedWaypoint, error) {
	result := new(*IEnhancedWaypoint)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(point)), uintptr(kind), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IManeuverWarning is the WinRT interface Windows.Services.Maps.IManeuverWarning.
// IID: c1a36d8a-2630-4378-9e4a-6e44253dceba
// Exclusive to the Windows.Services.Maps.ManeuverWarning runtime class.
type IManeuverWarning struct {
	syswinrt.IInspectable
}

// IID_IManeuverWarning is the interface identifier for IManeuverWarning.
var IID_IManeuverWarning = win32.GUID{Data1: 0xc1a36d8a, Data2: 0x2630, Data3: 0x4378, Data4: [8]byte{0x9e, 0x4a, 0x6e, 0x44, 0x25, 0x3d, 0xce, 0xba}}

// Kind (propget get_Kind) dispatches through IManeuverWarning's vtable slot 6.
func (self *IManeuverWarning) Kind() (ManeuverWarningKind, error) {
	result := new(ManeuverWarningKind)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Severity (propget get_Severity) dispatches through IManeuverWarning's vtable slot 7.
func (self *IManeuverWarning) Severity() (ManeuverWarningSeverity, error) {
	result := new(ManeuverWarningSeverity)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapAddress is the WinRT interface Windows.Services.Maps.IMapAddress.
// IID: cfa7a973-a3b4-4494-b3ff-cba94db69699
// Exclusive to the Windows.Services.Maps.MapAddress runtime class.
type IMapAddress struct {
	syswinrt.IInspectable
}

// IID_IMapAddress is the interface identifier for IMapAddress.
var IID_IMapAddress = win32.GUID{Data1: 0xcfa7a973, Data2: 0xa3b4, Data3: 0x4494, Data4: [8]byte{0xb3, 0xff, 0xcb, 0xa9, 0x4d, 0xb6, 0x96, 0x99}}

// BuildingName (propget get_BuildingName) dispatches through IMapAddress's vtable slot 6.
func (self *IMapAddress) BuildingName() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// BuildingFloor (propget get_BuildingFloor) dispatches through IMapAddress's vtable slot 7.
func (self *IMapAddress) BuildingFloor() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// BuildingRoom (propget get_BuildingRoom) dispatches through IMapAddress's vtable slot 8.
func (self *IMapAddress) BuildingRoom() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// BuildingWing (propget get_BuildingWing) dispatches through IMapAddress's vtable slot 9.
func (self *IMapAddress) BuildingWing() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// StreetNumber (propget get_StreetNumber) dispatches through IMapAddress's vtable slot 10.
func (self *IMapAddress) StreetNumber() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Street (propget get_Street) dispatches through IMapAddress's vtable slot 11.
func (self *IMapAddress) Street() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Neighborhood (propget get_Neighborhood) dispatches through IMapAddress's vtable slot 12.
func (self *IMapAddress) Neighborhood() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// District (propget get_District) dispatches through IMapAddress's vtable slot 13.
func (self *IMapAddress) District() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Town (propget get_Town) dispatches through IMapAddress's vtable slot 14.
func (self *IMapAddress) Town() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Region (propget get_Region) dispatches through IMapAddress's vtable slot 15.
func (self *IMapAddress) Region() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// RegionCode (propget get_RegionCode) dispatches through IMapAddress's vtable slot 16.
func (self *IMapAddress) RegionCode() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[16], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Country (propget get_Country) dispatches through IMapAddress's vtable slot 17.
func (self *IMapAddress) Country() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[17], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// CountryCode (propget get_CountryCode) dispatches through IMapAddress's vtable slot 18.
func (self *IMapAddress) CountryCode() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[18], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// PostCode (propget get_PostCode) dispatches through IMapAddress's vtable slot 19.
func (self *IMapAddress) PostCode() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[19], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Continent (propget get_Continent) dispatches through IMapAddress's vtable slot 20.
func (self *IMapAddress) Continent() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[20], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IMapAddress2 is the WinRT interface Windows.Services.Maps.IMapAddress2.
// IID: 75cd6df1-e5ad-45a9-bf40-6cf256c1dd13
// Exclusive to the Windows.Services.Maps.MapAddress runtime class.
type IMapAddress2 struct {
	syswinrt.IInspectable
}

// IID_IMapAddress2 is the interface identifier for IMapAddress2.
var IID_IMapAddress2 = win32.GUID{Data1: 0x75cd6df1, Data2: 0xe5ad, Data3: 0x45a9, Data4: [8]byte{0xbf, 0x40, 0x6c, 0xf2, 0x56, 0xc1, 0xdd, 0x13}}

// FormattedAddress (propget get_FormattedAddress) dispatches through IMapAddress2's vtable slot 6.
func (self *IMapAddress2) FormattedAddress() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IMapLocation is the WinRT interface Windows.Services.Maps.IMapLocation.
// IID: 3c073f57-0da4-42e8-9ee2-a96fcf2371dc
// Exclusive to the Windows.Services.Maps.MapLocation runtime class.
type IMapLocation struct {
	syswinrt.IInspectable
}

// IID_IMapLocation is the interface identifier for IMapLocation.
var IID_IMapLocation = win32.GUID{Data1: 0x3c073f57, Data2: 0x0da4, Data3: 0x42e8, Data4: [8]byte{0x9e, 0xe2, 0xa9, 0x6f, 0xcf, 0x23, 0x71, 0xdc}}

// Point (propget get_Point) dispatches through IMapLocation's vtable slot 6.
func (self *IMapLocation) Point() (*devicesgeolocation.IGeopoint, error) {
	result := new(*devicesgeolocation.IGeopoint)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DisplayName (propget get_DisplayName) dispatches through IMapLocation's vtable slot 7.
func (self *IMapLocation) DisplayName() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Description (propget get_Description) dispatches through IMapLocation's vtable slot 8.
func (self *IMapLocation) Description() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Address (propget get_Address) dispatches through IMapLocation's vtable slot 9.
func (self *IMapLocation) Address() (*IMapAddress, error) {
	result := new(*IMapAddress)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapLocationFinderResult is the WinRT interface Windows.Services.Maps.IMapLocationFinderResult.
// IID: 43f1f179-e8cc-45f6-bed2-54ccbf965d9a
// Exclusive to the Windows.Services.Maps.MapLocationFinderResult runtime class.
type IMapLocationFinderResult struct {
	syswinrt.IInspectable
}

// IID_IMapLocationFinderResult is the interface identifier for IMapLocationFinderResult.
var IID_IMapLocationFinderResult = win32.GUID{Data1: 0x43f1f179, Data2: 0xe8cc, Data3: 0x45f6, Data4: [8]byte{0xbe, 0xd2, 0x54, 0xcc, 0xbf, 0x96, 0x5d, 0x9a}}

// Locations (propget get_Locations) dispatches through IMapLocationFinderResult's vtable slot 6.
func (self *IMapLocationFinderResult) Locations() (*IVectorViewOfMapLocation, error) {
	result := new(*IVectorViewOfMapLocation)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Status (propget get_Status) dispatches through IMapLocationFinderResult's vtable slot 7.
func (self *IMapLocationFinderResult) Status() (MapLocationFinderStatus, error) {
	result := new(MapLocationFinderStatus)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapLocationFinderStatics is the WinRT interface Windows.Services.Maps.IMapLocationFinderStatics.
// IID: 318adb5d-1c5d-4f35-a2df-aaca94959517
// Exclusive to the Windows.Services.Maps.MapLocationFinder runtime class.
type IMapLocationFinderStatics struct {
	syswinrt.IInspectable
}

// IID_IMapLocationFinderStatics is the interface identifier for IMapLocationFinderStatics.
var IID_IMapLocationFinderStatics = win32.GUID{Data1: 0x318adb5d, Data2: 0x1c5d, Data3: 0x4f35, Data4: [8]byte{0xa2, 0xdf, 0xaa, 0xca, 0x94, 0x95, 0x95, 0x17}}

// FindLocationsAtAsync dispatches through IMapLocationFinderStatics's vtable slot 6.
func (self *IMapLocationFinderStatics) FindLocationsAtAsync(queryPoint *devicesgeolocation.IGeopoint) (*IAsyncOperationOfMapLocationFinderResult, error) {
	result := new(*IAsyncOperationOfMapLocationFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(queryPoint)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// FindLocationsAsync dispatches through IMapLocationFinderStatics's vtable slot 7.
func (self *IMapLocationFinderStatics) FindLocationsAsync(searchText string, referencePoint *devicesgeolocation.IGeopoint) (*IAsyncOperationOfMapLocationFinderResult, error) {
	hSearchText, err := winrt.NewHString(searchText)
	if err != nil {
		return nil, err
	}
	defer hSearchText.Close()
	result := new(*IAsyncOperationOfMapLocationFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(hSearchText.Raw()), uintptr(unsafe.Pointer(referencePoint)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// FindLocationsWithMaxCountAsync dispatches through IMapLocationFinderStatics's vtable slot 8.
func (self *IMapLocationFinderStatics) FindLocationsWithMaxCountAsync(searchText string, referencePoint *devicesgeolocation.IGeopoint, maxCount uint32) (*IAsyncOperationOfMapLocationFinderResult, error) {
	hSearchText, err := winrt.NewHString(searchText)
	if err != nil {
		return nil, err
	}
	defer hSearchText.Close()
	result := new(*IAsyncOperationOfMapLocationFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hSearchText.Raw()), uintptr(unsafe.Pointer(referencePoint)), uintptr(maxCount), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapLocationFinderStatics2 is the WinRT interface Windows.Services.Maps.IMapLocationFinderStatics2.
// IID: 959a8b96-6485-4dfd-851a-33ac317e3af6
// Exclusive to the Windows.Services.Maps.MapLocationFinder runtime class.
type IMapLocationFinderStatics2 struct {
	syswinrt.IInspectable
}

// IID_IMapLocationFinderStatics2 is the interface identifier for IMapLocationFinderStatics2.
var IID_IMapLocationFinderStatics2 = win32.GUID{Data1: 0x959a8b96, Data2: 0x6485, Data3: 0x4dfd, Data4: [8]byte{0x85, 0x1a, 0x33, 0xac, 0x31, 0x7e, 0x3a, 0xf6}}

// FindLocationsAtWithAccuracyAsync dispatches through IMapLocationFinderStatics2's vtable slot 6.
func (self *IMapLocationFinderStatics2) FindLocationsAtWithAccuracyAsync(queryPoint *devicesgeolocation.IGeopoint, accuracy MapLocationDesiredAccuracy) (*IAsyncOperationOfMapLocationFinderResult, error) {
	result := new(*IAsyncOperationOfMapLocationFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(queryPoint)), uintptr(accuracy), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapManagerStatics is the WinRT interface Windows.Services.Maps.IMapManagerStatics.
// IID: 37e3e515-82b4-4d54-8fd9-af2624b3011c
// Exclusive to the Windows.Services.Maps.MapManager runtime class.
type IMapManagerStatics struct {
	syswinrt.IInspectable
}

// IID_IMapManagerStatics is the interface identifier for IMapManagerStatics.
var IID_IMapManagerStatics = win32.GUID{Data1: 0x37e3e515, Data2: 0x82b4, Data3: 0x4d54, Data4: [8]byte{0x8f, 0xd9, 0xaf, 0x26, 0x24, 0xb3, 0x01, 0x1c}}

// ShowDownloadedMapsUI dispatches through IMapManagerStatics's vtable slot 6.
func (self *IMapManagerStatics) ShowDownloadedMapsUI() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// ShowMapsUpdateUI dispatches through IMapManagerStatics's vtable slot 7.
func (self *IMapManagerStatics) ShowMapsUpdateUI() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// IMapRoute is the WinRT interface Windows.Services.Maps.IMapRoute.
// IID: fb07b732-584d-4583-9c60-641fea274349
// Exclusive to the Windows.Services.Maps.MapRoute runtime class.
type IMapRoute struct {
	syswinrt.IInspectable
}

// IID_IMapRoute is the interface identifier for IMapRoute.
var IID_IMapRoute = win32.GUID{Data1: 0xfb07b732, Data2: 0x584d, Data3: 0x4583, Data4: [8]byte{0x9c, 0x60, 0x64, 0x1f, 0xea, 0x27, 0x43, 0x49}}

// BoundingBox (propget get_BoundingBox) dispatches through IMapRoute's vtable slot 6.
func (self *IMapRoute) BoundingBox() (*devicesgeolocation.IGeoboundingBox, error) {
	result := new(*devicesgeolocation.IGeoboundingBox)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// slot 7: get_LengthInMeters skipped: float64 return cannot cross SyscallN

// EstimatedDuration (propget get_EstimatedDuration) dispatches through IMapRoute's vtable slot 8.
func (self *IMapRoute) EstimatedDuration() (foundation.TimeSpan, error) {
	result := new(foundation.TimeSpan)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Path (propget get_Path) dispatches through IMapRoute's vtable slot 9.
func (self *IMapRoute) Path() (*devicesgeolocation.IGeopath, error) {
	result := new(*devicesgeolocation.IGeopath)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Legs (propget get_Legs) dispatches through IMapRoute's vtable slot 10.
func (self *IMapRoute) Legs() (*IVectorViewOfMapRouteLeg, error) {
	result := new(*IVectorViewOfMapRouteLeg)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IsTrafficBased (propget get_IsTrafficBased) dispatches through IMapRoute's vtable slot 11.
func (self *IMapRoute) IsTrafficBased() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// IMapRoute2 is the WinRT interface Windows.Services.Maps.IMapRoute2.
// IID: d1c5d40c-2213-4ab0-a260-46b38169beac
// Exclusive to the Windows.Services.Maps.MapRoute runtime class.
type IMapRoute2 struct {
	syswinrt.IInspectable
}

// IID_IMapRoute2 is the interface identifier for IMapRoute2.
var IID_IMapRoute2 = win32.GUID{Data1: 0xd1c5d40c, Data2: 0x2213, Data3: 0x4ab0, Data4: [8]byte{0xa2, 0x60, 0x46, 0xb3, 0x81, 0x69, 0xbe, 0xac}}

// ViolatedRestrictions (propget get_ViolatedRestrictions) dispatches through IMapRoute2's vtable slot 6.
func (self *IMapRoute2) ViolatedRestrictions() (MapRouteRestrictions, error) {
	result := new(MapRouteRestrictions)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// HasBlockedRoads (propget get_HasBlockedRoads) dispatches through IMapRoute2's vtable slot 7.
func (self *IMapRoute2) HasBlockedRoads() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// IMapRoute3 is the WinRT interface Windows.Services.Maps.IMapRoute3.
// IID: 858d1eae-f2ad-429f-bb37-cd21094ffc92
// Exclusive to the Windows.Services.Maps.MapRoute runtime class.
type IMapRoute3 struct {
	syswinrt.IInspectable
}

// IID_IMapRoute3 is the interface identifier for IMapRoute3.
var IID_IMapRoute3 = win32.GUID{Data1: 0x858d1eae, Data2: 0xf2ad, Data3: 0x429f, Data4: [8]byte{0xbb, 0x37, 0xcd, 0x21, 0x09, 0x4f, 0xfc, 0x92}}

// DurationWithoutTraffic (propget get_DurationWithoutTraffic) dispatches through IMapRoute3's vtable slot 6.
func (self *IMapRoute3) DurationWithoutTraffic() (foundation.TimeSpan, error) {
	result := new(foundation.TimeSpan)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// TrafficCongestion (propget get_TrafficCongestion) dispatches through IMapRoute3's vtable slot 7.
func (self *IMapRoute3) TrafficCongestion() (TrafficCongestion, error) {
	result := new(TrafficCongestion)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapRoute4 is the WinRT interface Windows.Services.Maps.IMapRoute4.
// IID: 366c8ca5-3053-4fa1-80ff-d475f3ed1e6e
// Exclusive to the Windows.Services.Maps.MapRoute runtime class.
type IMapRoute4 struct {
	syswinrt.IInspectable
}

// IID_IMapRoute4 is the interface identifier for IMapRoute4.
var IID_IMapRoute4 = win32.GUID{Data1: 0x366c8ca5, Data2: 0x3053, Data3: 0x4fa1, Data4: [8]byte{0x80, 0xff, 0xd4, 0x75, 0xf3, 0xed, 0x1e, 0x6e}}

// IsScenic (propget get_IsScenic) dispatches through IMapRoute4's vtable slot 6.
func (self *IMapRoute4) IsScenic() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// IMapRouteDrivingOptions is the WinRT interface Windows.Services.Maps.IMapRouteDrivingOptions.
// IID: 6815364d-c6dc-4697-a452-b18f8f0b67a1
// Exclusive to the Windows.Services.Maps.MapRouteDrivingOptions runtime class.
type IMapRouteDrivingOptions struct {
	syswinrt.IInspectable
}

// IID_IMapRouteDrivingOptions is the interface identifier for IMapRouteDrivingOptions.
var IID_IMapRouteDrivingOptions = win32.GUID{Data1: 0x6815364d, Data2: 0xc6dc, Data3: 0x4697, Data4: [8]byte{0xa4, 0x52, 0xb1, 0x8f, 0x8f, 0x0b, 0x67, 0xa1}}

// MaxAlternateRouteCount (propget get_MaxAlternateRouteCount) dispatches through IMapRouteDrivingOptions's vtable slot 6.
func (self *IMapRouteDrivingOptions) MaxAlternateRouteCount() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetMaxAlternateRouteCount (propput put_MaxAlternateRouteCount) dispatches through IMapRouteDrivingOptions's vtable slot 7.
func (self *IMapRouteDrivingOptions) SetMaxAlternateRouteCount(value uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(value))
	return win32.ErrIfFailed(int32(r1))
}

// InitialHeading (propget get_InitialHeading) dispatches through IMapRouteDrivingOptions's vtable slot 8.
func (self *IMapRouteDrivingOptions) InitialHeading() (*IReferenceOfDouble, error) {
	result := new(*IReferenceOfDouble)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetInitialHeading (propput put_InitialHeading) dispatches through IMapRouteDrivingOptions's vtable slot 9.
func (self *IMapRouteDrivingOptions) SetInitialHeading(value *IReferenceOfDouble) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RouteOptimization (propget get_RouteOptimization) dispatches through IMapRouteDrivingOptions's vtable slot 10.
func (self *IMapRouteDrivingOptions) RouteOptimization() (MapRouteOptimization, error) {
	result := new(MapRouteOptimization)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetRouteOptimization (propput put_RouteOptimization) dispatches through IMapRouteDrivingOptions's vtable slot 11.
func (self *IMapRouteDrivingOptions) SetRouteOptimization(value MapRouteOptimization) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(value))
	return win32.ErrIfFailed(int32(r1))
}

// RouteRestrictions (propget get_RouteRestrictions) dispatches through IMapRouteDrivingOptions's vtable slot 12.
func (self *IMapRouteDrivingOptions) RouteRestrictions() (MapRouteRestrictions, error) {
	result := new(MapRouteRestrictions)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetRouteRestrictions (propput put_RouteRestrictions) dispatches through IMapRouteDrivingOptions's vtable slot 13.
func (self *IMapRouteDrivingOptions) SetRouteRestrictions(value MapRouteRestrictions) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(value))
	return win32.ErrIfFailed(int32(r1))
}

// IMapRouteDrivingOptions2 is the WinRT interface Windows.Services.Maps.IMapRouteDrivingOptions2.
// IID: 35dc8670-c298-48d0-b5ad-825460645603
// Exclusive to the Windows.Services.Maps.MapRouteDrivingOptions runtime class.
type IMapRouteDrivingOptions2 struct {
	syswinrt.IInspectable
}

// IID_IMapRouteDrivingOptions2 is the interface identifier for IMapRouteDrivingOptions2.
var IID_IMapRouteDrivingOptions2 = win32.GUID{Data1: 0x35dc8670, Data2: 0xc298, Data3: 0x48d0, Data4: [8]byte{0xb5, 0xad, 0x82, 0x54, 0x60, 0x64, 0x56, 0x03}}

// DepartureTime (propget get_DepartureTime) dispatches through IMapRouteDrivingOptions2's vtable slot 6.
func (self *IMapRouteDrivingOptions2) DepartureTime() (*IReferenceOfDateTime, error) {
	result := new(*IReferenceOfDateTime)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetDepartureTime (propput put_DepartureTime) dispatches through IMapRouteDrivingOptions2's vtable slot 7.
func (self *IMapRouteDrivingOptions2) SetDepartureTime(value *IReferenceOfDateTime) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// IMapRouteFinderResult is the WinRT interface Windows.Services.Maps.IMapRouteFinderResult.
// IID: a868a31a-9422-46ac-8ca1-b1614d4bfbe2
// Exclusive to the Windows.Services.Maps.MapRouteFinderResult runtime class.
type IMapRouteFinderResult struct {
	syswinrt.IInspectable
}

// IID_IMapRouteFinderResult is the interface identifier for IMapRouteFinderResult.
var IID_IMapRouteFinderResult = win32.GUID{Data1: 0xa868a31a, Data2: 0x9422, Data3: 0x46ac, Data4: [8]byte{0x8c, 0xa1, 0xb1, 0x61, 0x4d, 0x4b, 0xfb, 0xe2}}

// Route (propget get_Route) dispatches through IMapRouteFinderResult's vtable slot 6.
func (self *IMapRouteFinderResult) Route() (*IMapRoute, error) {
	result := new(*IMapRoute)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Status (propget get_Status) dispatches through IMapRouteFinderResult's vtable slot 7.
func (self *IMapRouteFinderResult) Status() (MapRouteFinderStatus, error) {
	result := new(MapRouteFinderStatus)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapRouteFinderResult2 is the WinRT interface Windows.Services.Maps.IMapRouteFinderResult2.
// IID: 20709c6d-d90c-46c8-91c6-7d4be4efb215
// Exclusive to the Windows.Services.Maps.MapRouteFinderResult runtime class.
type IMapRouteFinderResult2 struct {
	syswinrt.IInspectable
}

// IID_IMapRouteFinderResult2 is the interface identifier for IMapRouteFinderResult2.
var IID_IMapRouteFinderResult2 = win32.GUID{Data1: 0x20709c6d, Data2: 0xd90c, Data3: 0x46c8, Data4: [8]byte{0x91, 0xc6, 0x7d, 0x4b, 0xe4, 0xef, 0xb2, 0x15}}

// AlternateRoutes (propget get_AlternateRoutes) dispatches through IMapRouteFinderResult2's vtable slot 6.
func (self *IMapRouteFinderResult2) AlternateRoutes() (*IVectorViewOfMapRoute, error) {
	result := new(*IVectorViewOfMapRoute)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapRouteFinderStatics is the WinRT interface Windows.Services.Maps.IMapRouteFinderStatics.
// IID: b8a5c50f-1c64-4c3a-81eb-1f7c152afbbb
// Exclusive to the Windows.Services.Maps.MapRouteFinder runtime class.
type IMapRouteFinderStatics struct {
	syswinrt.IInspectable
}

// IID_IMapRouteFinderStatics is the interface identifier for IMapRouteFinderStatics.
var IID_IMapRouteFinderStatics = win32.GUID{Data1: 0xb8a5c50f, Data2: 0x1c64, Data3: 0x4c3a, Data4: [8]byte{0x81, 0xeb, 0x1f, 0x7c, 0x15, 0x2a, 0xfb, 0xbb}}

// GetDrivingRouteAsync dispatches through IMapRouteFinderStatics's vtable slot 6.
func (self *IMapRouteFinderStatics) GetDrivingRouteAsync(startPoint *devicesgeolocation.IGeopoint, endPoint *devicesgeolocation.IGeopoint) (*IAsyncOperationOfMapRouteFinderResult, error) {
	result := new(*IAsyncOperationOfMapRouteFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(startPoint)), uintptr(unsafe.Pointer(endPoint)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetDrivingRouteWithOptimizationAsync dispatches through IMapRouteFinderStatics's vtable slot 7.
func (self *IMapRouteFinderStatics) GetDrivingRouteWithOptimizationAsync(startPoint *devicesgeolocation.IGeopoint, endPoint *devicesgeolocation.IGeopoint, optimization MapRouteOptimization) (*IAsyncOperationOfMapRouteFinderResult, error) {
	result := new(*IAsyncOperationOfMapRouteFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(startPoint)), uintptr(unsafe.Pointer(endPoint)), uintptr(optimization), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetDrivingRouteWithOptimizationAndRestrictionsAsync dispatches through IMapRouteFinderStatics's vtable slot 8.
func (self *IMapRouteFinderStatics) GetDrivingRouteWithOptimizationAndRestrictionsAsync(startPoint *devicesgeolocation.IGeopoint, endPoint *devicesgeolocation.IGeopoint, optimization MapRouteOptimization, restrictions MapRouteRestrictions) (*IAsyncOperationOfMapRouteFinderResult, error) {
	result := new(*IAsyncOperationOfMapRouteFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(startPoint)), uintptr(unsafe.Pointer(endPoint)), uintptr(optimization), uintptr(restrictions), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetDrivingRouteAsync skipped: float64 parameter headingInDegrees cannot cross SyscallN

// GetDrivingRouteFromWaypointsAsync dispatches through IMapRouteFinderStatics's vtable slot 10.
func (self *IMapRouteFinderStatics) GetDrivingRouteFromWaypointsAsync(wayPoints *IIterableOfGeopoint) (*IAsyncOperationOfMapRouteFinderResult, error) {
	result := new(*IAsyncOperationOfMapRouteFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(wayPoints)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetDrivingRouteFromWaypointsAndOptimizationAsync dispatches through IMapRouteFinderStatics's vtable slot 11.
func (self *IMapRouteFinderStatics) GetDrivingRouteFromWaypointsAndOptimizationAsync(wayPoints *IIterableOfGeopoint, optimization MapRouteOptimization) (*IAsyncOperationOfMapRouteFinderResult, error) {
	result := new(*IAsyncOperationOfMapRouteFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(wayPoints)), uintptr(optimization), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetDrivingRouteFromWaypointsOptimizationAndRestrictionsAsync dispatches through IMapRouteFinderStatics's vtable slot 12.
func (self *IMapRouteFinderStatics) GetDrivingRouteFromWaypointsOptimizationAndRestrictionsAsync(wayPoints *IIterableOfGeopoint, optimization MapRouteOptimization, restrictions MapRouteRestrictions) (*IAsyncOperationOfMapRouteFinderResult, error) {
	result := new(*IAsyncOperationOfMapRouteFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(wayPoints)), uintptr(optimization), uintptr(restrictions), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// slot 13: GetDrivingRouteFromWaypointsAsync skipped: float64 parameter headingInDegrees cannot cross SyscallN

// GetWalkingRouteAsync dispatches through IMapRouteFinderStatics's vtable slot 14.
func (self *IMapRouteFinderStatics) GetWalkingRouteAsync(startPoint *devicesgeolocation.IGeopoint, endPoint *devicesgeolocation.IGeopoint) (*IAsyncOperationOfMapRouteFinderResult, error) {
	result := new(*IAsyncOperationOfMapRouteFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(startPoint)), uintptr(unsafe.Pointer(endPoint)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetWalkingRouteFromWaypointsAsync dispatches through IMapRouteFinderStatics's vtable slot 15.
func (self *IMapRouteFinderStatics) GetWalkingRouteFromWaypointsAsync(wayPoints *IIterableOfGeopoint) (*IAsyncOperationOfMapRouteFinderResult, error) {
	result := new(*IAsyncOperationOfMapRouteFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(wayPoints)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapRouteFinderStatics2 is the WinRT interface Windows.Services.Maps.IMapRouteFinderStatics2.
// IID: afcc2c73-7760-49af-b3bd-baf135b703e1
// Exclusive to the Windows.Services.Maps.MapRouteFinder runtime class.
type IMapRouteFinderStatics2 struct {
	syswinrt.IInspectable
}

// IID_IMapRouteFinderStatics2 is the interface identifier for IMapRouteFinderStatics2.
var IID_IMapRouteFinderStatics2 = win32.GUID{Data1: 0xafcc2c73, Data2: 0x7760, Data3: 0x49af, Data4: [8]byte{0xb3, 0xbd, 0xba, 0xf1, 0x35, 0xb7, 0x03, 0xe1}}

// GetDrivingRouteWithOptionsAsync dispatches through IMapRouteFinderStatics2's vtable slot 6.
func (self *IMapRouteFinderStatics2) GetDrivingRouteWithOptionsAsync(startPoint *devicesgeolocation.IGeopoint, endPoint *devicesgeolocation.IGeopoint, options *IMapRouteDrivingOptions) (*IAsyncOperationOfMapRouteFinderResult, error) {
	result := new(*IAsyncOperationOfMapRouteFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(startPoint)), uintptr(unsafe.Pointer(endPoint)), uintptr(unsafe.Pointer(options)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapRouteFinderStatics3 is the WinRT interface Windows.Services.Maps.IMapRouteFinderStatics3.
// IID: f6098134-5913-11e6-8b77-86f30ca893d3
// Exclusive to the Windows.Services.Maps.MapRouteFinder runtime class.
type IMapRouteFinderStatics3 struct {
	syswinrt.IInspectable
}

// IID_IMapRouteFinderStatics3 is the interface identifier for IMapRouteFinderStatics3.
var IID_IMapRouteFinderStatics3 = win32.GUID{Data1: 0xf6098134, Data2: 0x5913, Data3: 0x11e6, Data4: [8]byte{0x8b, 0x77, 0x86, 0xf3, 0x0c, 0xa8, 0x93, 0xd3}}

// GetDrivingRouteFromEnhancedWaypointsAsync dispatches through IMapRouteFinderStatics3's vtable slot 6.
func (self *IMapRouteFinderStatics3) GetDrivingRouteFromEnhancedWaypointsAsync(waypoints *IIterableOfEnhancedWaypoint) (*IAsyncOperationOfMapRouteFinderResult, error) {
	result := new(*IAsyncOperationOfMapRouteFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(waypoints)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetDrivingRouteFromEnhancedWaypointsWithOptionsAsync dispatches through IMapRouteFinderStatics3's vtable slot 7.
func (self *IMapRouteFinderStatics3) GetDrivingRouteFromEnhancedWaypointsWithOptionsAsync(waypoints *IIterableOfEnhancedWaypoint, options *IMapRouteDrivingOptions) (*IAsyncOperationOfMapRouteFinderResult, error) {
	result := new(*IAsyncOperationOfMapRouteFinderResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(waypoints)), uintptr(unsafe.Pointer(options)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapRouteLeg is the WinRT interface Windows.Services.Maps.IMapRouteLeg.
// IID: 96f8b2f6-5bba-4d17-9db6-1a263fec7471
// Exclusive to the Windows.Services.Maps.MapRouteLeg runtime class.
type IMapRouteLeg struct {
	syswinrt.IInspectable
}

// IID_IMapRouteLeg is the interface identifier for IMapRouteLeg.
var IID_IMapRouteLeg = win32.GUID{Data1: 0x96f8b2f6, Data2: 0x5bba, Data3: 0x4d17, Data4: [8]byte{0x9d, 0xb6, 0x1a, 0x26, 0x3f, 0xec, 0x74, 0x71}}

// BoundingBox (propget get_BoundingBox) dispatches through IMapRouteLeg's vtable slot 6.
func (self *IMapRouteLeg) BoundingBox() (*devicesgeolocation.IGeoboundingBox, error) {
	result := new(*devicesgeolocation.IGeoboundingBox)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Path (propget get_Path) dispatches through IMapRouteLeg's vtable slot 7.
func (self *IMapRouteLeg) Path() (*devicesgeolocation.IGeopath, error) {
	result := new(*devicesgeolocation.IGeopath)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// slot 8: get_LengthInMeters skipped: float64 return cannot cross SyscallN

// EstimatedDuration (propget get_EstimatedDuration) dispatches through IMapRouteLeg's vtable slot 9.
func (self *IMapRouteLeg) EstimatedDuration() (foundation.TimeSpan, error) {
	result := new(foundation.TimeSpan)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Maneuvers (propget get_Maneuvers) dispatches through IMapRouteLeg's vtable slot 10.
func (self *IMapRouteLeg) Maneuvers() (*IVectorViewOfMapRouteManeuver, error) {
	result := new(*IVectorViewOfMapRouteManeuver)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapRouteLeg2 is the WinRT interface Windows.Services.Maps.IMapRouteLeg2.
// IID: 02e2062d-c9c6-45b8-8e54-1a10b57a17e8
// Exclusive to the Windows.Services.Maps.MapRouteLeg runtime class.
type IMapRouteLeg2 struct {
	syswinrt.IInspectable
}

// IID_IMapRouteLeg2 is the interface identifier for IMapRouteLeg2.
var IID_IMapRouteLeg2 = win32.GUID{Data1: 0x02e2062d, Data2: 0xc9c6, Data3: 0x45b8, Data4: [8]byte{0x8e, 0x54, 0x1a, 0x10, 0xb5, 0x7a, 0x17, 0xe8}}

// DurationWithoutTraffic (propget get_DurationWithoutTraffic) dispatches through IMapRouteLeg2's vtable slot 6.
func (self *IMapRouteLeg2) DurationWithoutTraffic() (foundation.TimeSpan, error) {
	result := new(foundation.TimeSpan)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// TrafficCongestion (propget get_TrafficCongestion) dispatches through IMapRouteLeg2's vtable slot 7.
func (self *IMapRouteLeg2) TrafficCongestion() (TrafficCongestion, error) {
	result := new(TrafficCongestion)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapRouteManeuver is the WinRT interface Windows.Services.Maps.IMapRouteManeuver.
// IID: ed5c17f0-a6ab-4d65-a086-fa8a7e340df2
// Exclusive to the Windows.Services.Maps.MapRouteManeuver runtime class.
type IMapRouteManeuver struct {
	syswinrt.IInspectable
}

// IID_IMapRouteManeuver is the interface identifier for IMapRouteManeuver.
var IID_IMapRouteManeuver = win32.GUID{Data1: 0xed5c17f0, Data2: 0xa6ab, Data3: 0x4d65, Data4: [8]byte{0xa0, 0x86, 0xfa, 0x8a, 0x7e, 0x34, 0x0d, 0xf2}}

// StartingPoint (propget get_StartingPoint) dispatches through IMapRouteManeuver's vtable slot 6.
func (self *IMapRouteManeuver) StartingPoint() (*devicesgeolocation.IGeopoint, error) {
	result := new(*devicesgeolocation.IGeopoint)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// slot 7: get_LengthInMeters skipped: float64 return cannot cross SyscallN

// InstructionText (propget get_InstructionText) dispatches through IMapRouteManeuver's vtable slot 8.
func (self *IMapRouteManeuver) InstructionText() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Kind (propget get_Kind) dispatches through IMapRouteManeuver's vtable slot 9.
func (self *IMapRouteManeuver) Kind() (MapRouteManeuverKind, error) {
	result := new(MapRouteManeuverKind)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ExitNumber (propget get_ExitNumber) dispatches through IMapRouteManeuver's vtable slot 10.
func (self *IMapRouteManeuver) ExitNumber() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// ManeuverNotices (propget get_ManeuverNotices) dispatches through IMapRouteManeuver's vtable slot 11.
func (self *IMapRouteManeuver) ManeuverNotices() (MapManeuverNotices, error) {
	result := new(MapManeuverNotices)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapRouteManeuver2 is the WinRT interface Windows.Services.Maps.IMapRouteManeuver2.
// IID: 5d7bcd9c-7c9b-41df-838b-eae21e4b05a9
// Exclusive to the Windows.Services.Maps.MapRouteManeuver runtime class.
type IMapRouteManeuver2 struct {
	syswinrt.IInspectable
}

// IID_IMapRouteManeuver2 is the interface identifier for IMapRouteManeuver2.
var IID_IMapRouteManeuver2 = win32.GUID{Data1: 0x5d7bcd9c, Data2: 0x7c9b, Data3: 0x41df, Data4: [8]byte{0x83, 0x8b, 0xea, 0xe2, 0x1e, 0x4b, 0x05, 0xa9}}

// slot 6: get_StartHeading skipped: float64 return cannot cross SyscallN

// slot 7: get_EndHeading skipped: float64 return cannot cross SyscallN

// StreetName (propget get_StreetName) dispatches through IMapRouteManeuver2's vtable slot 8.
func (self *IMapRouteManeuver2) StreetName() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IMapRouteManeuver3 is the WinRT interface Windows.Services.Maps.IMapRouteManeuver3.
// IID: a6a138df-0483-4166-85be-b99336c11875
// Exclusive to the Windows.Services.Maps.MapRouteManeuver runtime class.
type IMapRouteManeuver3 struct {
	syswinrt.IInspectable
}

// IID_IMapRouteManeuver3 is the interface identifier for IMapRouteManeuver3.
var IID_IMapRouteManeuver3 = win32.GUID{Data1: 0xa6a138df, Data2: 0x0483, Data3: 0x4166, Data4: [8]byte{0x85, 0xbe, 0xb9, 0x93, 0x36, 0xc1, 0x18, 0x75}}

// Warnings (propget get_Warnings) dispatches through IMapRouteManeuver3's vtable slot 6.
func (self *IMapRouteManeuver3) Warnings() (*IVectorViewOfManeuverWarning, error) {
	result := new(*IVectorViewOfManeuverWarning)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapServiceStatics is the WinRT interface Windows.Services.Maps.IMapServiceStatics.
// IID: 0144ad85-c04c-4cdd-871a-a0726d097cd4
// Exclusive to the Windows.Services.Maps.MapService runtime class.
type IMapServiceStatics struct {
	syswinrt.IInspectable
}

// IID_IMapServiceStatics is the interface identifier for IMapServiceStatics.
var IID_IMapServiceStatics = win32.GUID{Data1: 0x0144ad85, Data2: 0xc04c, Data3: 0x4cdd, Data4: [8]byte{0x87, 0x1a, 0xa0, 0x72, 0x6d, 0x09, 0x7c, 0xd4}}

// SetServiceToken (propput put_ServiceToken) dispatches through IMapServiceStatics's vtable slot 6.
func (self *IMapServiceStatics) SetServiceToken(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// ServiceToken (propget get_ServiceToken) dispatches through IMapServiceStatics's vtable slot 7.
func (self *IMapServiceStatics) ServiceToken() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IMapServiceStatics2 is the WinRT interface Windows.Services.Maps.IMapServiceStatics2.
// IID: f8193eed-9c85-40a9-8896-0fc3fd2b7c2a
// Exclusive to the Windows.Services.Maps.MapService runtime class.
type IMapServiceStatics2 struct {
	syswinrt.IInspectable
}

// IID_IMapServiceStatics2 is the interface identifier for IMapServiceStatics2.
var IID_IMapServiceStatics2 = win32.GUID{Data1: 0xf8193eed, Data2: 0x9c85, Data3: 0x40a9, Data4: [8]byte{0x88, 0x96, 0x0f, 0xc3, 0xfd, 0x2b, 0x7c, 0x2a}}

// WorldViewRegionCode (propget get_WorldViewRegionCode) dispatches through IMapServiceStatics2's vtable slot 6.
func (self *IMapServiceStatics2) WorldViewRegionCode() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IMapServiceStatics3 is the WinRT interface Windows.Services.Maps.IMapServiceStatics3.
// IID: 0a11ce20-63a7-4854-b355-d6dcda223d1b
// Exclusive to the Windows.Services.Maps.MapService runtime class.
type IMapServiceStatics3 struct {
	syswinrt.IInspectable
}

// IID_IMapServiceStatics3 is the interface identifier for IMapServiceStatics3.
var IID_IMapServiceStatics3 = win32.GUID{Data1: 0x0a11ce20, Data2: 0x63a7, Data3: 0x4854, Data4: [8]byte{0xb3, 0x55, 0xd6, 0xdc, 0xda, 0x22, 0x3d, 0x1b}}

// DataAttributions (propget get_DataAttributions) dispatches through IMapServiceStatics3's vtable slot 6.
func (self *IMapServiceStatics3) DataAttributions() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IMapServiceStatics4 is the WinRT interface Windows.Services.Maps.IMapServiceStatics4.
// IID: 088a2862-6abc-420e-945f-4cfd89c67356
// Exclusive to the Windows.Services.Maps.MapService runtime class.
type IMapServiceStatics4 struct {
	syswinrt.IInspectable
}

// IID_IMapServiceStatics4 is the interface identifier for IMapServiceStatics4.
var IID_IMapServiceStatics4 = win32.GUID{Data1: 0x088a2862, Data2: 0x6abc, Data3: 0x420e, Data4: [8]byte{0x94, 0x5f, 0x4c, 0xfd, 0x89, 0xc6, 0x73, 0x56}}

// SetDataUsagePreference (propput put_DataUsagePreference) dispatches through IMapServiceStatics4's vtable slot 6.
func (self *IMapServiceStatics4) SetDataUsagePreference(value MapServiceDataUsagePreference) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(value))
	return win32.ErrIfFailed(int32(r1))
}

// DataUsagePreference (propget get_DataUsagePreference) dispatches through IMapServiceStatics4's vtable slot 7.
func (self *IMapServiceStatics4) DataUsagePreference() (MapServiceDataUsagePreference, error) {
	result := new(MapServiceDataUsagePreference)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IPlaceInfo is the WinRT interface Windows.Services.Maps.IPlaceInfo.
// IID: 9a0810b6-31c8-4f6a-9f18-950b4c38951a
// Exclusive to the Windows.Services.Maps.PlaceInfo runtime class.
type IPlaceInfo struct {
	syswinrt.IInspectable
}

// IID_IPlaceInfo is the interface identifier for IPlaceInfo.
var IID_IPlaceInfo = win32.GUID{Data1: 0x9a0810b6, Data2: 0x31c8, Data3: 0x4f6a, Data4: [8]byte{0x9f, 0x18, 0x95, 0x0b, 0x4c, 0x38, 0x95, 0x1a}}

// slot 6: Show skipped: by-value Windows.Foundation.Rect parameter selection does not flatten to one integer word

// slot 7: Show skipped: by-value Windows.Foundation.Rect parameter selection does not flatten to one integer word

// Identifier (propget get_Identifier) dispatches through IPlaceInfo's vtable slot 8.
func (self *IPlaceInfo) Identifier() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// DisplayName (propget get_DisplayName) dispatches through IPlaceInfo's vtable slot 9.
func (self *IPlaceInfo) DisplayName() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// DisplayAddress (propget get_DisplayAddress) dispatches through IPlaceInfo's vtable slot 10.
func (self *IPlaceInfo) DisplayAddress() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Geoshape (propget get_Geoshape) dispatches through IPlaceInfo's vtable slot 11.
func (self *IPlaceInfo) Geoshape() (*devicesgeolocation.IGeoshape, error) {
	result := new(*devicesgeolocation.IGeoshape)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IPlaceInfoCreateOptions is the WinRT interface Windows.Services.Maps.IPlaceInfoCreateOptions.
// IID: cd33c125-67f1-4bb3-9907-ecce939b0399
// Exclusive to the Windows.Services.Maps.PlaceInfoCreateOptions runtime class.
type IPlaceInfoCreateOptions struct {
	syswinrt.IInspectable
}

// IID_IPlaceInfoCreateOptions is the interface identifier for IPlaceInfoCreateOptions.
var IID_IPlaceInfoCreateOptions = win32.GUID{Data1: 0xcd33c125, Data2: 0x67f1, Data3: 0x4bb3, Data4: [8]byte{0x99, 0x07, 0xec, 0xce, 0x93, 0x9b, 0x03, 0x99}}

// SetDisplayName (propput put_DisplayName) dispatches through IPlaceInfoCreateOptions's vtable slot 6.
func (self *IPlaceInfoCreateOptions) SetDisplayName(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// DisplayName (propget get_DisplayName) dispatches through IPlaceInfoCreateOptions's vtable slot 7.
func (self *IPlaceInfoCreateOptions) DisplayName() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// SetDisplayAddress (propput put_DisplayAddress) dispatches through IPlaceInfoCreateOptions's vtable slot 8.
func (self *IPlaceInfoCreateOptions) SetDisplayAddress(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// DisplayAddress (propget get_DisplayAddress) dispatches through IPlaceInfoCreateOptions's vtable slot 9.
func (self *IPlaceInfoCreateOptions) DisplayAddress() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IPlaceInfoStatics is the WinRT interface Windows.Services.Maps.IPlaceInfoStatics.
// IID: 82b9ff71-6cd0-48a4-afd9-5ed82097936b
// Exclusive to the Windows.Services.Maps.PlaceInfo runtime class.
type IPlaceInfoStatics struct {
	syswinrt.IInspectable
}

// IID_IPlaceInfoStatics is the interface identifier for IPlaceInfoStatics.
var IID_IPlaceInfoStatics = win32.GUID{Data1: 0x82b9ff71, Data2: 0x6cd0, Data3: 0x48a4, Data4: [8]byte{0xaf, 0xd9, 0x5e, 0xd8, 0x20, 0x97, 0x93, 0x6b}}

// Create dispatches through IPlaceInfoStatics's vtable slot 6.
func (self *IPlaceInfoStatics) Create(referencePoint *devicesgeolocation.IGeopoint) (*IPlaceInfo, error) {
	result := new(*IPlaceInfo)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(referencePoint)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateWithGeopointAndOptions dispatches through IPlaceInfoStatics's vtable slot 7.
func (self *IPlaceInfoStatics) CreateWithGeopointAndOptions(referencePoint *devicesgeolocation.IGeopoint, options *IPlaceInfoCreateOptions) (*IPlaceInfo, error) {
	result := new(*IPlaceInfo)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(referencePoint)), uintptr(unsafe.Pointer(options)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateFromIdentifier dispatches through IPlaceInfoStatics's vtable slot 8.
func (self *IPlaceInfoStatics) CreateFromIdentifier(identifier string) (*IPlaceInfo, error) {
	hIdentifier, err := winrt.NewHString(identifier)
	if err != nil {
		return nil, err
	}
	defer hIdentifier.Close()
	result := new(*IPlaceInfo)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hIdentifier.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateFromIdentifierWithOptions dispatches through IPlaceInfoStatics's vtable slot 9.
func (self *IPlaceInfoStatics) CreateFromIdentifierWithOptions(identifier string, defaultPoint *devicesgeolocation.IGeopoint, options *IPlaceInfoCreateOptions) (*IPlaceInfo, error) {
	hIdentifier, err := winrt.NewHString(identifier)
	if err != nil {
		return nil, err
	}
	defer hIdentifier.Close()
	result := new(*IPlaceInfo)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(hIdentifier.Raw()), uintptr(unsafe.Pointer(defaultPoint)), uintptr(unsafe.Pointer(options)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateFromMapLocation dispatches through IPlaceInfoStatics's vtable slot 10.
func (self *IPlaceInfoStatics) CreateFromMapLocation(location *IMapLocation) (*IPlaceInfo, error) {
	result := new(*IPlaceInfo)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(location)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IsShowSupported (propget get_IsShowSupported) dispatches through IPlaceInfoStatics's vtable slot 11.
func (self *IPlaceInfoStatics) IsShowSupported() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// IPlaceInfoStatics2 is the WinRT interface Windows.Services.Maps.IPlaceInfoStatics2.
// IID: 730f0249-4047-44a3-8f81-2550a5216370
// Exclusive to the Windows.Services.Maps.PlaceInfo runtime class.
type IPlaceInfoStatics2 struct {
	syswinrt.IInspectable
}

// IID_IPlaceInfoStatics2 is the interface identifier for IPlaceInfoStatics2.
var IID_IPlaceInfoStatics2 = win32.GUID{Data1: 0x730f0249, Data2: 0x4047, Data3: 0x44a3, Data4: [8]byte{0x8f, 0x81, 0x25, 0x50, 0xa5, 0x21, 0x63, 0x70}}

// CreateFromAddress dispatches through IPlaceInfoStatics2's vtable slot 6.
func (self *IPlaceInfoStatics2) CreateFromAddress(displayAddress string) (*IPlaceInfo, error) {
	hDisplayAddress, err := winrt.NewHString(displayAddress)
	if err != nil {
		return nil, err
	}
	defer hDisplayAddress.Close()
	result := new(*IPlaceInfo)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hDisplayAddress.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateFromAddressWithName dispatches through IPlaceInfoStatics2's vtable slot 7.
func (self *IPlaceInfoStatics2) CreateFromAddressWithName(displayAddress string, displayName string) (*IPlaceInfo, error) {
	hDisplayAddress, err := winrt.NewHString(displayAddress)
	if err != nil {
		return nil, err
	}
	defer hDisplayAddress.Close()
	hDisplayName, err := winrt.NewHString(displayName)
	if err != nil {
		return nil, err
	}
	defer hDisplayName.Close()
	result := new(*IPlaceInfo)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(hDisplayAddress.Raw()), uintptr(hDisplayName.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
