// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package desktop

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// IDesktopWindowTarget is the WinRT interface Windows.UI.Composition.Desktop.IDesktopWindowTarget.
// IID: 6329d6ca-3366-490e-9db3-25312929ac51
// Exclusive to the Windows.UI.Composition.Desktop.DesktopWindowTarget runtime class.
type IDesktopWindowTarget struct {
	syswinrt.IInspectable
}

// IID_IDesktopWindowTarget is the interface identifier for IDesktopWindowTarget.
var IID_IDesktopWindowTarget = win32.GUID{Data1: 0x6329d6ca, Data2: 0x3366, Data3: 0x490e, Data4: [8]byte{0x9d, 0xb3, 0x25, 0x31, 0x29, 0x29, 0xac, 0x51}}

// IsTopmost (propget get_IsTopmost) dispatches through IDesktopWindowTarget's vtable slot 6.
func (self *IDesktopWindowTarget) IsTopmost() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}
