// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package viewmanagement

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/ui"
	uiwindowmanagement "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/ui/windowmanagement"
)

// IAsyncOperationOfBool is the WinRT interface Windows.Foundation.IAsyncOperation`1<Bool>.
// IID: cdb5efb3-5788-509d-9be1-71ccb8a3362a
// Requires: Windows.Foundation.IAsyncInfo.
type IAsyncOperationOfBool struct {
	syswinrt.IInspectable
}

// IID_IAsyncOperationOfBool is the interface identifier for IAsyncOperationOfBool.
var IID_IAsyncOperationOfBool = win32.GUID{Data1: 0xcdb5efb3, Data2: 0x5788, Data3: 0x509d, Data4: [8]byte{0x9b, 0xe1, 0x71, 0xcc, 0xb8, 0xa3, 0x36, 0x2a}}

// SetCompleted (propput put_Completed) dispatches through IAsyncOperationOfBool's vtable slot 6.
// A nil handler passes NULL at the ABI (WinRT accepts it where a handler may be cleared).
func (self *IAsyncOperationOfBool) SetCompleted(handler *AsyncOperationCompletedHandlerOfBool) error {
	_handler := uintptr(0)
	if handler != nil {
		_handler = handler.Ptr()
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), _handler)
	return win32.ErrIfFailed(int32(r1))
}

// slot 7: get_Completed skipped: parameterized type Windows.Foundation.AsyncOperationCompletedHandler`1

// GetResults dispatches through IAsyncOperationOfBool's vtable slot 8.
func (self *IAsyncOperationOfBool) GetResults() (bool, error) {
	var result byte
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(&result)))
	return result != 0, win32.ErrIfFailed(int32(r1))
}

// Await registers a Completed handler and blocks until IAsyncOperationOfBool reaches
// a terminal state, then returns GetResults() — or, when the status is not
// Completed, an error carrying the status and the IAsyncInfo error code (see
// winrt.AsyncError). Safe on an operation that already completed: WinRT
// invokes a handler assigned after completion immediately. put_Completed
// accepts a single assignment per operation, so Await (or SetCompleted) can
// be used at most once per instance. Await blocks indefinitely by design; a
// context-aware variant is future work. The completion signal is sent from
// the handler's Invoke, which the delegate runtime runs on a fresh goroutine
// — it never contends with the runtime's callback worker, so a completed
// operation cannot deadlock Await.
func (self *IAsyncOperationOfBool) Await() (bool, error) {
	completion := make(chan foundation.AsyncStatus, 1)
	handler, err := NewAsyncOperationCompletedHandlerOfBool(func(_ *IAsyncOperationOfBool, asyncStatus foundation.AsyncStatus) {
		completion <- asyncStatus
	})
	if err != nil {
		return false, err
	}
	defer handler.Close()
	if err := self.SetCompleted(handler); err != nil {
		return false, err
	}
	status := <-completion
	if status != foundation.AsyncStatusCompleted {
		info, err := winrt.QueryInterface[foundation.IAsyncInfo](unsafe.Pointer(self), &foundation.IID_IAsyncInfo)
		if err != nil {
			return false, err
		}
		defer info.Release()
		code, err := info.ErrorCode()
		if err != nil {
			return false, err
		}
		return false, winrt.AsyncError(int32(status), code)
	}
	return self.GetResults()
}

// IReferenceOfColor is the WinRT interface Windows.Foundation.IReference`1<Windows.UI.Color>.
// IID: ab8e5d11-b0c1-5a21-95ae-f16bf3a37624
// Requires: Windows.Foundation.IPropertyValue.
type IReferenceOfColor struct {
	syswinrt.IInspectable
}

// IID_IReferenceOfColor is the interface identifier for IReferenceOfColor.
var IID_IReferenceOfColor = win32.GUID{Data1: 0xab8e5d11, Data2: 0xb0c1, Data3: 0x5a21, Data4: [8]byte{0x95, 0xae, 0xf1, 0x6b, 0xf3, 0xa3, 0x76, 0x24}}

// Value (propget get_Value) dispatches through IReferenceOfColor's vtable slot 6.
func (self *IReferenceOfColor) Value() (ui.Color, error) {
	var result ui.Color
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(&result)))
	return result, win32.ErrIfFailed(int32(r1))
}

// IVectorViewOfDisplayRegion is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Windows.UI.WindowManagement.DisplayRegion>.
// IID: 9460debb-a0d6-5ab8-84f5-9087f2a6bb67
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.UI.WindowManagement.DisplayRegion>.
type IVectorViewOfDisplayRegion struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfDisplayRegion is the interface identifier for IVectorViewOfDisplayRegion.
var IID_IVectorViewOfDisplayRegion = win32.GUID{Data1: 0x9460debb, Data2: 0xa0d6, Data3: 0x5ab8, Data4: [8]byte{0x84, 0xf5, 0x90, 0x87, 0xf2, 0xa6, 0xbb, 0x67}}

// GetAt dispatches through IVectorViewOfDisplayRegion's vtable slot 6.
func (self *IVectorViewOfDisplayRegion) GetAt(index uint32) (*uiwindowmanagement.IDisplayRegion, error) {
	var result *uiwindowmanagement.IDisplayRegion
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(&result)))
	return result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfDisplayRegion's vtable slot 7.
func (self *IVectorViewOfDisplayRegion) Size() (uint32, error) {
	var result uint32
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(&result)))
	return result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfDisplayRegion's vtable slot 8.
func (self *IVectorViewOfDisplayRegion) IndexOf(value *uiwindowmanagement.IDisplayRegion, index *uint32) (bool, error) {
	var result byte
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(unsafe.Pointer(index)), uintptr(unsafe.Pointer(&result)))
	return result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array
