// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package lights

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
)

// AsyncOperationCompletedHandlerOfIBuffer is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Storage.Streams.IBuffer>.
// IID: 51c3d2fd-b8a1-5620-b746-7ee6d533aca3
type AsyncOperationCompletedHandlerOfIBuffer struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfIBuffer is the delegate identifier for AsyncOperationCompletedHandlerOfIBuffer.
var IID_AsyncOperationCompletedHandlerOfIBuffer = win32.GUID{Data1: 0x51c3d2fd, Data2: 0xb8a1, Data3: 0x5620, Data4: [8]byte{0xb7, 0x46, 0x7e, 0xe6, 0xd5, 0x33, 0xac, 0xa3}}

// NewAsyncOperationCompletedHandlerOfIBuffer wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Storage.Streams.IBuffer>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfIBuffer(fn func(asyncInfo *IAsyncOperationOfIBuffer, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfIBuffer, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfIBuffer, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfIBuffer)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfIBuffer{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfIBuffer) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfIBuffer) Close() { h.delegate.Release() }

// AsyncOperationCompletedHandlerOfLamp is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Devices.Lights.Lamp>.
// IID: 191a8c6e-60dd-5a21-a53c-bf3f940a1dde
type AsyncOperationCompletedHandlerOfLamp struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfLamp is the delegate identifier for AsyncOperationCompletedHandlerOfLamp.
var IID_AsyncOperationCompletedHandlerOfLamp = win32.GUID{Data1: 0x191a8c6e, Data2: 0x60dd, Data3: 0x5a21, Data4: [8]byte{0xa5, 0x3c, 0xbf, 0x3f, 0x94, 0x0a, 0x1d, 0xde}}

// NewAsyncOperationCompletedHandlerOfLamp wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Devices.Lights.Lamp>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfLamp(fn func(asyncInfo *IAsyncOperationOfLamp, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfLamp, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfLamp, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfLamp)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfLamp{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfLamp) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfLamp) Close() { h.delegate.Release() }

// AsyncOperationCompletedHandlerOfLampArray is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Devices.Lights.LampArray>.
// IID: eba415db-42af-54b8-a2f3-5b34494c8972
type AsyncOperationCompletedHandlerOfLampArray struct {
	delegate *winrt.Delegate
}

// IID_AsyncOperationCompletedHandlerOfLampArray is the delegate identifier for AsyncOperationCompletedHandlerOfLampArray.
var IID_AsyncOperationCompletedHandlerOfLampArray = win32.GUID{Data1: 0xeba415db, Data2: 0x42af, Data3: 0x54b8, Data4: [8]byte{0xa2, 0xf3, 0x5b, 0x34, 0x49, 0x4c, 0x89, 0x72}}

// NewAsyncOperationCompletedHandlerOfLampArray wraps fn as a COM-callable Windows.Foundation.AsyncOperationCompletedHandler`1<Windows.Devices.Lights.LampArray>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewAsyncOperationCompletedHandlerOfLampArray(fn func(asyncInfo *IAsyncOperationOfLampArray, asyncStatus foundation.AsyncStatus)) (*AsyncOperationCompletedHandlerOfLampArray, error) {
	delegate, err := winrt.NewDelegate(IID_AsyncOperationCompletedHandlerOfLampArray, 2, func(raw []uintptr) uintptr {
		fn((*IAsyncOperationOfLampArray)(unsafe.Pointer(raw[0])), foundation.AsyncStatus(raw[1]))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &AsyncOperationCompletedHandlerOfLampArray{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *AsyncOperationCompletedHandlerOfLampArray) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *AsyncOperationCompletedHandlerOfLampArray) Close() { h.delegate.Release() }

// TypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Lights.Lamp, Windows.Devices.Lights.LampAvailabilityChangedEventArgs>.
// IID: 556a02d9-7685-576f-89ca-b62dc481d29d
type TypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs is the delegate identifier for TypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs.
var IID_TypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs = win32.GUID{Data1: 0x556a02d9, Data2: 0x7685, Data3: 0x576f, Data4: [8]byte{0x89, 0xca, 0xb6, 0x2d, 0xc4, 0x81, 0xd2, 0x9d}}

// NewTypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Lights.Lamp, Windows.Devices.Lights.LampAvailabilityChangedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs(fn func(sender *ILamp, args *ILampAvailabilityChangedEventArgs)) (*TypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*ILamp)(unsafe.Pointer(raw[0])), (*ILampAvailabilityChangedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfLampAndLampAvailabilityChangedEventArgs) Close() { h.delegate.Release() }

// TypedEventHandlerOfLampArrayAndObject is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.Devices.Lights.LampArray, Object>.
// IID: 1229c9f2-783e-5bc8-9a1e-772e45e66401
type TypedEventHandlerOfLampArrayAndObject struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfLampArrayAndObject is the delegate identifier for TypedEventHandlerOfLampArrayAndObject.
var IID_TypedEventHandlerOfLampArrayAndObject = win32.GUID{Data1: 0x1229c9f2, Data2: 0x783e, Data3: 0x5bc8, Data4: [8]byte{0x9a, 0x1e, 0x77, 0x2e, 0x45, 0xe6, 0x64, 0x01}}

// NewTypedEventHandlerOfLampArrayAndObject wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.Devices.Lights.LampArray, Object>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfLampArrayAndObject(fn func(sender *ILampArray, args *syswinrt.IInspectable)) (*TypedEventHandlerOfLampArrayAndObject, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfLampArrayAndObject, 2, func(raw []uintptr) uintptr {
		fn((*ILampArray)(unsafe.Pointer(raw[0])), (*syswinrt.IInspectable)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfLampArrayAndObject{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfLampArrayAndObject) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfLampArrayAndObject) Close() { h.delegate.Release() }
