// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package lockscreen

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// TypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.ApplicationModel.LockScreen.LockApplicationHost, Windows.ApplicationModel.LockScreen.LockScreenUnlockingEventArgs>.
// IID: 002e5776-8a5b-5b93-8c6c-9c4c8788f5b4
type TypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs is the delegate identifier for TypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs.
var IID_TypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs = win32.GUID{Data1: 0x002e5776, Data2: 0x8a5b, Data3: 0x5b93, Data4: [8]byte{0x8c, 0x6c, 0x9c, 0x4c, 0x87, 0x88, 0xf5, 0xb4}}

// NewTypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.ApplicationModel.LockScreen.LockApplicationHost, Windows.ApplicationModel.LockScreen.LockScreenUnlockingEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs(fn func(sender *ILockApplicationHost, args *ILockScreenUnlockingEventArgs)) (*TypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*ILockApplicationHost)(unsafe.Pointer(raw[0])), (*ILockScreenUnlockingEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfLockScreenInfoAndObject is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Windows.ApplicationModel.LockScreen.LockScreenInfo, Object>.
// IID: 8be9e6a3-f88a-5429-8da3-676b7d4f1a5b
type TypedEventHandlerOfLockScreenInfoAndObject struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfLockScreenInfoAndObject is the delegate identifier for TypedEventHandlerOfLockScreenInfoAndObject.
var IID_TypedEventHandlerOfLockScreenInfoAndObject = win32.GUID{Data1: 0x8be9e6a3, Data2: 0xf88a, Data3: 0x5429, Data4: [8]byte{0x8d, 0xa3, 0x67, 0x6b, 0x7d, 0x4f, 0x1a, 0x5b}}

// NewTypedEventHandlerOfLockScreenInfoAndObject wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Windows.ApplicationModel.LockScreen.LockScreenInfo, Object>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfLockScreenInfoAndObject(fn func(sender *ILockScreenInfo, args *syswinrt.IInspectable)) (*TypedEventHandlerOfLockScreenInfoAndObject, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfLockScreenInfoAndObject, 2, func(raw []uintptr) uintptr {
		fn((*ILockScreenInfo)(unsafe.Pointer(raw[0])), (*syswinrt.IInspectable)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfLockScreenInfoAndObject{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfLockScreenInfoAndObject) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can
// still invoke the handler (after the event source removed it or closed);
// the runtime keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfLockScreenInfoAndObject) Close() { h.delegate.Release() }
