// Code generated by go-bindings-winrt-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package lockscreen

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
	storagestreams "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/storage/streams"
)

// ILockApplicationHost is the WinRT interface Windows.ApplicationModel.LockScreen.ILockApplicationHost.
// IID: 38ee31ad-d94f-4e7c-81fa-4f4436506281
// Exclusive to the Windows.ApplicationModel.LockScreen.LockApplicationHost runtime class.
type ILockApplicationHost struct {
	syswinrt.IInspectable
}

// IID_ILockApplicationHost is the interface identifier for ILockApplicationHost.
var IID_ILockApplicationHost = win32.GUID{Data1: 0x38ee31ad, Data2: 0xd94f, Data3: 0x4e7c, Data4: [8]byte{0x81, 0xfa, 0x4f, 0x44, 0x36, 0x50, 0x62, 0x81}}

// RequestUnlock dispatches through ILockApplicationHost's vtable slot 6.
func (self *ILockApplicationHost) RequestUnlock() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// AddUnlocking (event add add_Unlocking) dispatches through ILockApplicationHost's vtable slot 7.
// The handler stays registered (and referenced by the runtime) until the
// returned token is passed to RemoveUnlocking.
func (self *ILockApplicationHost) AddUnlocking(handler *TypedEventHandlerOfLockApplicationHostAndLockScreenUnlockingEventArgs) (syswinrt.EventRegistrationToken, error) {
	result := new(syswinrt.EventRegistrationToken)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), handler.Ptr(), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemoveUnlocking (event remove remove_Unlocking) dispatches through ILockApplicationHost's vtable slot 8,
// unregistering the Unlocking handler the token was returned for.
func (self *ILockApplicationHost) RemoveUnlocking(token syswinrt.EventRegistrationToken) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(token.Value))
	return win32.ErrIfFailed(int32(r1))
}

// ILockApplicationHostStatics is the WinRT interface Windows.ApplicationModel.LockScreen.ILockApplicationHostStatics.
// IID: f48fab8e-23d7-4e63-96a1-666ff52d3b2c
// Exclusive to the Windows.ApplicationModel.LockScreen.LockApplicationHost runtime class.
type ILockApplicationHostStatics struct {
	syswinrt.IInspectable
}

// IID_ILockApplicationHostStatics is the interface identifier for ILockApplicationHostStatics.
var IID_ILockApplicationHostStatics = win32.GUID{Data1: 0xf48fab8e, Data2: 0x23d7, Data3: 0x4e63, Data4: [8]byte{0x96, 0xa1, 0x66, 0x6f, 0xf5, 0x2d, 0x3b, 0x2c}}

// GetForCurrentView dispatches through ILockApplicationHostStatics's vtable slot 6.
func (self *ILockApplicationHostStatics) GetForCurrentView() (*ILockApplicationHost, error) {
	result := new(*ILockApplicationHost)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ILockScreenBadge is the WinRT interface Windows.ApplicationModel.LockScreen.ILockScreenBadge.
// IID: e95105d9-2bff-4db0-9b4f-3824778b9c9a
// Exclusive to the Windows.ApplicationModel.LockScreen.LockScreenBadge runtime class.
type ILockScreenBadge struct {
	syswinrt.IInspectable
}

// IID_ILockScreenBadge is the interface identifier for ILockScreenBadge.
var IID_ILockScreenBadge = win32.GUID{Data1: 0xe95105d9, Data2: 0x2bff, Data3: 0x4db0, Data4: [8]byte{0x9b, 0x4f, 0x38, 0x24, 0x77, 0x8b, 0x9c, 0x9a}}

// Logo (propget get_Logo) dispatches through ILockScreenBadge's vtable slot 6.
func (self *ILockScreenBadge) Logo() (*storagestreams.IRandomAccessStream, error) {
	result := new(*storagestreams.IRandomAccessStream)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Glyph (propget get_Glyph) dispatches through ILockScreenBadge's vtable slot 7.
func (self *ILockScreenBadge) Glyph() (*storagestreams.IRandomAccessStream, error) {
	result := new(*storagestreams.IRandomAccessStream)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Number (propget get_Number) dispatches through ILockScreenBadge's vtable slot 8.
func (self *ILockScreenBadge) Number() (*IReferenceOfUInt32, error) {
	result := new(*IReferenceOfUInt32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// AutomationName (propget get_AutomationName) dispatches through ILockScreenBadge's vtable slot 9.
func (self *ILockScreenBadge) AutomationName() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// LaunchApp dispatches through ILockScreenBadge's vtable slot 10.
func (self *ILockScreenBadge) LaunchApp() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// ILockScreenInfo is the WinRT interface Windows.ApplicationModel.LockScreen.ILockScreenInfo.
// IID: f59aa65c-9711-4dc9-a630-95b6cb8cdad0
// Exclusive to the Windows.ApplicationModel.LockScreen.LockScreenInfo runtime class.
type ILockScreenInfo struct {
	syswinrt.IInspectable
}

// IID_ILockScreenInfo is the interface identifier for ILockScreenInfo.
var IID_ILockScreenInfo = win32.GUID{Data1: 0xf59aa65c, Data2: 0x9711, Data3: 0x4dc9, Data4: [8]byte{0xa6, 0x30, 0x95, 0xb6, 0xcb, 0x8c, 0xda, 0xd0}}

// AddLockScreenImageChanged (event add add_LockScreenImageChanged) dispatches through ILockScreenInfo's vtable slot 6.
// The handler stays registered (and referenced by the runtime) until the
// returned token is passed to RemoveLockScreenImageChanged.
func (self *ILockScreenInfo) AddLockScreenImageChanged(handler *TypedEventHandlerOfLockScreenInfoAndObject) (syswinrt.EventRegistrationToken, error) {
	result := new(syswinrt.EventRegistrationToken)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), handler.Ptr(), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemoveLockScreenImageChanged (event remove remove_LockScreenImageChanged) dispatches through ILockScreenInfo's vtable slot 7,
// unregistering the LockScreenImageChanged handler the token was returned for.
func (self *ILockScreenInfo) RemoveLockScreenImageChanged(token syswinrt.EventRegistrationToken) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(token.Value))
	return win32.ErrIfFailed(int32(r1))
}

// LockScreenImage (propget get_LockScreenImage) dispatches through ILockScreenInfo's vtable slot 8.
func (self *ILockScreenInfo) LockScreenImage() (*storagestreams.IRandomAccessStream, error) {
	result := new(*storagestreams.IRandomAccessStream)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// AddBadgesChanged (event add add_BadgesChanged) dispatches through ILockScreenInfo's vtable slot 9.
// The handler stays registered (and referenced by the runtime) until the
// returned token is passed to RemoveBadgesChanged.
func (self *ILockScreenInfo) AddBadgesChanged(handler *TypedEventHandlerOfLockScreenInfoAndObject) (syswinrt.EventRegistrationToken, error) {
	result := new(syswinrt.EventRegistrationToken)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), handler.Ptr(), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemoveBadgesChanged (event remove remove_BadgesChanged) dispatches through ILockScreenInfo's vtable slot 10,
// unregistering the BadgesChanged handler the token was returned for.
func (self *ILockScreenInfo) RemoveBadgesChanged(token syswinrt.EventRegistrationToken) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(token.Value))
	return win32.ErrIfFailed(int32(r1))
}

// Badges (propget get_Badges) dispatches through ILockScreenInfo's vtable slot 11.
func (self *ILockScreenInfo) Badges() (*IVectorViewOfLockScreenBadge, error) {
	result := new(*IVectorViewOfLockScreenBadge)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// AddDetailTextChanged (event add add_DetailTextChanged) dispatches through ILockScreenInfo's vtable slot 12.
// The handler stays registered (and referenced by the runtime) until the
// returned token is passed to RemoveDetailTextChanged.
func (self *ILockScreenInfo) AddDetailTextChanged(handler *TypedEventHandlerOfLockScreenInfoAndObject) (syswinrt.EventRegistrationToken, error) {
	result := new(syswinrt.EventRegistrationToken)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), handler.Ptr(), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemoveDetailTextChanged (event remove remove_DetailTextChanged) dispatches through ILockScreenInfo's vtable slot 13,
// unregistering the DetailTextChanged handler the token was returned for.
func (self *ILockScreenInfo) RemoveDetailTextChanged(token syswinrt.EventRegistrationToken) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(token.Value))
	return win32.ErrIfFailed(int32(r1))
}

// DetailText (propget get_DetailText) dispatches through ILockScreenInfo's vtable slot 14.
func (self *ILockScreenInfo) DetailText() (*IVectorViewOfString, error) {
	result := new(*IVectorViewOfString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// AddAlarmIconChanged (event add add_AlarmIconChanged) dispatches through ILockScreenInfo's vtable slot 15.
// The handler stays registered (and referenced by the runtime) until the
// returned token is passed to RemoveAlarmIconChanged.
func (self *ILockScreenInfo) AddAlarmIconChanged(handler *TypedEventHandlerOfLockScreenInfoAndObject) (syswinrt.EventRegistrationToken, error) {
	result := new(syswinrt.EventRegistrationToken)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)), handler.Ptr(), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemoveAlarmIconChanged (event remove remove_AlarmIconChanged) dispatches through ILockScreenInfo's vtable slot 16,
// unregistering the AlarmIconChanged handler the token was returned for.
func (self *ILockScreenInfo) RemoveAlarmIconChanged(token syswinrt.EventRegistrationToken) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[16], uintptr(unsafe.Pointer(self)), uintptr(token.Value))
	return win32.ErrIfFailed(int32(r1))
}

// AlarmIcon (propget get_AlarmIcon) dispatches through ILockScreenInfo's vtable slot 17.
func (self *ILockScreenInfo) AlarmIcon() (*storagestreams.IRandomAccessStream, error) {
	result := new(*storagestreams.IRandomAccessStream)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[17], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ILockScreenUnlockingDeferral is the WinRT interface Windows.ApplicationModel.LockScreen.ILockScreenUnlockingDeferral.
// IID: 7e7d1ad6-5203-43e7-9bd6-7c3947d1e3fe
// Exclusive to the Windows.ApplicationModel.LockScreen.LockScreenUnlockingDeferral runtime class.
type ILockScreenUnlockingDeferral struct {
	syswinrt.IInspectable
}

// IID_ILockScreenUnlockingDeferral is the interface identifier for ILockScreenUnlockingDeferral.
var IID_ILockScreenUnlockingDeferral = win32.GUID{Data1: 0x7e7d1ad6, Data2: 0x5203, Data3: 0x43e7, Data4: [8]byte{0x9b, 0xd6, 0x7c, 0x39, 0x47, 0xd1, 0xe3, 0xfe}}

// Complete dispatches through ILockScreenUnlockingDeferral's vtable slot 6.
func (self *ILockScreenUnlockingDeferral) Complete() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// ILockScreenUnlockingEventArgs is the WinRT interface Windows.ApplicationModel.LockScreen.ILockScreenUnlockingEventArgs.
// IID: 44e6c007-75fb-4abb-9f8b-824748900c71
// Exclusive to the Windows.ApplicationModel.LockScreen.LockScreenUnlockingEventArgs runtime class.
type ILockScreenUnlockingEventArgs struct {
	syswinrt.IInspectable
}

// IID_ILockScreenUnlockingEventArgs is the interface identifier for ILockScreenUnlockingEventArgs.
var IID_ILockScreenUnlockingEventArgs = win32.GUID{Data1: 0x44e6c007, Data2: 0x75fb, Data3: 0x4abb, Data4: [8]byte{0x9f, 0x8b, 0x82, 0x47, 0x48, 0x90, 0x0c, 0x71}}

// GetDeferral dispatches through ILockScreenUnlockingEventArgs's vtable slot 6.
func (self *ILockScreenUnlockingEventArgs) GetDeferral() (*ILockScreenUnlockingDeferral, error) {
	result := new(*ILockScreenUnlockingDeferral)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Deadline (propget get_Deadline) dispatches through ILockScreenUnlockingEventArgs's vtable slot 7.
func (self *ILockScreenUnlockingEventArgs) Deadline() (foundation.DateTime, error) {
	result := new(foundation.DateTime)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
